### ISSUE TITLE
ShouldBe for enumerables fails

### ISSUE THREAD

**Issue by xerxesb** [shouldly/shouldly#100]
```
[Test]
public void ShouldBe_Enumerable_Matching()
{
    new int[] { 1 }.ShouldBe(new int[] { 1 });
}
```

fails with 

```
Shouldly.ChuckedAWobbly : 
    new int[] { 1 }
        should be
    [1]
        but was
    [1]
        difference
    [1]
```

which seems cray cray. Enumerable matching should just work

**Comment by DasNaughtie** [comment]
I'm still seeing the same issue and don't understand...making me angry!!

Shouldly.ShouldAssertException : [Domain.Model.Product (54467399), Domain.Model.Product (35113868), Domain.Model.Product (36620214)]
    should be
[Domain.Model.Product (37296927), Domain.Model.Product (640117), Domain.Model.Product (28805302)]
    but was not
    difference
[*Domain.Model.Product (54467399)*, *Domain.Model.Product (35113868)*, *Domain.Model.Product (36620214)*]

Why is it adding those numbers which make it fail comparison?
