### ISSUE TITLE
Should.ThrowExact<T>

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#127]
`Should.Throw<Exception>(()=>{throw new IOException();});` passes, it would be good to have an overload which allows enforcing the exact exception types and not allowing a derived exception type to be thrown

**Comment by mikernet** [comment]
I don't think this should have been closed :/

If I want to make sure one of my methods throws `IOException` exactly and not `FileNotFoundException` then there isn't a decent way to do this. MSTest has `Throws` and `ThrowsExactly`, and I think at least some other test frameworks have similar functionality.
