### ISSUE TITLE
.ShouldNotBeNull();

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#134]
I would like to add `.ShouldNotBeNull()` which can have a r# annotation validating that the now cannot be null. `.ShouldNotBe(null)` cannot be made to give r# the same information.

Thoughts?

**Comment by Roemer** [comment]
Was this already added now? Because I still get R# warnings on an object after checking it with ShouldNotBeNull.

**Comment by JosephWoodward** [comment]
Hi @Roemer, could you provide an example of when you're seeing the R# warnings please?

**Comment by Roemer** [comment]
```
var code = codes.FirstOrDefault(v => v.Year == 2016);
code.ShouldNotBeNull();
code.SomeOtherProperty.ShouldBeNull();
```
The "code" on the last line is reported by R#

**Comment by JakeGinnivan** [comment]
We don't have r# annotations on this method =/

https://github.com/shouldly/shouldly/blob/master/src/Shouldly/ShouldlyExtensionMethods/ShouldBeNullExtensions.cs#L27

We actually have them on `ShouldNotBe(null);`

We need to add `[ContractAnnotation("actual:null => halt")]` to those methods to tell r# that we throw if actual is null.

**Comment by JosephWoodward** [comment]
*Hand up* My fault! I'll create a PR for that.

**Comment by JosephWoodward** [comment]
There we go @Roemer and @JakeGinnivan, this will be fixed in the new release: https://github.com/shouldly/shouldly/commit/522e30e0d87b2801b2dd942c194079103dcfd04e

**Comment by Roemer** [comment]
@JosephWoodward Cool, thanks :)
