### ISSUE TITLE
Improved failure message - "ShouldBeOneOf"/"ShouldNotBeOneOf" can display the variable name

### ISSUE THREAD

**Issue by chaitanyagurrapu** [shouldly/shouldly#142]
It might be better to tackle this after issue #52 is resolved, but the error message for "ShouldBeOneOf" can be improved by using the variable name of the IEnumerable being tested.

For example, the test ..

``` c#
[Test]
public void ShouldBeOneOf()
{
    var apu = new Person() { Name = "Apu" };
    var homer = new Person() { Name = "Homer" };
    var skinner = new Person() { Name = "Skinner" };
    var barney = new Person() { Name = "Barney" };
    var theBeSharps = new List<Person>() { homer, skinner, barney };

    apu.ShouldBeOneOf(theBeSharps.ToArray());
}
```

... currently shows the following message on failure ...

```
Shouldly.ChuckedAWobbly : 
    apu
        should be one of
    [Simpsons.Person, Simpsons.Person, Simpsons.Person]
        but was
    Simpsons.Person
```

... but it would be better if it showed something like ...

```
Shouldly.ChuckedAWobbly : 
    apu
        should be one of
    theBeSharps
        but was not
```

Similar thing with the `ShouldNotBeOneOf` , `ShouldContain` , `ShouldNotContain`, `ShouldBeOneOf`, `ShouldBeSubsetOf`,  messages.

**Comment by SimonCropp** [comment]
@chaitanyagurrapu are you still interested in this feature?

**Comment by chaitanyagurrapu** [comment]
@SimonCropp I haven't used Shouldly in a little while so I am afraid I have to say that I am not particularly invested in the feature at the moment.

**Comment by SimonCropp** [comment]
thanks. i will close this for now
