### ISSUE TITLE
ShouldAllBe message generator

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#150]
Currently error message is `new[]{1,2,3} should all be an element satisfying the condition ((x + 4) < 7) but does not`

It should be `new[]{1,2,3,4} should satisfying the condition ((x + 4) < 7) but [3] does not` or `new[]{1,2,3} should satisfying the condition ((x + 4) < 7) but [3,4] does not`

**Comment by cottsak** [comment]
`new[]{1,2,3,4} should satisfying` or `new[]{1,2,3,4} should satisfy`?

**Comment by JakeGinnivan** [comment]
`satisfy` is better

**Comment by cottsak** [comment]
@JakeGinnivan I'll try and jump in on this one (GitHub membership is all mine!!)

**Comment by cottsak** [comment]
Fixed in https://github.com/shouldly/shouldly/pull/181

**Comment by JakeGinnivan** [comment]
Will be released in next (>2.4.0) release
