### ISSUE TITLE
Add InstantHandleAttribute to Should.Throw 

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#153]
Which can remove warnings like `Access to disposed closure`

InstantHandleAttribute is a ReSharper code annotation

**Comment by JoeMighty** [comment]
How would you like to deal with `JetBrains.Annotations` package dependency? Are you happy for me to add the latest `JetBrains.Annotations` NuGet package to the solution?

**Comment by JakeGinnivan** [comment]
I think it can be added as a source file and be marked internal. @citizenmatt - suggestions?

**Comment by citizenmatt** [comment]
Yep. Here are the recommended ways:

1. **Add a reference to the `JetBrains.Annotations` package**

    The attributes in the package are marked with the `[Conditional]` attribute, which by default means they don't get compiled into the resulting assembly, but are still used for analysis of the source code of the current project.

    Defining `JETBRAINS_ANNOTATIONS` means they get compiled into the resulting assembly, so third parties can use your annotations. HOWEVER, you now have a binary dependency on JetBrains.Annotations.dll, and you're forcing that on your third party.

    Generally, this approach is most useful when you're building an application, rather than a framework, and you can happily take the dependency, or rely on the `[Conditional]` attribute not to compile anything in.

2. **Add the annotations as source**

    Adding as source allows you to compile the annotations into your assembly without introducing a dependency. This is great for frameworks.

    However, adding them as public symbols means that anyone who references your source will also see them, and can lead to clashes if more than one person has attributes defined in the `JetBrains.Annotations` namespace. Making the attributes internal is the way to go here. 9.1 has updated the annotations options page to allow copying to clipboard as public or internal.

    This approach, with symbols set to internal, is the recommended approach for frameworks.

(There is a third approach - using external annotations file. This avoids any confusion about what's compiled where and who has dependencies, but they're a PITA to write…)

**Comment by JoeMighty** [comment]
Thanks @citizenmatt. It sounds like number 2 is the best way to go then.

**Comment by JoeMighty** [comment]
I've created a pull request for this (#218).

**Comment by JakeGinnivan** [comment]
@JoeMighty there are now a heap more overloads. So the work for this needs to be done again, at least the nuget package change is done

**Comment by JoeMighty** [comment]
No worries, I'll take a look at these then. Are these the Should.Throw(Task) overloads you're referring to?

**Comment by JakeGinnivan** [comment]
Yep, and the custom message overloads

**Comment by JoeMighty** [comment]
Alright, sounds good. I'll get on it!

**Comment by JoeMighty** [comment]
The Should.Throw methods are sorted (#226). Are you happy for me to sort the `NotThrow` methods under this issue or do you want to create a new one?

**Comment by JakeGinnivan** [comment]
Just do it in the same PR

**Comment by JoeMighty** [comment]
There we go, that's `Throw` and `NotThrow` sorted. I used your rebase -i instruction and it worked like a charm!

**Comment by yannisgu** [comment]
Fixed in #226 and #218?

**Comment by JakeGinnivan** [comment]
So it is
