### ISSUE TITLE
Multiple Assertions

### ISSUE THREAD

**Issue by circa1741** [shouldly/shouldly#160]
It would be nice to have something like:

http://blog.drorhelper.com/2011/02/multiple-asserts-done-right.html

**Comment by dotnetchris** [comment]
Updated url: http://docs.shouldly-lib.net/docs/shouldsatisfyallconditions

**Comment by Jawvig** [comment]
Updated updated url: https://docs.shouldly.io/documentation/satisfyallconditions

**Comment by JosephWoodward** [comment]
@Jawvig Thanks for posting the link for anyone else who stumbles across this.

**Comment by GusGusGusGus** [comment]
I ran into a similar problem... I have a call to a service Task that returns a list, with a method signature like so:
async Task<List<bool>> UpdateRecords(parameters);
This task can cause an Exception, which would be duelly caught in a try-catch.
In my test, I want to assert both for a lack of Exceptions, but also to receive that returned list and/or assert on it's value, something like so:
await Should.NotThrowAsync.And.BeOfType<List<bool>>.And.NotBeEmpty(_myService.Update(parameters));
either that or at least:
var myReturnedList = await Should.NotThrowAsync(_myService.Update(parameters));
which is not possible.
Any thoughts? Thanks in advance

**Comment by gregmac** [comment]
Updated updated updated url: https://docs.shouldly.org/documentation/satisfyallconditions
