### ISSUE TITLE
Ignore case = true breaks comparison for yield break/yield return methods

### ISSUE THREAD

**Issue by vorou** [shouldly/shouldly#164]
`ShouldBe` on a IEnumerable method returning iterator (i.e., either yield breaking or yield returning) returns false positive if ignore case sets to true. Changing any of these constraints results in proper behavior of `ShouldBe` (if method returns collection, OR if ignore case is false, should be is blowing up as expected).

I've hacked up [some test cases](https://github.com/vorou/shouldly/commit/f0748edbe81ff760afacbfc88ce059d8281fd3d8), but haven't checked the actual code yet, since I'm not sure is it a bug.

**Comment by JakeGinnivan** [comment]
Yeah it is a bug.. really silly one too, nothing to do with yield/iterators either. Thanks for the tests, made it easy to reproduce/fix.
