### ISSUE TITLE
Allow additional context to be passed to Shouldly

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#169]
There are times when additional context would be useful. As an example https://gist.github.com/raybooysen/5cf4c9b74a7d35d9ba0b

This is *not* a custom error message like many other frameworks. I am thinking:

`type.IsSealed.ShouldBe(false, "type is " + type.FullName);`

Error message would be
```
type.IsSealed should be false but was true

Additional info:
type is MyNamespace.MyType
```

**Comment by JoeMighty** [comment]
Are you thinking this should be added to all of the Should/ShouldBe/ShouldNotBe methods?

**Comment by JakeGinnivan** [comment]
Most likely. I think we can assume that any type of assertion could always want additional context to improve the message.

Also they need to be overloads, not optional parameters otherwise we break semantic versioning

**Comment by JoeMighty** [comment]
Yes, I thought as much. I'll give this one a shot and see how I go!

**Comment by JakeGinnivan** [comment]
Have any luck @JoeMighty?

**Comment by JoeMighty** [comment]
Sorry for the late reply, I missed that you commented. I think I've bitten off more than I can chew with this one I'm afraid!

**Comment by JakeGinnivan** [comment]
No worries, feel free to pick something smaller up.
