### ISSUE TITLE
Graceful fall-back when source/pdbs are not available

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#170]
See https://github.com/shouldly/shouldly/issues/105 for info on the issue.

We need to not crash and try our best to display a decent error message.

**Comment by yannisgu** [comment]
Fixed in #173 or is there a way to "better" fallback?

**Comment by JakeGinnivan** [comment]
I am actually unsure.. Need to test and make sure it is fixed

**Comment by JakeGinnivan** [comment]
I think it is all fixed though

**Comment by JakeGinnivan** [comment]
This is completely done, #335 updates all tests to verify message when source is available, and when source is not available. PCL cannot get at the source code, so it required this
