### ISSUE TITLE
Add `Should.ThrowAsync` method

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#172]
Current `Should.Throw` is blocking. We should add a `Should.ThrowAsync` which returns a task and requires awaiting.

**Comment by PureKrome** [comment]
I'm on it!

**Comment by PureKrome** [comment]
Oh snap - this is targetting `.NET 4.0` right? oh urgh. Can i bump it to `.NET 4.5`  to use `async/await` ?

**Comment by JakeGinnivan** [comment]
You will have to write it using TPL.

Something like this:

``` csharp
public static Task<TException> ThrowAsync<TException>(Func<Task> actual)
    where TException : Exception
{
     return actual().ContinueWith(t => {
         if (t.IsFaulted)
            throw new ChuckedAWobbly(new ShouldlyMessage(t.Exception.GetType()).ToString());
         // Etc to check type of exception and such
    });
```

**Comment by PureKrome** [comment]
Ah ok - TPL. Um ... i've not used any of that so I'll pull myself off this task now and let someone will TPL skills jump on, instead :blush:

**Comment by txdv** [comment]
Sigh ... It is not rocket science.

**Comment by YogirajA** [comment]
@JakeGinnivan  I am taking a stab at this one. I need some pointers on testing it. What could be a sample passing and failing test here?

**Comment by JakeGinnivan** [comment]
Have a look at https://github.com/shouldly/shouldly/blob/master/src/Shouldly.Tests/ShouldThrow/FuncOfTaskScenario.cs

The difference will be that it will be asynchronous, so you will need to do soemthing like this:

```
Should.ThrowAsync(...).TimeoutAfter(Timespan.FromSeconds(1)).Wait();
```

**Comment by YogirajA** [comment]
@JakeGinnivan  What do you think of [this?](https://github.com/YogirajA/shouldly/blob/development/src/Shouldly/ShouldThrowTaskExtensions.cs) It is work in progress. Am I going in the right direction?
I ran into some trouble with the [ShouldThrowAWobbly test]
(https://github.com/YogirajA/shouldly/blob/development/src/Shouldly.Tests/ShouldThrowAsync/FuncOfTaskScenarioAsync.cs). The other one succeeds. I also created a little test scenario below that. That works fine too.  I feel like I may have to also modify the ShouldlyShouldFailureTestScenario class methods along with the default throw. What do you think?

**Comment by JakeGinnivan** [comment]
If it doesn't make sense to use the base fixture, don't. Just write a test normally, the base class is there to save time and give some structure by default.

But likely you need to wrap https://github.com/YogirajA/shouldly/blob/development/src/Shouldly.Tests/ShouldThrowAsync/FuncOfTaskScenarioAsync.cs#L15 with a try/catch. Catch the `AggregateException` then rethrow the InnerException which should be ShouldlyAssertException

**Comment by JakeGinnivan** [comment]
Submit a work in progress pull request if you want, then we can comment on the code easily

**Comment by YogirajA** [comment]
@JakeGinnivan Thanks! Please let me know if you see any issues with the code in the pull request.

**Comment by JakeGinnivan** [comment]
I ended up commenting this out as I was getting exceptions when shouldly was trying to check out the stack frame to get the code. 

This needs to be looked at again. I did extend the tests so it might have just hit a edge case. At any rate this will not be in the next release until I (or someone else) can look into it more

**Comment by YogirajA** [comment]
@JakeGinnivan Can you give me steps to recreate it? I will take a look.

**Comment by JakeGinnivan** [comment]
No worries! Thanks for looking into it. I wanted to get the release out so I just commented it to get past the issue.

**Comment by YogirajA** [comment]
I did some digging today. I compared the stacktrace of the master code with the working one from one my local branches. They looked almost identical. They both have the same frame null. In the working code however, the while loop does not go this far. This call  `IsShouldlyMethod(currentFrame.GetMethod())` returns true when  the value of i is 2. In the master code, that method doesn't return true for any of the frames and one of them being null, it throws the null reference. I will keep digging more. If this rings any bells , it will be helpful.

**Comment by JakeGinnivan** [comment]
Interesting. Your local branch would not have as many overloads and also I ended up changing the code around ShouldCompleteIn to give it better exceptions. All of these things could have changed the stacktrace slightly. I was short on time to investigate, not sure when I will get a chance. Am in Prague this weekend
