### ISSUE TITLE
Improve ShouldContain error message

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#174]
Working on carnac and I got this:

```
Shouldly.ChuckedAWobbly occurred
  HResult=-2146233088
  Message=
    keysCollection
        should contain
    Carnac.Logic.Models.Message
        but was
    [] (System.Collections.ObjectModel.ObservableCollection`1[Carnac.Logic.Models.Message])
  Source=Shouldly
  StackTrace:
       at Shouldly.ShouldBeEnumerableTestExtensions.ShouldContain[T](IEnumerable`1 actual, T expected) in c:\TeamCity\buildAgent\work\45364f332cb20c9\src\Shouldly\ShouldBeEnumerableTestExtensions.cs:line 17
  InnerException: 
```

`but did not` would be sufficient I think? We don't care what else is in the collection, right?

**Comment by urig** [comment]
Hi @JakeGinnivan. I'd like to jump-in :). 
Couple of questions if you will:
1. Your specification is to just print "but did not" instead of printing the collection?
2. Is there an existing test scenario for this? (I can't seem to find it)
