### ISSUE TITLE
[Feedback wanted] New Docs Site

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#175]
http://docs.shouldly-lib.net

Thoughts @robdmoore @chaitanyagurrapu ?

Thinking of redirecting current github page to that and cutting the readme right back to include contribution info and such.

**Comment by JakeGinnivan** [comment]
Will also redirect shouldly-lib.net to docs.shouldly-lib.net

As for domains, it was that or shouldly.io and I thought shouldly-lib.net was better

**Comment by JakeGinnivan** [comment]
But thoughts welcome

**Comment by robdmoore** [comment]
It's *beautiful*! wow.

**Comment by chaitanyagurrapu** [comment]
Very nice. I like it. Perhaps the contrast between the right most pane (failure messages) and the middle one can be less? Maybe very light gray or light blue?

I've never used readme.io. Can I use my github login or do I need to sign up to it separately to suggest edits?

**Comment by xerxesb** [comment]
kudos!

Looks great!
