### ISSUE TITLE
Improve examples on docs site

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#177]
The simpsons examples should override ToString so they give better error messages

**Comment by robertlyson** [comment]
I edited through http://docs.shouldly-lib.net/v2.4.0/docs failure messages for following tests: `IEnumerable_ShouldBe`, `ShouldBeOneOf`, `ShouldNotBeOneOf`, `ShouldBeAssignableTo`, `IEnumerable_ShouldContain`, `IEnumerable_ShouldNotContain`, `IEnumerable_ShouldBeEmpty`, `IEnumerable_ShouldBeOneOf` and `IEnumerable_ShouldBeSubsetOf`.

Hope it helps.

**Comment by JakeGinnivan** [comment]
Awesome! Great work.

The only one that looked a bit strange was https://dash.readme.io/project/shouldly/v2.4.0/docs/shouldbeoneof-1 - but that was not your doing.. I will have to look into that

**Comment by JakeGinnivan** [comment]
Replaced by #308
