### ISSUE TITLE
Client-friendly exception names

### ISSUE THREAD

**Issue by jbogard** [shouldly/shouldly#179]
On a couple of clients now we've had to explain what a Wobbly is and how it getting Chucked is not reason for alarm. That it's actually an assertion failure.

Any thoughts of making the ChuckedAWobblyException a little more explicit in what it is and not a funny name?

**Comment by ChrisMissal** [comment]
:+1:

**Comment by chaitanyagurrapu** [comment]
+1. I've heard a similar comment at my current place as well. The naysayers find the "Chucked A Wobbly" to be very unprofessional and annoying.

**Comment by JakeGinnivan** [comment]
Not against this. I would suggest that we create a new exception which inherits from ChuckedAWobblyException so we do not break anyone catching that exception.

What should we call the exception?

**Comment by plioi** [comment]
Let's go Full Boring: AssertionException.

**Comment by jbogard** [comment]
- XUnit - assertion-specific exception `throw new FalseException()`
- NUnit has one `AssertionException`
- MSTest has `AssertFailedException`
- mspec has `SpecificationException`

My vote is something with Assert in it or `ಠ_ಠException`

**Comment by JakeGinnivan** [comment]
`ShouldAssertException` maybe.
