### ISSUE TITLE
Make Should-methods chainable

### ISSUE THREAD

**Issue by asgerhallas** [shouldly/shouldly#180]
Would it be an idea to make the rest of the should-methods chainable like ShouldBeTypeOf?

I use ShouldBeTypeOf and it's chainability, but I often need to assert on more than one property on the  cast subject, like

            commands[0].ShouldBeOfType<AddColumn>()
                .Tablename.ShouldBe(GetTableFor<Entity>().Name);
                .Column.ShouldBe("Something");

That would be quite nice :)

**Comment by JakeGinnivan** [comment]
The problem with this is how shouldly grabs the code. The best would be if we could remove the `.Should*` methods out completely so say the column is wrong the error would be:

`((AddColumn)commands[0]).Tablename.GetTableFor<Entity>().Name.Column` because that is what you are asserting.

I don't have an issue with doing this, but it will require a bit of testing to make sure the error messages are created nicely

**Comment by chaitanyagurrapu** [comment]
What if there was an other keyword introduced to help with this. 'AndAlso' for example. So the test could be written as 

       commands[0].ShouldBeOfType<AddColumn>()
            AndAlso.Tablename.ShouldBe(GetTableFor<Entity>().Name);
            AndAlso.Column.ShouldBe("Something");

This way, when printing the error message shouldly can search for text between the `should*` method and `AndAlso`

**Comment by jamesmiles** [comment]
At what point would assertion failures be thrown in this model?

**Comment by JakeGinnivan** [comment]
Thinking about this, it is something I don't think we need. I think being explicit is better. 

This works right now and is not much extra code and is pretty understandable
```
var commandColumn = commands[0].ShouldBeOfType<AddColumn>();
commandColumn.Tablename.ShouldBe(GetTableFor<Entity>().Name);
commandColumn.Column.ShouldBe("Something");
```

We also have `ShouldSatisfyAllConditions()` for having multiple asserts against a single object. 

```
commands[0]
    .ShouldBeOfType<AddColumn>()
    .ShouldSatisfyAllConditions(c => {
        c.Tablename.ShouldBe(GetTableFor<Entity>().Name);
        c.Column.ShouldBe("Something");
    });
```

**Comment by asgerhallas** [comment]
I think you're right. And thanks for pointing me towards ShouldSatisfyAllConditions(), I hadn't seen that.

**Comment by JakeGinnivan** [comment]
It was only added recently, maybe after this issue was actually created. Alternate way to solve the same issue :)

**Comment by asgerhallas** [comment]
And a much cleaner way than my original suggestion :)
