### ISSUE TITLE
NuGet Readme should be simplified like the github readme

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#183]
I just upgraded shouldly and the readme that pops up is out of date and should be simplified and brought into line with the Readme.md in this repo

**Comment by mountain65** [comment]
I would love to do this, but have no idea where to find the files. They are not in this repo, as far as I can see.

**Comment by JakeGinnivan** [comment]
Just had a look at this. We actually just need to deploy, the readme updates were done after the last deploy to github.. See: http://teamcity.ginnivan.net/repository/download/OpenSourceProjects_Shouldly_CI/10672:id/Shouldly.2.4.1.nupkg%21/README.txt

My bad!
