### ISSUE TITLE
Add InstantHandleAttribute to ShouldContain

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#184]
R# hint to not warn about modified closure as the lambda is executed immediately not delayed

**Comment by JakeGinnivan** [comment]
@JoeMighty hold off on this until #195 is merged, otherwise we have to do it again after

**Comment by JoeMighty** [comment]
Alright, will do.

**Comment by JakeGinnivan** [comment]
Ok this is good to go.

**Comment by JoeMighty** [comment]
Good good! I'll get sort this then.

**Comment by JoeMighty** [comment]
The Should.Throw methods are sorted (#226). Are you happy for me to sort the NotThrow methods under this issue or do you want to create a new one?

**Comment by JoeMighty** [comment]
Just submitted PR #228 to fix this issue.

**Comment by JoeMighty** [comment]
At one point we briefly talked about adding the InstantHandleAttribute to the custom message parameters; are you still keen to do this?

**Comment by JakeGinnivan** [comment]
Yep, see no reason not to

Sent from my Windows Phone
________________________________

**Comment by JoeMighty** [comment]
A pull request (#238) has now been created for this.
