### ISSUE TITLE
Add extension methods on System.Action for ShouldThrow etc

### ISSUE THREAD

**Issue by kpstolk** [shouldly/shouldly#213]
It is easier in my opinion to have an extension on System.Action like this:

    Action action = () => { throw new NotImplementedException(); };
    action.Throws<NotImplementedException>();

instead of:

    Action action = () => { throw new NotImplementedException(); };
    Should.Throws<NotImplementedException>(action);

**Comment by JakeGinnivan** [comment]
I think having these extension methods make sense. They should just proxy to the existing static methods.

All the Should.Throw tests should be moved over to use the new extension methods so all code paths are still tested

Happy to have a pull request for this

**Comment by JakeGinnivan** [comment]
I think this is even more useful for the task overloads.

`await task.ShouldThrowAsync<InvalidOperationException>()`

**Comment by JoeMighty** [comment]
kpstolks initial suggestion is to make the method `action.Throws<T>`, however I feel `action.ShouldThrow<T>` makes more sense as all other Shoudly methods start with the Should prefix. 

What are your thoughts?

**Comment by JoeMighty** [comment]
Also, is there any need to pass the action in as an argument as well? Presumably we can just do:

`action.ShouldThrow<T>()` instead of `action.ShouldThrow<T>(action)`?

**Comment by kpstolk** [comment]
No, my bad. I've updated the sample code.

**Comment by JoeMighty** [comment]
Thanks for the clarification. That makes more sense :)

**Comment by JakeGinnivan** [comment]
This will also have to be in addition to old API. This isn't worth a breaking change

**Comment by JoeMighty** [comment]
I've been working on this one ([see comparison here](https://github.com/shouldly/shouldly/compare/master...JoeMighty:ShouldThrowExtensions)) and added the necessary extension methods and updated the tests accordingly; however I'm struggling updating the tests for the timeout scenarios `FuncOfTaskWithTimeoutScenario.cs` and `TaskWithTimeoutScenario.cs` that take an additional delegate as an argument.

Do you have any suggestions on how I can proceed with this, they seem quite specific tests that won't work with these updates?

**Comment by JakeGinnivan** [comment]
Should be fine, the overload should be

`ShouldThrow<T>(this Task<T> task, Timeout timeout);`

Is that what you mean?

**Comment by JoeMighty** [comment]
Yes, I realised I'd missed the Timeout overload methods :S I was also having difficulty in converting the tests that pass the task to a `Should.Throw(Action)` but figured it out in the end. Thanks.

Are you happy for me to add the NotThrow extensions under this issue?

**Comment by JakeGinnivan** [comment]
Yep :)

**Comment by JoeMighty** [comment]
Hoping to have this one finished in the next few days!

**Comment by JoeMighty** [comment]
A PR (249) has now been created for this.

**Comment by yannisgu** [comment]
This can be closed, or not?

**Comment by JakeGinnivan** [comment]
Yep!

**Comment by grokky1** [comment]
Not sure how to use this...

In NUnit I'd do this:
````csharp
AsyncTestDelegate action = async () => await foo();    // foo returns a Task or Task<T>
Assert.ThrowsAsync<FooException>(action);
````

or even simpler:
````csharp
AsyncTestDelegate action = () => foo();    
Assert.ThrowsAsync<FooException>(action);
````

In shouldly I suppose I should do this:
````csharp
action.ShouldThrowAsync<FooException>();
````

However, both `ShouldThrowAsync` and `ShouldThrow` seem to work for me. In NUnit, that won't compile.

Is it safe to use either way? I'm afraid I'll accidentally use the wrong assertion method and get a true negative, whereas the test should fail. In NUnit I can't make that mistake.
