### ISSUE TITLE
Should.Throw(Task) Overloads

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#216]
At the moment there is just the signature `Should.Throw(Func<Task>)`. There should be `Should.Throw(Task)`

**Comment by JoeMighty** [comment]
I've created a pull request for this (#219).

What about the other methods (such as `NotThrow`, `ThrowAsync` etc)? Let me know and I'll update my PR.

**Comment by JakeGinnivan** [comment]
I'm on this one

**Comment by JakeGinnivan** [comment]
Fixed in #195
