### ISSUE TITLE
Should.NotThrowAsync(Task) and Should.NotThrowAsync(Func<Task>)

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#217]
We have Should.ThrowAsync but not the opposite

**Comment by JakeGinnivan** [comment]
Wait until #195 is merged

**Comment by YogirajA** [comment]
@JakeGinnivan  I understand this is blocked. I can start looking into this.  Do you think #195 will have a ton of impact on this item? If yes, I will wait.

**Comment by YogirajA** [comment]
On this

**Comment by JakeGinnivan** [comment]
:+1:

**Comment by YogirajA** [comment]
@JakeGinnivan 

One option is to have methods like below:

       public static Task NotThrowAsync([InstantHandle] Func<Task> action
           , TimeSpan timeoutAfter,
            Func<string> customMessage)
        {
            try
            {
                return action().TimeoutAfter(timeoutAfter);
            }
            catch (TimeoutException)
            {
                throw;
            }
            catch (Exception ex)
            {
                throw new ShouldAssertException
                  (new ExpectedShouldlyMessage(ex.GetType(), customMessage).ToString());
            }
            
        }

        public static Task NotThrowAsync<T>([InstantHandle] Task task
           , TimeSpan timeoutAfter,
            Func<string> customMessage)
        {
            return task.TimeoutAfter(timeoutAfter);
        }

The other option could be to have an Async version of CompleteIn (may be a part of separate refactor item). Which one you think makes more sense? Also, how many overloads are you expecting?

**Comment by hossambarakat** [comment]
I started working on this issue and raised PR #430 with my changes. approciate your feedback @JakeGinnivan , @YogirajA

**Comment by ArnaudB88** [comment]
What is the current state of this functionality? The PR is created for more than 2 years now...

**Comment by hossambarakat** [comment]
@ArnaudB88 Thanks for reminding me about this PR. I have just updated it with the latest master branch so it should be ready for merge.

**Comment by SimonCropp** [comment]
given https://github.com/shouldly/shouldly/pull/430 is merged, i will close this
