### ISSUE TITLE
Should.NotThrow message generator

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#220]
```
Shouldly.ShouldAssertException : 
    Should
        error 
    Shouldly.ShouldAssertException
        but does not
```

Is not great. Something like this would be better:

```
Shouldly.ShouldAssertException : 
   {code argument}
       should not throw but threw
   {exception type}
       with message
   {exception message}
```

**Comment by JoeMighty** [comment]
I've made a start on this one.

**Comment by JakeGinnivan** [comment]
It is not the simplest change. We don't have any code to extract arguments from a static shouldly message. Good luck :)

**Comment by JoeMighty** [comment]
Yeah, I quickly realised that! The rest of it is done; extracting the arguments is all that's left. Am I correct in thinking that by arguments you mean the contents of the delegate? ie: `Should.NotThrow(() => { MyMethod(); });` (in this case the `MyMethod` should be output at the beginning of the shouldly message?

**Comment by JoeMighty** [comment]
Here's the branch in its current state https://github.com/JoeMighty/shouldly/tree/ShouldNotThrowMessageGenerator

**Comment by JakeGinnivan** [comment]
I think it should be the entire lambda `() => MyMethod()`. I'm not sure if we have overloads, if we do we just want the first argument.
Will check this out tomorrow when back in London

Sent from my Windows Phone
________________________________

**Comment by JoeMighty** [comment]
Cool, sounds good. I'm pretty certain you can get that info by wrapping the delegate in an `Expression<>`.

**Comment by JakeGinnivan** [comment]
Yeah, but that is a breaking change. Maybe overloads?

Sent from my Windows Phone
________________________________

**Comment by JoeMighty** [comment]
I wondered whether we can wrap the delegate within an expression within the message generator. I've not tried it before so I don't know if it can be done - but that way wouldn't introduce a breaking change and wouldn't add additional overloads?

**Comment by JakeGinnivan** [comment]
Once you have an action/func delegate you cannot break it back down into an expression tree unfortunately.

I think overloads are probably the best solution.. More overloads.. :( 

Even if we were to introduce a breaking change, expressions do not allow block scoped expressions, meaning this would no longer compile:

```
Should.Throw(() => {
    // Some block level code because we are wrapped in { }
});
```

**Comment by JakeGinnivan** [comment]
So basically overloads or trying to get the source code out

**Comment by JoeMighty** [comment]
I see, I didn't know that. I'm relatively new to C# so this at the edge of my knowledge.

>Even if we were to introduce a breaking change, expressions do not allow block scoped expressions, meaning this would no longer compile:

If this is the case then it sounds like expressions won't suffice; can you point me in the direction of other options that might work?

As I said above - this is the edge of my knowledge but I'm keen to crack this issue and learn in the process.

**Comment by JakeGinnivan** [comment]
Will get back to you in the morning:)

Sent from my Windows Phone
________________________________

**Comment by JoeMighty** [comment]
Thanks a lot, that would be appreciated :)

**Comment by JakeGinnivan** [comment]
Ok, so bit of a brain dump. Expressions in .NET do allow blocks if you build them using the expressions API, but only lambdas can be turned into expression trees, not blocks.

To give you a bit more of an idea of what the Expression type does:

```
Should.Throw(Expression<Action> action)
Should.Throw(() => a == b) // Expression.Equal(Expression.Value(a), Expression.Value(b))
// Or in tree form
//       ==
//   a        b
```
Expressions cannot be executed, but you can call `.Compile()` which will turn that into a delegate which can be invoked, ie `Expression<Action>.Compile() -> Action`

Once you have a delegate, it cannot be decomposed back into an expression tree. Which is where we are now. So we have two options

1) Add expression overloads
I think the compiler will favour the Expression overload first, so if you do not have a block scoped lambda then it will use the expression tree. But if you have `{ }` around statements then it will fall back to the delegate overload. We need to check this, the compiler may just say it's ambigious which means this approach will not work.

2) Read source code
This is not super easy as we need to handle:

```
Should.Throw(() => methodCall());
Should.Throw(() => { methodCall(); });
Should.Throw(() => {
    if (methodCall1()) {
        methodCall2();
    }
});
Should.Throw(() => methodCall(), "AdditionalInfo");
Should.Throw(() => methodCall(), () => "AdditionalInfo");
Should.Throw(() => { methodCall(); }, "AdditionalInflo");
Should.Throw(() => { methodCall(); }, () => { "AdditionalInflo" });
Should.Throw(() => {
    if (methodCall1()) {
        methodCall2();
    }
}, () => "Additional info");
```

So we need to just pull out the initial lambda of the `Throw` method, and just the first argument. It can be block scoped, and have nested blocks and the code which pulls out the code needs to handle all that.

So yeah, fun task :)

**Comment by JakeGinnivan** [comment]
I think 2) is the way to go

**Comment by yannisgu** [comment]
@JakeGinnivan how do you thought to read the source code? With CallerFilePathAttribute  and CallerLineNumberAttribute and then read the file with System.IO? Or is there any better way to get the source code which called a method?

**Comment by JakeGinnivan** [comment]
We get the source information from the stackframes. Basically we walk until we find a stackframe which type does not have the [ShouldlyMethod] attribute. The code to read the source is all in place, it is just pulling it apart to get the correct bits of source out of the lambdas
