### ISSUE TITLE
ShouldContainWithoutWhitespace message generator

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#221]
Current:

```
Shouldly.ShouldAssertException : 
    ex.Message
        should contain without whitespace
    "Should not throw System.RankException but does
Additional Info:
Some additional context"
        but does not
```

It should have the actual message as well to make diagnosing the issue easier

**Comment by urig** [comment]
How do I reproduce this?

**Comment by urig** [comment]
Would it be acceptable to go:

    throw new ShouldAssertException(new ExpectedShouldlyMessage(ex, customMessage).ToString());

Instead of:

    throw new ShouldAssertException(new ExpectedShouldlyMessage(ex.GetType(), customMessage).ToString());

Here: https://github.com/shouldly/shouldly/blob/master/src/Shouldly/ShouldStaticClasses/ShouldThrowTaskExtensions.cs#L173 ? (and on line 169 naturally)

**Comment by JakeGinnivan** [comment]
I explained it badly, it is not the Should.Throw methods, it is the `ShouldContainWithoutWhitespace` method. We use that method to verify others, I was writing tests for the Should.Throw method.

```
Shouldly.ShouldAssertException : 
    ex.Message
        should contain without whitespace
    "<expected>"
        but does not
```

Maybe something like:

```
Shouldly.ShouldAssertException : 
    ex.Message
        should contain without whitespace
    "<expected>"
        but
    "<actual>"
        does not
```

**Comment by urig** [comment]
I'm afraid I still don't quite get what you're specifying here. Can we have a quick chat about it [here](https://gitter.im/urig/shouldly) sometime?
