### ISSUE TITLE
Possible new logo?

### ISSUE THREAD

**Issue by JosephWoodward** [shouldly/shouldly#236]
I'm looking at the existing logo and wondering if you're open to ideas on a new one? I'm a dab handy in Photoshop and am happy to put a few ideas together if you're open to them?

**Comment by PureKrome** [comment]
DO
IT
! :+1:

**Comment by JakeGinnivan** [comment]
Sure, why not.

**Comment by JosephWoodward** [comment]
Reviving this idea from the dead, here's one proposed version, with the O being used for the NuGet package icon.

![shouldly4](https://user-images.githubusercontent.com/1237341/28922204-147fcd82-7851-11e7-8cbd-6bd20c1a793e.png)

**Comment by JosephWoodward** [comment]
Closing this in favour of more recent call for logo ideas.
