### ISSUE TITLE
ShouldBeSameAs (Reference equality)

### ISSUE THREAD

**Issue by xerxesb** [shouldly/shouldly#24]
https://twitter.com/#!/davetchepak/statuses/73686872353812481

.ShouldBeSameAs() for reference equality (Object.ReferenceEquals(a, b))

Also with equivalent ShouldNotBeSameAs

**Comment by dotnetchris** [comment]
I know this is an old thread but just incase anyone else ever ends up here. If you look at the code for `Same` via resharper/reflector it shows `return actual == expected;` but you can see in the source it very **explicitly** uses `ReferenceEquals` as seen https://github.com/shouldly/shouldly/blob/master/src/Shouldly/Internals/Is.cs#L27

**Comment by Rookian** [comment]
This is a bug imo. 

How can I check for reference equality if I overrided the == operator?

**Comment by dotnetchris** [comment]
@Rookian see my comment above yours, the source specifically uses reference equals. The bug was resolved in 2011

**Comment by Rookian** [comment]
@dotnetchris  That's weird. When I decompile Shouldly (3.0.0-beta0003) with Resharper in VS2017 I see the following:

```
    public static void ShouldBeSameAs(this object actual, object expected, [InstantHandle] Func<string> customMessage)
    {
      actual.AssertAwesomely<object>((Func<object, bool>) (v => Is.Same(v, expected)), actual, expected, customMessage, nameof (ShouldBeSameAs));
    }

```

Which points to:
```
    public static bool Same(object actual, object expected)
    {
      if (actual == null && expected == null)
        return true;
      if (actual == null || expected == null)
        return false;
      return actual == expected; // --> Bug?
    }
```

**Comment by dotnetchris** [comment]
Alex,


Look at the source for Same https://github.com/shouldly/shouldly/blob/master/src/Shouldly/Internals/Is.cs#L27


The resharper decompliation doesn't return the precise code in this situtation 


Chris



-----Original Message-----
