### ISSUE TITLE
Add ShouldBe Case insensitive Enumerable<string> comparision

### ISSUE THREAD

**Issue by mcbelton** [shouldly/shouldly#244]

**Comment by brendanconnolly** [comment]
I'm looking to jump-in, just to clarify is this that an enumerable contains a string ex. enumerable.ShouldContainIgnoringCase("expected")

or is it comparing two enumerables?  ex. enumerable.ShouldContainIgnoringCase({"yes","no","maybe"}) 

or a different case. Either way I'm happy to implement

**Comment by mcbelton** [comment]
Incase of string collection can we have Case enum as argument for ShouldBe method. Default can be Case.Sensitive.

**Comment by JakeGinnivan** [comment]
Yeah, so we need to add:

```
static void ShouldBe(this IEnumerable<string> actual, IEnumerable<string> expected, Case caseSensitivity);
static void ShouldBe(this IEnumerable<string> actual, IEnumerable<string> expected, Case caseSensitivity, string customMessage);
static void ShouldBe(this IEnumerable<string> actual, IEnumerable<string> expected, Case caseSensitivity, [InstantHandle] Func<string> customMessage);
```

**Comment by JakeGinnivan** [comment]
The defaulted case is already taken care of with current `ShouldBe` implementation

**Comment by mcbelton** [comment]
yes that's right. However, if can enable this part of ShouldBe would be nice rather than having separate method with different name.

**Comment by JakeGinnivan** [comment]
Yep, they are just additional overloads

**Comment by JulienFiaffe** [comment]
I don't know if this issue is still relevant since it has not been updated for a while.
Yet I forked the project and I made an implementation for it.
I can submit a PR if needed for a review.

**Comment by JoeMighty** [comment]
This feature has now been added; thanks @JulienFiaffe for the PR and to @mcbelton for the enhancement suggestion.
