### ISSUE TITLE
Idea: ShouldBeLike

### ISSUE THREAD

**Issue by jamesmiles** [shouldly/shouldly#245]
Have you considered support for dynamic "matching" using anonymous types?

// Given a customer named Homer
var customer = new Customer{ Name = "Homer", Age = 42};

// Their should be a name field with "Homer" in it.
customer.ShouldBeLike(new { Name = "Homer" });

This would be particularly useful in asserting all objects in a list (not necessarily sharing a common type of interface) meet some criteria. EG.

// Given some scenario resulting in a sequence of business events
var events = //...

// Assert
events.ShouldBeLike(new[] 
{ 
   new{Id = 1, EventType = "CustomerCreated", Name = "Homer"},
   new{Id = 1, EventType = "MobileNumberChanged", PhoneNumber="0412 333 111"},
   new{Id = 1, EventType = "SMSVerificationCodeSent", PhoneNumber="0412 333 111", VerificationCode="4421"},
}

**Comment by JakeGinnivan** [comment]
That would be awesome. Fluent assertions has had this feature for ages

http://www.continuousimprover.com/2012/09/asserting-object-graph-equivalence.html

Could get some inspiration of the API and implementation from there

**Comment by jamesmiles** [comment]
ExpectedObjects does a similar thing, however I'd prefer to see this in Shouldly as the messages are way better.

https://github.com/derekgreer/expectedObjects

**Comment by JakeGinnivan** [comment]
As for API and behavior. 

1) Do we fail if properties are not defined on expected?
   a) Can it be overridden by options?
2) What other options do we need?
3) Should the enumerable overload take an object or object[] as the expected
  a) If it takes an object we could use a single object to verify all actual, useful for trait checking?
  b) Or we could have another method `ShouldAllBeLike` which compares all items to a single item for the trait checking? That could default to ignoring missing properties?
  a) If we did this property specifications could be cool, similar to NSubstitute? Because we are using anonymous objects we could do `Should.Exist()`. In your events sample you could then do  
`events.ShouldAllBeLike({ Id = Should.Exist(), EventType = Should.Exist() })` - this could be an api explosion though.
4) Do we need ShouldInclude which explicitly opts into just the specified properties?

Initial cut of the api could look like this
```
void ShouldBeLike<T>(this T actual, object expected, Action<ShouldBeLikeOptions<T>> configure = null);
void ShouldBeLike<T>(this IEnumerable<T> actual, object expected, Action<ShouldBeLikeOptions<T>> configure = null);
class ShouldBeLikeOptions<T>
{
   ShouldBeLikeOptions ShouldFailForMissingProperties()
   ShouldBeLikeOptions ShouldIgnoreMissingProperties()
   ShouldBeLikeOptions ShouldExclude(string propertyPath);
   ShouldBeLikeOptions ShouldExclude(Expression<Func<T, object>> property);
}
```

The IEnumerable overload should be able to take an object or an array/enumerable. If it's an array then each item in actual gets compared to the corresponding 

Examples:
```
new Pet { Name = "Snowball" }.ShouldBeLike(new { Name = "Santas Little helper" });
ShouldAssertException
   new Pet { Name = "Snowball" } should be like { Name = Santas little helper } but had the following issues:
     - Name should be "Snowball" but was "Santas little helper"

new Person { Name = "Person" }.ShouldBeLike(new { Name = "Person" });
ShouldAssertException
   new Person { Name = "Homer" } should be like { Name = "Person" } but had the following issues:
     - Salary property was not defined, should be null

new Person { Name = "Person" }.ShouldBeLike(new { Name = "Person" });
ShouldAssertException
   new Person { Name = "Homer", Salary = 1000 } should be like { Name = "Person" } but had the following issues:
     - Salary property was not defined, should be 1000

new Person { Name = "Person" }.ShouldBeLike(
     new { Name = "Person" },
     options => options.ShouldExclude(p => p.Salary));
<no exception>
```

Let me know your thoughts, I have wanted this feature for quite a while but never sat down and thought about it

**Comment by jamesmiles** [comment]
In the case that an anonymous type is provided as the "expected object", I think the default behaviour should be to ignore fields that are not explicitly referred to. There may be a case to optionally override this behaviour, however you could argue that to achieve this, one must provide any non-anonymous object as an argument, at which point all fields are statically known / verified to be there, as well as the classes being type-checked. Note: it may therefor also be possible to mix and match this behaviour like so:

events.ShouldBeLike(new PersonCollection // type-checked by test
{
   new { Name = “Homer” }, // class not type-checked by test & not all fields provided.
   new Person { Name = “Bar”, Age = 10}, // class type-checked by test & all fields provided.
}

I think "ShouldBeLike" operates on any object, and take any object as an arg: public static void ShouldBeLike(this object actual, object expected)

ShouldAllBeLike would be a nice feature; really just encompasses this pattern: xs.All(x => x.ShouldBeLike(...))

Yes, when using anonymous expected object, you should be able to do something like this: actualy.ShouldBeLike(new{ Name = Any<string>(), Age = NotNull<int?>()})

**Comment by jamesmiles** [comment]
Jake,

Let us know if you want us to develop this or if it is something you want to do "on the plane". We're happy either way but we don't want to duplicate effort.

Thanks,
James

**Comment by JakeGinnivan** [comment]
Happy for you to do it.

Sent from my Windows Phone
________________________________

**Comment by chrischu** [comment]
@jamesmiles Do you have any updates on this? Is it currently being worked on?

**Comment by Martaver** [comment]
Check out this Issue https://github.com/shouldly/shouldly/issues/403, I have a prototype library that we use side by side with Shouldly to achieve exactly this. I've proposed merging it's functionality into Shouldly to bundle it all in one neat package - but there's some housekeeping to be done first.

I would love your input on it!

**Comment by chrischu** [comment]
It might be worth considering porting the functionality over from MSpec.Should (see https://github.com/machine/machine.specifications.should/blob/master/Machine.Specifications.Should/ShouldExtensionMethods.cs#L632).

**Comment by JosephWoodward** [comment]
This can be closed.
