### ISSUE TITLE
There seems to be a problem formatting assertion failure messages

### ISSUE THREAD

**Issue by jamesmiles** [shouldly/shouldly#247]
Is it something to do with my testing having multiple .ShouldXX() calls or just a random bug?

        [Fact]
        public void TaskProcessCanBeInitialized()
        {
            s.When(FakeContractScenarios.ALoanContractIsCreated(contractId));

            var scenario = s.Scenario.OfType<SimulatedEvent>().Select(x => x.Event).OfType<FakeContractScenarios.FakeContractCreatedEvent>().Single();
            var command = s.Commands.SingleOrDefault() as CreateTaskCommand;
            var processEvent = s.Events.SingleOrDefault() as WaitingForTaskCreationEvent;
            command.ShouldNotBe(null);
            command.AggregateId.ShouldBe(scenario.TaskItem.Id);
            command.TaskItem.ShouldNotBe(null);
            processEvent.ShouldNotBe(null);
            processEvent.Command.ShouldNotBeNullOrEmpty();
            processEvent.TaskId.ShouldBe(scenario.TaskItem.Id);
            processEvent.Alarms.Length.ShouldBe(1);
            processEvent.Alarms[0].AlarmType.ShouldBe("CreateTaskAlarm");
            processEvent.Alarms[0].DueAt.ShouldBe(s.Now.AddMinutes(16));
        }

OUTPUT
-------------
Shouldly.ShouldAssertExceptionprocessEvent.Alarms[0].DueAt
        should be
    2/03/2024 12:16:00 AM +00:00
        but was
    2/03/2024 12:15:00 AM +00:00

**Comment by JakeGinnivan** [comment]
Do you want multiple failures to be grouped? If so you can use

```
processEvent.ShouldSatistyAllConditions(p =>
{
   p.ShouldNotBe(null);
   p.Command.ShouldNotBeNullOrEmpty();
   ...
}
```

Can you put a code fence around that exception, it's not formatted properly so maybe I can't see the issue?

**Comment by jamesmiles** [comment]
The bug is that there should simply be a new line here and there isn't.

Shouldly.ShouldAssertExceptionprocess*[\N]*Event.Alarms[0].DueAt

**Comment by JakeGinnivan** [comment]
This should all be sorted now. In #335 I switched tests over to verify whitespace as well as content and fixed a heap of formatting issues.
