### ISSUE TITLE
Unexpected exception ShouldAssertException while testing string extension method...

### ISSUE THREAD

**Issue by natiki** [shouldly/shouldly#256]
Hi,

- VS 2013, .NET 4.51
- Shouldly 2.5.0 

It goes without saying that Shouldly is GREAT ;-). I have however run into an issue which while I am not certain is a Shouldly issue I cannot seem to work out why this is happening.

I have the following string extension method IsLike() that I am writing some unit tests for:

``` c#
        /// <summary>
        ///     Converts a string of characters to a HashSet of characters. If the string
        ///     contains character ranges, such as A-Z, all characters in the range are
        ///     also added to the returned set of characters.
        /// </summary>
        /// <param name="aCharList"> Character list string </param>
        /// <remarks>
        ///     Based on code from http://www.blackbeltcoder.com/Articles/net/implementing-vbs-like-operator-in-c
        /// </remarks>
        private static HashSet<char> CharListToSet(string aCharList)
        {
            HashSet<char> set = new HashSet<char>();

            for (int i = 0; i < aCharList.Length; i++)
            {
                if ((i + 1) < aCharList.Length && aCharList[i + 1] == '-')
                {
                    //Character range
                    char startChar = aCharList[i++];

                    i++; // Hyphen

                    char endChar = (char) 0;
                    if (i < aCharList.Length)
                        endChar = aCharList[i++];

                    for (int j = startChar; j <= endChar; j++)
                        set.Add((char) j);
                }
                else set.Add(aCharList[i]);
            }
            return set;
        }



/// <summary>
///     Implement's VB's Like operator logic
/// </summary>
        /// <remarks>
        ///     Based on code from http://www.blackbeltcoder.com/Articles/net/implementing-vbs-like-operator-in-c
        /// </remarks>
        public static bool IsLike(this string aString, string aPattern)
        {
            // Characters matched so far
            int matched = 0;

            // Loop through pattern string
            for (int i = 0; i < aPattern.Length;)
            {
                //Check for end of string
                if (matched >= aString.Length)
                    return false;

                //Get next pattern character
                char c = aPattern[i++];
                if (c == '[') // Character list
                {
                    //Test for exclude character
                    bool exclude = (i < aPattern.Length && aPattern[i] == '!');
                    if (exclude)
                        i++;

                    //Build character list
                    int j = aPattern.IndexOf(']', i);
                    if (j < 0)
                        j = aString.Length;
                    HashSet<char> charList = CharListToSet(aPattern.Substring(i, j - i));
                    i = j + 1;

                    if (charList.Contains(aString[matched]) == exclude)
                        return false;
                    matched++;
                }
                else if (c == '?') //Any single character
                {
                    matched++;
                }
                else if (c == '#') //Any single digit
                {
                    if (!Char.IsDigit(aString[matched]))
                        return false;
                    matched++;
                }
                else if (c == '*') //Zero or more characters
                {
                    if (i < aPattern.Length)
                    {
                        //Matches all characters until next character in pattern
                        char next = aPattern[i];
                        int j = aString.IndexOf(next, matched);
                        if (j < 0)
                            return false;
                        matched = j;
                    }
                    else
                    {
                        //Matches all remaining characters
                        matched = aString.Length;
                        break;
                    }
                }
                else //Exact character
                {
                    if (c != aString[matched])
                        return false;
                    matched++;
                }
            }

            //Return true if all characters matched
            return (matched == aString.Length);
        }
```

and finally my unit test:

``` c#
 [TestFixture]
    public class MyStringExtensionsTests
    {
        [TestCase]
        public void IsLikeVariousPatterns()
        {
            //Arrange

            //Act

            //Assert
            "123".IsLike("1#3").ShouldBe(true);
            "/admin".IsLike("/admin/*").ShouldBe(false);

            "/admin".IsLike("/admin*").ShouldBe(true);  //Generates exception

            var s = "/admin";
            s.IsLike("/admin*").ShouldBe(true);  //Does not generate exception
        }
    }
```

Notice the last test for **IsLike("/admin*")**. When done directly off a string I get an exception (image attached, stack trace below), but when I do the same test using a string variable there is no exception. Can you shed any light as to:

- Why I am getting the exception?
- Why the one version of the test generates an exception and the other one does not?

![image](https://cloud.githubusercontent.com/assets/4738140/8740368/cdc0eaa6-2c8b-11e5-8a7c-247f9c5a9eee.png)

** Stack Trace: **

> at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage) in c:\TeamCity\buildAgent\work\45364f332cb20c9\src\Shouldly\Internals\ShouldlyCoreExtensions.cs:line 21
> at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage) in c:\TeamCity\buildAgent\work\45364f332cb20c9\src\Shouldly\ShouldlyExtensionMethods\ShouldBe\GenericShouldBeTestExtensions.cs:line 25
> at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected) in c:\TeamCity\buildAgent\work\45364f332cb20c9\src\Shouldly\ShouldlyExtensionMethods\ShouldBe\GenericShouldBeTestExtensions.cs:line 14
> at OzCruising.Extensions.Tests.OzCruisingStringExtensionsTests.IsLikeVariousPatterns() in d:\Data\TFS\Ozcruising\VS 2013\OzcruisingShared\OzCruising.Extensions.Tests\OzCruisingStringExtensionsTests.cs:line 24

**Comment by JakeGinnivan** [comment]
Just had a quick look. The one which you say doesn't throw does seem to be throwing

![image](https://cloud.githubusercontent.com/assets/453152/8741343/c969a7a6-2c89-11e5-8784-180646b6ef11.png)

If you remove the `n` on admin it works. so `"/admin".IsLike("/admi*").ShouldBe(true);` works. I think the `IsLike` function is not working the way you expect it to?

**Comment by natiki** [comment]
Hi Jake,

Appreciate you getting back to me so quickly.

My bad,,, please ignore lines 18 & 19 in your screenshot. Those were other tests that are confusing the issue. I agree that IsLike() may not be working. What I am trying to understand however is why line 22 does not generate an exception and 23 does considering they are being passed the exact same parameters? 

The IsLike() is not throwing the exception so while its logic may be flawed (I believe it to be) it is not running off the end of anything and hence causing an exception that way, My simple evaluation of this is to set a break point on line 22 and then use my immediate window to execute:

```
s.IsLike("/admin*")
"/admin".IsLike("/admin*")
```

and no exception is thrown.

What is different between the two calls is that one uses a local variable (line 21, 22) and the one generating the exception uses the implicit variable from the declared string (line 23) - wondering if that has any effect on things?

**Comment by JakeGinnivan** [comment]
In my screenshot above line 22 is throwing an exception. For me both throw. When the first throughs the test stops executing, so I need to change the order of those to see them both failing. But for me both 22 and 23 generate exceptions

**Comment by natiki** [comment]
Hi Jake,

Appreciate you getting back to me so quickly. 

I concur and see the same behaviour. I may have misread things... :-( When running NUnit in debug mode using Resharper test runner the Shouldly.ShouldAssertException() is always raised when a test fails? Is that correct?

Without changing the IsLike() implementation I did two runs, using each one:

![image](https://cloud.githubusercontent.com/assets/4738140/8742186/0eab675c-2ca6-11e5-9011-1cb4f8093d0f.png)

![image](https://cloud.githubusercontent.com/assets/4738140/8742189/1c1e9dc8-2ca6-11e5-8206-593a832d0073.png)

**Comment by JakeGinnivan** [comment]
Yeah, so shouldly just throws an exception when it fails. This will cause the test to stop executing and the test fail immediately (and the rest of the test will not be executed).

If you want multiple asserts to run and get a summary of which fails then you can use `ShouldSatisfyAllConditions`. See http://docs.shouldly-lib.net/docs/shouldsatisfyallconditions

**Comment by natiki** [comment]
Hi Jake,

Thanks for the pointer and apologies for misunderstanding the cause of the exception.

**Comment by JakeGinnivan** [comment]
No probe, happy to help

Sent from my Windows Phone
________________________________
