### ISSUE TITLE
Remove ShouldThrow/ShouldNotThrow?

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#260]
Based on the work around improving ShouldThrow/ShouldNotThrow I am wondering if we should follow xUnit and remove them. This is a discussion, not a plan. I am still on the fence but all the examples I come up with if I think about it more I normally can think of a better test. 

See discussion at https://github.com/xunit/xunit/issues/188

Here are some examples of using ShouldThrow and what it could become:

```
Should.Throw<FooException>(() => callSomeMethod());
//
var ex = Record.Exception(() => callSomeMethod());

ex.ShouldBeOfType<FooException>();
```
This doesn't violate AAA and sticks to each line in the test doing something. ShouldThrow conflates executing and asserting.

```
Should.NotThrow(() => someMethod());
//
someMethod();
//

someMethod()l

//Assert something else, either on the return value or a side effect. 
```

The work in #259 makes the exception nicer, but the stack trace you get if shouldly wasn't involved would be almost as nice as it gives you the line number and you can jump to that line.

What do people think? Do should.throw and should.notthrow provide a lot of value to you? What are some examples where you are using it where you use it.

// @yannisgu @JoeMighty

**Comment by JoeMighty** [comment]
Personally I'm in favour of keeping it. I like the explicitness of it. [Suraj's comment](https://github.com/xunit/xunit/issues/188#issuecomment-86621058) echos my feelings about it (just without the sarcasm).

Whilst we haven't used it loads, there are instances where it has been used - one being when writing tests against an asmx webservice where mocking the internals wasn't an option and custom exceptions were thrown for various reasons that we needed to test for.
