### ISSUE TITLE
Debug vs Release mode verbage

### ISSUE THREAD

**Issue by mudnug** [shouldly/shouldly#262]
I'm seeing Shouldly.ShouldAssertException shows "The provided expression" instead of a more specific identifier when we are running tests in release mode. For example:

    The provided expression
        should be
    5
        but was
    4

I expect this would happen if Shouldly is using reflection to determine what the identifier should be (and the compiler has rearranged the code when compiling).

Has anyone else discussed any workaround for this? Perhaps the only option is to set the build server to compile the tests with optimizations turned off.

**Comment by chaitanyagurrapu** [comment]
Similar discussion previously here -> https://github.com/shouldly/shouldly/issues/234

It needs the symbol information via the pdbs. 

Hope it helps.

**Comment by mudnug** [comment]
The pdb is available. Is the linked item saying the source has to be located somewhere, too?

**Comment by JakeGinnivan** [comment]
Yeah, the PDB with full source information *and* the source must be available for Shouldly to give it's error messages

**Comment by mudnug** [comment]
I'm not sure I understand how to set that up. Where should the source be located?

**Comment by JakeGinnivan** [comment]
You should be able to just build and run the tests, as long as you have full debug info in the pdb then it will work fine.

**Comment by mudnug** [comment]
We were able to do that, but when the build server builds and deploys the tests the runs show the more generic messaging.

**Comment by JakeGinnivan** [comment]
Do you build and run the tests in place, or are they run in another location to where they are build (i.e two separate builds)

**Comment by mudnug** [comment]
They run in a separate location. Does that mean the source has to be copied to the same location where it would have been on the build server?

**Comment by JakeGinnivan** [comment]
Yes, or run the tests in the same build as when the artifacts are built.

Without the source the aim is shouldly gives about the same amount of information than other framework. i.e nUnit `Expected 5 but was 4`. With the source it can provide much more information than other frameworks.

**Comment by mudnug** [comment]
Ok. That wasn't initially clear (I thought it might use reflection or AOP or some other technique). Thanks for the help.

**Comment by JakeGinnivan** [comment]
Will have a think how we can make this information more easily available. Reflection doesn't have enough information to do what we do unfortunately.

**Comment by mudnug** [comment]
One option might involve the use of the C# 6 nameof keyword
