### ISSUE TITLE
ShouldContain() fails when the item is in the list?

### ISSUE THREAD

**Issue by natiki** [shouldly/shouldly#267]
Hi,

Why does the following fail? The item is in the list. I am assuming I have a comparison issue here where the object contents are not being compared but rather the references to the list items. If so how should you check for the existence of an item within the list that has identical values?

![image](https://cloud.githubusercontent.com/assets/4738140/9623942/2c170e5e-518b-11e5-9af9-632e46970ae6.png)

**Comment by JakeGinnivan** [comment]
We have an open issue to add object graph equality checking at #245. To make this work you need to override the `.Equals` method on `RegionItem` so it does a value comparison not a reference comparison.

**Comment by natiki** [comment]
Thanks. Look forward to #245 but this works fine for now.
