### ISSUE TITLE
Is there a "summarized" change log....

### ISSUE THREAD

**Issue by natiki** [shouldly/shouldly#268]
Hi,

Noticed that 2.6.0 has made it out the door. WooHoo. More nice free stuff to play with. Now while I could go and read all the issues covered in this release (and I did), I was wondering if there was a summarized change log that might just give a brief intro/discussion to some of the cool features that appear to be in this release like #233 or similair? I would hate to think I missed out on something ;-)

When looking on http://docs.shouldly-lib.net but that appears tied to 2.4.0.

**Comment by JakeGinnivan** [comment]
There isn't, I am working on another project GitReleaseNotes which will make this sort of thing easier. I plan on moving the docs again to make this better, so watch that space (hopefully next week or two).

**Comment by natiki** [comment]
Cool. Will close this for now and watch for the magic to happen.
