### ISSUE TITLE
Megazord FluentAssertions assertions with Shouldly

### ISSUE THREAD

**Issue by AlexKeySmith** [shouldly/shouldly#269]
It would be fantastic to have all the assertions available in FluentAssertions like number of items in the collection etc. But have the absolutely awesome output messages that shouldly provides.

I'm hoping for some sort of power ranger style / "megazord"-esque combination...

![illustration of combining powers](http://stream1.gifsoup.com/view1/3848027/ninja-megazord-o.gif)

Yes, I realize this is a big ask - hence the tongue-in-cheek illustration :-) But it's nice to dream.

**Comment by JakeGinnivan** [comment]
Hey @AlexKeySmith 

Lets create an issue for each of the missing ones, describing the API and the error messages it should produce. Once the issues are created I can mark them as up for grabs and anyone can jump in and add them one at a time.

Did you want to make a start on some of the missing assertions?

**Comment by AlexKeySmith** [comment]
Thanks for the comment @JakeGinnivan I'll try to help out if I get a spare moment. 

Keep up the great work :-)
