### ISSUE TITLE
New Assertion: ShouldCount

### ISSUE THREAD

**Issue by JoeMighty** [shouldly/shouldly#270]
Following on from the [recent dicussion](https://github.com/shouldly/shouldly/issues/269) about adding more assertions, one I feel would be beneficial is `ShouldHaveCount` or `ShouldCount` (still undecided on which seems best).

Users can currently check to see if a collection is empty using `new int[0].ShouldBeEmpty(); but it would be great if they could check to see how many items are in the collection.

So I'm proposing something like this:

    new[] { 1,2,3 }.ShouldCount(3);

**Comment by JakeGinnivan** [comment]
Not sure this is more readable over `new[] { 1,2,3 }.Length.ShouldBe(3);` ?

**Comment by JoeMighty** [comment]
Yeah, on further thought you're right; `ShouldCount` doesn't add any value.
