### ISSUE TITLE
Implement ShouldHaveValue() and ShouldNotHaveValue() for nullable numeric types

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#271]
See https://github.com/shouldly/shouldly/issues/269

ShouldHaveValue():
Asserts that a nullable numeric value is not null.

ShouldNotHaveValue():
Asserts that a nullable numeric value is null.

**Comment by JakeGinnivan** [comment]
We have `ShouldBeNull()` and `ShouldNotBeNull()` for this one
