### ISSUE TITLE
Implement ShouldHaveFlag() and ShouldNotHaveFlag() for enums decorated with [Flags] attribute

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#272]
See #269

ShouldHaveFlag(Enum expectedFlag):
Asserts that an object is an enum and has a specified flag

ShouldNotHaveFlag(Enum expectedFlag):
Asserts that an object is an enum and does not have a specified flag

**Comment by JakeGinnivan** [comment]
Could you add an example of the idea error message for this

**Comment by JosephWoodward** [comment]
This issue can now be closed as it was completed within [this PR](https://github.com/shouldly/shouldly/pull/355/commits).
