### ISSUE TITLE
Implement ShouldBePositive() and ShouldBeNegative() for numeric types with sign

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#273]
See #269 

ShouldBeNegative():
Asserts that the numeric value is less than zero.

ShouldBePositive():
Asserts that the numeric value is greater than or equal to zero.

**Comment by JakeGinnivan** [comment]
@ceregador can you include examples of what the exception message would be for all of the issues I mark `Jump-in`.

**Comment by ceregador** [comment]
_Example of an error message for ShouldBePositive():_
Expected positive value, but found -5

_Example of an error message for ShouldBeNegative():_
Expected negative value, but found 5

**Comment by cmatskas** [comment]
Hi guys, I may as well take this one on in favor of #Hacktoberfest, if you're happy with it...Do you have a label for assigned tasks?

**Comment by JoeMighty** [comment]
Hey @cmatskas; of course! The more help the better. #Hacktoberfest certainly seems like a great idea doesn't it.

As for assigned tasks, we don't have any labels for assigned tasks, just add a comment to let everyone know that you're working on it.

This is quite a new task so the error message that should be generated hasn't been finalised just yet, but I imagine it would be something like below (pending minor tweaks to the wording):

```
const int myValue = 12;
myValueShouldBeNegative();
```

Would result in an error saying:
`myValue was 12 and should be negative but was positive` (thoughts @JakeGinnivan?)

#304 is another task that should be a good introduction to the way Shouldly works.

**Comment by JoeMighty** [comment]
Hi @cmatskas, are you still working/planning on working on this one or are you happy for me to pick it up?

**Comment by gertnelissen** [comment]
I am willing to tackle this. How would you expect this to operate on non-numeric values like strings or objects?

**Comment by cmatskas** [comment]
Damn, I forgot I was looking into this. A bit swamped at the moment so happy for someone else to look into it. Free again after end of Oct :) Unless you can wait, in which case I'll take this one

**Comment by JoeMighty** [comment]
Hi @gertnelissen You're more than welcome to take it on :+1: This assertion extension would be for numeric values only, so you needn't worry about other scenarios.

**Comment by gertnelissen** [comment]
I've implemented these assertions but I have some questions regarding the solution/tests setup:
* The ApprovePublicAPI test is failing, but this is probably something I can't fix without you guys merging these assert methods with the API?
* I'm ignoring scenario's where someone uses the assert methods on non-numeric values like you said. What do you guys normally do in these cases? Make the assert methods explicit instead of generic? Detect manually and throw some exception?

**Comment by JakeGinnivan** [comment]
> The ApprovePublicAPI test is failing, but this is probably something I can't fix without you guys merging these assert methods with the API?

Just run the test with a normal test runner, it should pop-up a diff tool, then you can merge the changes into the approved file. This is so we don't accidentally break the public API.

 > I'm ignoring scenario's where someone uses the assert methods on non-numeric values like you said. What do you guys normally do in these cases? Make the assert methods explicit instead of generic? Detect manually and throw some exception?

Create extension methods for `int`, `float`, `decimal` and `double`.

**Comment by gertnelissen** [comment]
Okay this is implemented (for short and long as well). Am I expected to document this somewhere or do I simply do a pull request?

**Comment by JoeMighty** [comment]
A pull request is all you need to do. We're currently in the process of migrating the docs so they'll be covered at some point.

**Comment by JakeGinnivan** [comment]
The docs for this should be added in this PR.

Sent from my Windows Phone
________________________________
