### ISSUE TITLE
Implement ShouldBeCloseTo() for DateTime and DateTimeOffset type

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#274]
ShouldBeCloseTo(DateTime nearbyTime, int precision = 20)

Asserts that the current dateTime is within the specified number of milliseconds (default = 20 ms) from the specified nearbyTime value.

You can use this assertion when, for example the database truncates datetimes to nearest 20ms.

**Comment by JakeGinnivan** [comment]
We already have `.ShouldBe(date, TimeSpan tolerance)`

**Comment by Edgaras91** [comment]
Anything for Nullable DateTime? Facing this issue now.

**Comment by kurtlmartin** [comment]
@Edgaras91 
I ran into this as well. Due to knowing that in this unit test my Nullable DateTime will be tested with a value, I did this. 
`Date.Value.ShouldBe(DateTime.Now, TimeSpan.FromMinutes(1));`
Hope this helps. :)

**Comment by Edgaras91** [comment]
Thanks, @kurtlmartin, but what if one test case will give a value, and the other won't. Would prefer a more future proof nullable datetime against nullable dateime, to make sure they both the same.
