### ISSUE TITLE
Implement ShouldStartWith() for IEnumerable

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#281]
_ShouldStartWith(object element)_
Asserts that the collection starts with the specified element.

**Comment by JakeGinnivan** [comment]
Can be achieved via linq. `enumerable.FirstOrDefault().ShouldBe(element)`

**Comment by SurajGupta** [comment]
ShouldStartWith is far more readable than the current solution.  Same comment as here: https://github.com/shouldly/shouldly/issues/280

**Comment by ceregador** [comment]
`var collection = new[] {1, 3, 5};`
`collection.ShouldStartWith(3);`

_Example of an error message for ShouldStartWith():_
Expected collection to start with 3, but found 1.

**Comment by bmpj13** [comment]
I can take a look at this, if you want @JakeGinnivan

**Comment by brunomasantos** [comment]
Hi guys,

I wanted to start contributing to this project. Wondering if is this that i can try to pick up. I see its open a long time now.

Thanks guys

**Comment by JosephWoodward** [comment]
@brunomasantos We already have an open [pull request](https://github.com/shouldly/shouldly/pull/417) surround this one.

**Comment by brunomasantos** [comment]
Completely missed it, sorry 👍

**Comment by JosephWoodward** [comment]
I'm going to close this one off as we've not had much interest it as a feature and agree with Jake that `enumerable.FirstOrDefault().ShouldBe(element)` is clearer.
