### ISSUE TITLE
Implement ShouldEndWith() for IEnumerable

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#282]
_ShouldEndWith(object element)_
Asserts that the collection ends with the specified element.

**Comment by JakeGinnivan** [comment]
Linq is pretty powerful, I don't think we should try and replace it.

`enumerable.LastOrDefault().ShouldBe(element)` will be just as good.

**Comment by SurajGupta** [comment]
ShouldEndWith is far more readable than the current solution.  Same comment as here: https://github.com/shouldly/shouldly/issues/280

**Comment by ceregador** [comment]
`var collection = new[] {1, 3, 5};`
`collection.ShouldEndWith(3);`

_Example of an error message for ShouldEndWith():_
Expected collection to end with 3, but found 5.
