### ISSUE TITLE
Implement ShouldHaveElementAt() for IEnumerable

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#283]
_ShouldHaveElementAt(int index, object element)_
Asserts that the current collection has the supplied element at the supplied index.

**Comment by JakeGinnivan** [comment]
I think using linq for this scenario is simpler and keeps the complexity of shouldly down. `enumerable.ElementAt(1).ShouldBe(...)`

The only reason I can see to keep this is that `.ElementAt(1)` may not be the best error message. Thoughts @JoeMighty

**Comment by JakeGinnivan** [comment]
Actually, using `ElementAtOrDefault` will stop any exception which Linq would throw. So I don't think we need this. Feel free to disagree but closing unless we decide differently

**Comment by JoeMighty** [comment]
I'm in agreement with you. I think adding these additional methods (that would hide what is essentially a simply linq query to perform the same test) won't bring any real value and just add a lot of unnecessary noise to the API.

**Comment by SurajGupta** [comment]
agree in this case - the existing solution is no less readable
