### ISSUE TITLE
Implement ShouldHaveElementPreceding() for IEnumerable

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#284]
_ShouldHaveElementPreceding(object successor, object expectation)_
Asserts that the expectation element directly precedes the successor element.

**Comment by JakeGinnivan** [comment]
I find this and #285 are not that clear, the steps it is trying to explain in a short method name is, find the index of this item, find the previous item then make sure it matches another.

This means we need to have different error messages for if we are asserting against the first item in the list as well, if the item does not exist in the list *and* that the next element actually matches. It is succinct but there is a lot going on there, is it too much?

What is a usecase/example of where this would be used which would go into the docs and the error messages. Can we roll #285 into this one, they are closely related so lets have a discussion and both can be added in a single pull request if someone wants to do it.

**Comment by SurajGupta** [comment]
I think we should close this out.  It's confusing and probably low-value-add.

**Comment by JoeMighty** [comment]
Agreed. I certainly can't think of any use case.
