### ISSUE TITLE
Implement ShouldBeBinarySerializable() for Object type

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#289]
_ShouldBeBinarySerializable()_
Asserts that an object can be serialized and deserialized using the binary serializer and that it stills retains the values of all members.

**Comment by JakeGinnivan** [comment]
Would this do a deep comparison if the objects or simply call .Equals? Currently we don't have anything like that, maybe `ShouldBeDeepEqual()` then something like this could be built on top of it.

**Comment by ceregador** [comment]
I dug into the code of FluentAssertionts library and found following description for internal function which compares original and deserialized object:

_Objects are equivalent when both object graphs have equally named properties with the same value, irrespective of the type of those objects. Two properties are also equal if one type can be converted to another and the result is equal.
The type of a collection property is ignored as long as the collection implements System.Collections.IEnumerable and all items in the collection are  structurally equal._

**Comment by SurajGupta** [comment]
I'm on the fence about the utility of this one.  I wouldn't object if you closed it out.
