### ISSUE TITLE
Implement ShouldBeDecoratedWith() for Type

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#291]
_ShouldBeDecoratedWith<TAttribute>()_
Asserts that the current type is decorated with the specified TAttribute.

**Comment by JakeGinnivan** [comment]
`ShouldHaveAttribute` might be a better name for this one. But it doesn't cover methods or properties. I am unsure if we want Shouldly to go down the reflection road. I would prefer just using `type.GetCustomAttribute<T>().ShouldNotBeNull()` which is quite readable and will still give a good exception message

**Comment by SurajGupta** [comment]
ShouldBeDecoratedWith is far more readable than the current solution.  Same comment as here: https://github.com/shouldly/shouldly/issues/280

**Comment by ceregador** [comment]
`typeof(IEnumerable).ShouldBeDecoratedWith<FlagsAttribute>();`

_Example of an error message for ShouldBeDecoratedWith():_
Expected type System.Collections.IEnumerable to be decorated with System.FlagsAttribute, but the attribute was not found.
