### ISSUE TITLE
Implement ShouldBeDerivedFrom() for Type

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#292]
_ShouldBeDerivedFrom<TBaseClass>()_
Asserts that the current type is derived from TBaseClass.

**Comment by JakeGinnivan** [comment]
Already exists: `ShouldBeOfType<T>`

**Comment by SurajGupta** [comment]
Is there a way to check that an object is of a derived type and not a base type?  It seems that ShouldByOfType allows both derived and base types?

**Comment by JakeGinnivan** [comment]
Hrrm, looks like this could be a bug. ShouldBeOfType should be exact type. ShouldBeAssignableTo is the one which allows both
