### ISSUE TITLE
Implement ShouldHaveMethod() for Type

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#298]
_ShouldHaveMethod(string name, IEnumerable<Type> parameterTypes)_
Asserts that the current type has a method named **name** with parameter types **parameterTypes**.

_ShouldNotHaveMethod(string name, IEnumerable<Type> parameterTypes)_
Asserts that the current type does not expose a method named **name** with parameter types **parameterTypes**.

**Comment by JakeGinnivan** [comment]
See https://github.com/shouldly/shouldly/issues/294#issuecomment-143942503
