### ISSUE TITLE
Implement ShouldHaveProperty() for Type

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#299]
_ShouldHaveProperty<TProperty>(string name)_
Asserts that the current type has a property of type **TProperty** named **name**.

_ShouldNotHaveProperty<TProperty>(string name)_
Asserts that the current type does not have a property of type **TProperty** named **name**.

**Comment by JakeGinnivan** [comment]
https://github.com/shouldly/shouldly/issues/294#issuecomment-143942503

Also this exists on `DynamicShould`
