### ISSUE TITLE
Include numeric type shortcut on values in error messages

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#301]
For example `0.01m` instead of just `0.01` for decimal type.

List is:

* F:  float
* D:  double
* U:  uint
* L:  long
* UL: ulong
* M:  decimal

**Comment by AmadeusW** [comment]
I've implemented this, and noticed that this change has a very broad reach since it changes the error message. Are there any backwards compatibility issues to consider except for over 30 failing tests that need their expected message tweaked?

**Comment by JoeMighty** [comment]
No, I don't think there are any backwards compatibility issues to worry about, it should just be a case of updating the broken tests.
