### ISSUE TITLE
Improve ShouldNotBe error message

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#304]
``` csharp
var theSimpsonsCat = new Cat() { Name = "Santas little helper" };
theSimpsonsCat.Name.ShouldNotBe("Santas little helper");
```

## Current
> ```
theSimpsonsCat.Name
    should not be
"Santas little helper"
    but was
"Santas little helper"
```

## Expected
The value is repeated, we don't need to repeat values for `ShouldNotBe`, if it fails the values are the same

> ```
theSimpsonsCat.Name
    should not be
"Santas little helper"
    but was
```

**Comment by cmatskas** [comment]
Are we sure that we want the error message to terminate at "but was"?. Is not "TheSimpsonsCat.Name should not be 'Santas little helper'?. Just a thought

**Comment by JakeGinnivan** [comment]
If ShouldNotBe fails it means expected and actual are the same, so will always repeat

Sent from my Windows Phone
________________________________

**Comment by cmatskas** [comment]
I'm a bit confused now as the bug says that we should not repeat the failed value. If you give me the desired error message, I'll be happy to implement this as well :) Thanks again for your feedback

**Comment by JakeGinnivan** [comment]
Yeah exactly, it repeats at the moment. I think it shouldn't. What do you think?

Sent from my Windows Phone
________________________________

**Comment by JoeMighty** [comment]
I agree. It seems unnecessary to repeat it if they're the same.

**Comment by cmatskas** [comment]
I believe, using the example above, that the correct message should be:
"TheSimpsonsCat.Name should not be 'Santas little helper'"

**Comment by JoeMighty** [comment]
I think I prefer the explicitness of "but was" at the end rather than the implied nature without it personally.

**Comment by cmatskas** [comment]
Cool, in that case we're going with:
"TheSimpsonsCat.Name should not be 'Santas little helper' but is" 
"TheSimpsonsCat.Name should not have been 'Santas little helper' but was" 

Apologies but I'm a stickler for grammar. Happy to go with whatever the group decides :)

**Comment by cmatskas** [comment]
@JakeGinnivan @JoeMighty - PR raised...let me know if you have any feedback.

**Comment by JoeMighty** [comment]
That's been merged now @cmatskas. Thanks for your contribution!
