### ISSUE TITLE
Migrate docs to readthedocs.org

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#308]
What needs to be done, post here if you are picking up a topic. I will put your name next to the task, please try and submit a pull request soon after so the task does not get blocked. If you cannot complete your task, let me know and I can remove you!

Current docs are at http://docs.shouldly-lib.net/v2.4.0 - some docs are missing, others out of date. Once the section has been created in the new docs, I will delete it out of the current docs site. If you notice I have missed something, yell out!

The docs are in the `docs` folder in the repository, so just submit a pull request. For new files make sure you update the [mkdocs.yml](https://github.com/shouldly/shouldly/blob/master/mkdocs.yml) file. https://github.com/shouldly/shouldly/tree/master/docs

Top level is a single markdown file, second level indicates a H2 (or ##) in that file
## Equality
- [x] ShouldBe
  - [x] Object
  - [x] Numeric
  - [x] DateTime(Offset)
  - [x] TimeSpan
  - [x] String (should link to string ShouldBe section)
  - [x] Enumerable (link to ShouldBe in enumerable section)
- [x] ShouldNotBe
  - [x] Object
  - [x] Numeric
  - [x] DateTime(Offset)
  - [x] TimeSpan
- [x] ShouldBeTrue/False
- [x] ShouldBeNull
  - [x] ShouldNotBeNull
- [x] ShouldBeSameAs
  - [x] ShouldNotBeSameAs
- [x] ShouldBeOneOf
  - [x] ShouldNotBeOneOf
- [x] ShouldBeGreater/LessThan
  - [x] ShouldBeGreaterThan
  - [x] ShouldBeLessThan
  - [x] ShouldBeGreaterThanOrEqualTo
  - [x] ShouldBeLessThanOrEqualTo
- [x] ShouldBeInRange
  - [x] ShouldNotBeInRange
- [x] ShouldBeOfType
  - [x] ShouldNotBeOfType
- [x] ShouldBeAssignableTo
  - [x] ShouldNotBeAssignableTo
## Strings

All these should show the case sensitivity options.
- [x] ShouldBe
  - [x] ShouldNotBe
- [x] ShouldStartWith
  - [x] ShouldNotStartWith
- [x] ShouldEndWith
  - [x] ShouldNotEndWith
- [x] ShouldMatch
  - [x] ShouldNotMatch - Overload missing see #312
- [x] ShouldBeNullOrEmpty
  - [x] ShouldNotBeNullOrEmpty
- [x] ShouldBeNullOrWhiteSpace
  - [x] ShouldNotBeNullOrWhiteSpace
- [x] ShouldContain
  - [x] ShouldNotContain
- [x] ShouldContainWithoutWhitespace
## Enumerable
- [x] ShouldBe (move from equality section)
- [x] ShouldAllBe
- [x] ShouldBeEmpty
  - [x] ShouldNotBeEmpty
- [x] ShouldBeSubsetOf
- [x] ShouldBeUnique
- [x] ShouldContain
  - [x] T
  - [x] Predicate&lt;T&gt;
- [x] ShouldNotContain
  - [x] T
  - [x] Predicate&lt;T&gt;
## Dictionaries
- [x] ShouldContainKey
  - [x] ShouldNotContainKey
- [x] ShouldContainKeyAndValue
  - [x] ShouldNotContainValueForKey
## Exceptions
- [x] Should.Throw
  - [x] Action&lt;T&gt;
  - [x] Func&lt;T&gt;
  - [x] Task
  - [x] ShouldThrow extension method
  - [x] ShouldThrowAsync
- [x] ShouldNotThrow
  - [x] Action&lt;T&gt;
  - [x] Func&lt;T&gt;
  - [x] Task
  - [x] ShouldThrow extension method
## Other
- [x] ShouldCompleteIn
- [x] ShouldSatisfyAllConditions
- [x] DynamicShould
  - [x] HaveProperty

**Comment by JoeMighty** [comment]
Sounds good! I'll try and make a start on some of these tonight.

**Comment by enkafan** [comment]
What are your thoughts about using a sample project to illustrate the code samples, and then bring in the code samples into the docs via Sphinx's `literalinclude` functionality?

You can see this in action on the ASP.NET docs 

Source - https://raw.githubusercontent.com/aspnet/Docs/master/aspnet/tutorials/your-first-aspnet-application.rst
In Action - http://aspnet.readthedocs.org/en/latest/tutorials/your-first-aspnet-application.html

That way the samples more or less get compiled with the build (assuming the sample project is included in the build process, of course). Coding style and standards could also be easily enforced. Plus it'd give people a chance to open the project and run through all the examples. I figure people will probably be writing their sample code in Visual Studio regardless - this just saves them from having to create their own project for copying and pasting.

The downside is I don't think markdown supports this. I've always used reStructuredText with Sphinx myself, so I'm pretty comfortable with it but I could see it being a an initial blocker to people contributing.

**Comment by JakeGinnivan** [comment]
Hey @enkafan 

That sounds pretty cool actually. I don't mind switching to rst, I haven't used it myself but if you wanted to submit a PR which switches it I am happy to go down that road. I don't think it will be a blocker to contributing as there are examples to follow.

**Comment by enkafan** [comment]
Issued a pull request (#316) with a quick redo to Sphinx. I included a contributing page pulled from the ASP.NET groups contributing page to include steps on running sphinx on your local box plus the style guidelines they recommend.

**Comment by billglover** [comment]
Was about to jump in and try and help but it looks as though we need PR #316 to be merged before starting. It looks as though reStructuredText is now the preferred format.

**Comment by JakeGinnivan** [comment]
@billglover merged now :) sorry about that

**Comment by JakeGinnivan** [comment]
Hey all, 

I have put some new docs infrastructure in place which makes all this quite nice. Help on finishing this off would be awesome :)

**Comment by JosephWoodward** [comment]
I've started working on this, however I'm noticing that my new assertions aren't appearing within the navigation of other assertion doc files (ie: _build/html/assertions/shouldMatchApproved.html). I've added the assertion to the index.rst file (I see you did the same thing when updating the docs); do you have any ideas what I could be missing?

**Comment by JakeGinnivan** [comment]
Make sure you delete your local _build folder and rebuild. I have noticed it doesn't always rebuild the TOC

**Comment by JosephWoodward** [comment]
Alright, thanks Jake. I'll give that a try.

**Comment by JosephWoodward** [comment]
Finally got around to trying it and that was the issue, you've got to delete the _build folder and rebuild (for anyone else who experiences the same issue!)

**Comment by mwhitis** [comment]
@JakeGinnivan - Is the list at the top of the issue still current for what needs converting?  Been looking for a project to get involved with, and this seems like a good place to jump in.

**Comment by JosephWoodward** [comment]
Hi @mwhitis Yes, the list is still up to date. Help with the docs would be very much appreciated!

**Comment by morrme** [comment]
i'm a little new, so pardon my question, but does this just involve taking a topic and reformatting it to fit the doc format of this repo?

**Comment by JosephWoodward** [comment]
Hi @morrme 

Yes it does, though we have some means of auto generating the code samples. [This](https://github.com/shouldly/shouldly/commit/fc8c632b44afd9f92687a9f8199b52c9eea5305c) pull request will give you an idea of what's involved.

If you have any questions then do ask :)

**Comment by morrme** [comment]
@JosephWoodward  took me a while to find this issue again!

So are the generators written by hand based on the current samples?

**Comment by weav797** [comment]
Is this still an open issue? If so, I'd love to help out.

**Comment by JosephWoodward** [comment]
Yes it is still an issue, there's soooo much migration to do :S

**Comment by weav797** [comment]
Hey Joseph,

Sorry for the wait in responding. I'll try to set aside some time this weekend. It's been hectic at work. I'll let you know once I get set up and everything.

**Comment by weav797** [comment]
@JosephWoodward I sent you an email regarding an issue. Can you see if you got it?

**Comment by TantumErgo** [comment]
I can see that this issue is still open, and that there's a ton left to do, but I honestly can't figure out what it is that needs to be done. I would like to help, so if anyone could explain to me what needs to be done, that would be great.

Is it just a matter of copying the content on the old docs site to the new docs site (readthedocs.org), or is there more involved?

@JosephWoodward in an earlier comment, you referenced a pull request as being indicative of what this task involves, but I didn't understand even after taking a look at it...

**Comment by JosephWoodward** [comment]
Yeah, this is something I'd really like to finish soon. I'll need to refresh my memory on how to do it first, I also wonder whether there's a Docker container to help with setting up a local environment.

**Comment by eddex** [comment]
> Yes it does, though we have some means of auto generating the code samples. [This](https://github.com/shouldly/shouldly/commit/fc8c632b44afd9f92687a9f8199b52c9eea5305c) pull request will give you an idea of what's involved.

Hi, I just found this issue and I'm a bit confused. The changes referred to in the comment above refer to a commit where next to documentation also code changes were done. Is this issue only about migrating the documentation or is this a some sort of a migration of the code too? And if so, where can we find the old codebase?

**Comment by SimonCropp** [comment]
@jnm2 @JosephWoodward ok i made a fair dint on the usages snippets and the resulting exception. see update list above. changes have been deployed to the docs site.

**Comment by JosephWoodward** [comment]
> @jnm2 @JosephWoodward ok i made a fair dint on the usages snippets and the resulting exception. see update list above. changes have been deployed to the docs site.

Oh nice! Well done!

**Comment by SimonCropp** [comment]
ok this is done. let me know if i missed anything

**Comment by jnm2** [comment]
@SimonCropp You're a legend!
