### ISSUE TITLE
Tests fail with Hungarian regional settings

### ISSUE THREAD

**Issue by Dotneteer** [shouldly/shouldly#324]
11 test fail when Hungarian regional settings is used.

**Comment by JoeMighty** [comment]
I'm getting the same result.

It's the decimal point separator that's causing the tests to break (see [ShouldNotBeInRangeTests for example](https://github.com/shouldly/shouldly/blob/master/src/Shouldly.Tests/ShouldNotBeInRangeTests.cs)) as Hungary use a decimal comma.

Example of error:

```
    ShouldThrowAWobbly
        error
    "1.5m should not be in range { from = 1.4, to = 1.6 } but was 1.5
Additional Info:
Some additional context"
        but was
    "
    1.5m
        should not be in range
    { from = 1,4, to = 1,6 }
        but was
    1,5
    Additional Info:
    Some additional context"
```

**Comment by JoeMighty** [comment]
As our tests are all written using the decimal point I've created a PR (#325) to set the culture to `en-GB`, if you're happy with this solution @JakeGinnivan?
