### ISSUE TITLE
ShouldThrow fails under Mono

### ISSUE THREAD

**Issue by nbarbettini** [shouldly/shouldly#327]
Running this test code with the latest build of Mono:

```csharp
var task = Task.Factory.StartNew(() => { throw new ArgumentNullException(); },
	CancellationToken.None, TaskCreationOptions.None,
	TaskScheduler.Default);

Should.Throw<ArgumentNullException> (async () =>
{
	await task;
});
```

Throws this error message:

> The provided expression` should throw System.ArgumentNullException but threw System.NullReferenceException

**Comment by JoeMighty** [comment]
This has now been fixed, thanks for the contribution @nbarbettini!
