### ISSUE TITLE
Support CoreCLR

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#331]
This will make the shouldly codebase require VS2015 and the new dnx tooling. Any objections?

I am starting to work on this.

// @JoeMighty

**Comment by JoeMighty** [comment]
No objections from me - VS2015 is my main editor and it'll be good getting Shouldly CoreCLR compliant.

**Comment by JakeGinnivan** [comment]
First step, convert tests to xUnit. Am working on this, it's a decent change.

We also need to start testing the error messages when source is not available and be able to get the shouldly method without walking the stacktrace because CoreCLR doesn't have stack trace support yet. As a side affect we can make shouldly a pretty broad PCL library to target all platforms.

**Comment by JoeMighty** [comment]
Sounds good to me. If there's anything I can do to help out then please do let me know, perhaps flag them in here or add them as an issue?

**Comment by jbogard** [comment]
Just came here looking for a CoreCLR version lol. Ditto on help, I'm working through some other DNX projects too.

**Comment by JakeGinnivan** [comment]
The biggest blocker is that StackTrace/StackFrame is not available in CoreCLR and all of Shouldlys tests are testing with source. I am switching Shouldly to xunit and changing all tests so they test both the with and without source error messages. A bunch of message generators crashed and others had terrible messages.

The conversion is a WIP at https://github.com/shouldly/shouldly/pull/335

I have ~100 failing tests left and I am getting through about 50 a night, so should get there over the weekend

**Comment by JakeGinnivan** [comment]
Done, next release should support pcl and dnx

**Comment by jbogard** [comment]
Nice! When should I expect that to drop?
