### ISSUE TITLE
ShouldBeSameAs and reference equality

### ISSUE THREAD

**Issue by TrueWill** [shouldly/shouldly#344]
More of a suggestion than an issue.

The behavior of `ShouldBeSameAs` is unintuitive to me (and most of Shouldly is *very* intuitive). The implementation calls `Is.Same`, which uses `==` (this surprised me). Since the operator can be overloaded, would it make sense to implement this with `Object.ReferenceEquals`? Or would it make more sense to add a "ShouldBeSameInstanceAs" or similar method? Thanks!

**Comment by JakeGinnivan** [comment]
I actually noticed this during the CoreCLR refactoring and fix it. See https://github.com/shouldly/shouldly/blob/master/src/Shouldly.Shared/Internals/Is.cs#L26

This will be sorted in the next release :)

**Comment by TrueWill** [comment]
Thank you! :+1:

**Comment by dotnetchris** [comment]
What's the status of this? I'm seeing `==` in Shouldly.2.7.0-beta0003\lib\net40\Shouldly.dll
