### ISSUE TITLE
Allow custom IComparer instances for classes that don't implement IComparable

### ISSUE THREAD

**Issue by josemesona** [shouldly/shouldly#364]
I have a 3rd party class that I can manually compare but it doesn't implement IComparable.  So I want to be able to call `ShouldBeGreaterThan<T>()` but this doesn't seem possible since that method requires that `T` implement `IComparable`.  Is there another way?  I was thinking there could be another parameter to methods like `ShouldBeGreaterThan<T>`() of `type IComparer<T>` and Shouldly would use that class for the comparison instead of calling `IComparable.Compare()`.  Does that seem like something worth implementing?

``` CSharp
public static void ShouldBeGreaterThan<T>(this T actual, T expected, IComparer<T> comparer, Func<string> customMessage)
{
    // Call Shouldy.Is() and which uses custom comparer
}
```

For now I have my own extension methods like this:

``` CSharp
public static void ShouldBeGreaterThan(this ElementLocation actual, ElementLocation expected, Func<string> customMessage)
{
    actual.Line.ShouldBeGreaterThan(expected.Line, customMessage);
}
```

I end up passing the property I want compared but I don't want to have to implement something like this for every class.

Thoughts?

**Comment by JakeGinnivan** [comment]
This sounds like a useful feature

**Comment by ankurMalhotra** [comment]
Given this a go. Please let me know if any improvements can be made :)

**Comment by eliziario** [comment]
This one also could also be closed

**Comment by JosephWoodward** [comment]
Thanks again @eliziario
