### ISSUE TITLE
ShouldHaveSingleItem()

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#365]
I often have this in my code:

```
var list = ...
list.Count.ShouldBe(1);
var item = list[0]; // or list.Single();
item.Foo.ShouldBe("Bar");
```

I would like a shouldly assertion:

```
var item = list.ShouldHaveSingleItem();
item.Foo.ShouldBe("Bar");
```

The important thing is the ShouldHaveSingleItem method should return the single item.

**Comment by JosephWoodward** [comment]
Thanks for the pull request @ssiko. I've just posted a question.

**Comment by ssiko** [comment]
@JosephWoodward I pushed another commit to my PR related to your question. I fixed that unnecessary null check in a couple other places as well. Also, updated ```ShouldBeEmpty()``` to use ```IEnumerable.Any()``` for consistency with ```ShouldNotBeEmpty()```.

**Comment by JosephWoodward** [comment]
Thanks for the PR and fixing the other null checks @ssiko

**Comment by ssiko** [comment]
@JosephWoodward No problem, hit me up if I can help with anything else. That was my first pull request for an open source contribution, so thanks for merging. Your tool has been useful, so was glad to get involved.

**Comment by JosephWoodward** [comment]
Oh, wow. Awesome! Glad we were your first open source contribution! Shouldly was actually my first too :) You're always welcome to pick up anything else whenever you have time.
