### ISSUE TITLE
Not compatible with UAP,Version=v10.0.

### ISSUE THREAD

**Issue by vbandi** [shouldly/shouldly#366]
The library is awesome, but it is not compatible with Universal Windows Platform (UWP). Since UWP is the way forward for Windows Store apps, it'd be great to have Shouldly work with such apps.

**Comment by mountain65** [comment]
Hi vbandi,  can you explain in what way the library is not compatible? Shouldly is meant for Unit Test projects and therefore probably never linked to production code. I myself do not know much about UWP yet, so please enlighten me/us!

**Comment by JakeGinnivan** [comment]
The 2.7.0-beta should support UWP, let me know if that works for you.

**Comment by JakeGinnivan** [comment]
@mountain65 UWP doesn't run the full .net framework, shouldly only targeted .net 3.5 and 4.0. The beta of 2.7.0 is a PCL library so should work for .net core, uwp and others.

**Comment by ZodmanPerth** [comment]
FYI: I've just tried installing every version down from the current (2.8.2); the most current version working with my UWP project is 2.7.0.

**Comment by SimonCropp** [comment]
version 4 will support .NETStandard 1.3 and up which includes UWP 10.0
