### ISSUE TITLE
Some of the tests in Shouldly.Tests will fail on 'da-DK' culture

### ISSUE THREAD

**Issue by maxild** [shouldly/shouldly#367]
Hi,

This is a classic:-) 

I have all tests pass under 'en-US', but 15+ tests fail under 'da-DK'. This is not a 'biggie' (production code is working, test code is not culture tolerant) because failures are due to assertions about numeric values, and failures are due to "3.14" and "3,14" both being text representations of approximations of pi (the exact failures are off course different but uninteresting per se).

I can fork and change the relevant tests to use scoped culture defined by the test (not the machine/OS). 

I normally use something like

```
public class CurrentCultureScope : IDisposable
    {
        private readonly CultureInfo _culture;
        private readonly CultureInfo _uiCulture;

        public CurrentCultureScope(string name)
        {
            _culture = Thread.CurrentThread.CurrentCulture;
            _uiCulture = Thread.CurrentThread.CurrentUICulture;
            Thread.CurrentThread.CurrentCulture = new CultureInfo(name);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(name);
        }

        public void Dispose()
        {
            Thread.CurrentThread.CurrentCulture = _culture;
            Thread.CurrentThread.CurrentUICulture = _uiCulture;
        }
    }
```

and setup scopes in the tests like (empty string is invariant culture...btw)

```
using (new CurrentCultureScope(""))
            {
                //....
            }
```

but in the end it adds noise to the tests.

I am new to Shouldly. Have you something in place for setting up culture scopes such that tests will pass for any OS settings.

Thoughts? Should we use InvariantCulture?

Will you accept PR with this noise?

**Comment by JosephWoodward** [comment]
Hi @maxild, thanks for raising this. I'm fairly certain there isn't the ability to set a specific culture and have all tests pass for that culture. At the moment, it's set to `en-US` by default.

It sounds like it'd be a good feature to have, though. Your thoughts @JakeGinnivan ?

**Comment by maxild** [comment]
I don't think you have set the culture to 'en-US' anywhere in your test code. This is an OS setting (called 'system locale' in native code).

But you have a few tests where you setup the culture in the 'arrange' part, but you are doing it the wrong [way](https://github.com/shouldly/shouldly/blob/master/src/DocumentationExamples/ShouldBeExamples.cs#L44).

You should use an IDisposable scope like the one above.

I will be glad to fork and try out Shouldly on a project of mine. I could fix these minor issues and send you a PR from the fixing/feature branch.

**Comment by maxild** [comment]
Do you guys now if you can define the (OS) 'system locale' on the VM that appveyor spins up?

**Comment by maxild** [comment]
You can change it in windows without a reboot....and it is called 'user locale' btw...my mistake.

Changing the system locale requires a reboot, but it is the user locale that defines the default culture in .NET 

(and there is a thread locale too, so this is not exactly 100 percent correct...but you get the idea)

**Comment by JakeGinnivan** [comment]
This would be nice to fix, anyone want to submit a PR to fix this?

**Comment by JakeGinnivan** [comment]
Id prefer a code fix, otherwise if we just fix appveyor then people who clone the codebase can hit the issue

**Comment by maxild** [comment]
Agree...test code should be OS/platform/culture ignorant (work for both local and appveyor builds)...hole point of this issue :smile: 

I was just guessing how to control OS settings on the WM spinned up by the appveyor service... 

The fix is trivial. I will send you PR next week, where I have some spare time...

**Comment by JosephWoodward** [comment]
Would be great to get this fix sorted. Have you been able to make any progress on it @maxild ?

**Comment by rasmeta** [comment]
I know that the issue is a bit old, but I ran into this as well on machine with pl-PL culture. Did some digging and apparently there's been an ongoing discussion [on xunit](https://github.com/xunit/xunit/issues/1605) lately, resulting in [this issue](https://github.com/xunit/xunit/issues/1605) being created.

Assigning culture explicitly before the test is ran does the trick (as @maxild showed [above](https://github.com/shouldly/shouldly/issues/367#issuecomment-195333738), but I feel like it would be nice to have it embedded i.e. into the `Fact` attribute just to have it clean.

Let me know what you think about it. I was looking into contributing and just came across this one - looks like a good thing to get straight. 😉
