### ISSUE TITLE
Can I have a bit of extensibility?

### ISSUE THREAD

**Issue by xoposhiy** [shouldly/shouldly#369]
One can't create new shouldly-like extension methods with all that awesome error messages, because all useful classes are internal :(

It would be great if you make your library a bit more extension friendly.

**Comment by JakeGinnivan** [comment]
The issue has been that we keep changing the internal APIs and if we make them public they become part of the public API. 2.7.0 actually used this to keep it as a minor version bump rather than a major, even though lots of internals have changed.

That said, I hear you and I would love to enable this..

**Comment by xoposhiy** [comment]
Actually you don't need to make class internal to remove them from so called "public API".
Instead you can move all internal classes to namespace named something like "Shouldly.UnstableInternals.NoSupportGuarantee" and make all the classes public. After this change, one can choose himself use this unstable API or not.  Maybe somebody is ready to update his code after every major change of Shouldly. Why did you decided for him?

**Comment by JakeGinnivan** [comment]
@xoposhiy fair enough. Will look at opening things up :)

**Comment by asgerhallas** [comment]
@JakeGinnivan would really appreciate this too :)

Things like ShouldlyAssertionContext, ExpectedActualShouldlyMessage and the AssertAwesomely() methods would be really nice to make som special case ShouldBe extensions with same good messages.

**Comment by JosephWoodward** [comment]
@asgerhallas Happy to do this, the more extensibility the better.

**Comment by SimonCropp** [comment]
@asgerhallas  @xoposhiy how does this look https://github.com/shouldly/shouldly/pull/640?
