### ISSUE TITLE
Object graph comparison - ShouldbeEquivalentTo

### ISSUE THREAD

**Issue by DouglasHammon** [shouldly/shouldly#370]
When dealing with projects that use DTO's or objects with similar fields and properties, it would be nice if shouldly had a the ability to compare the exposed members of two different objects/types. 

FluentAssertions has this feature: ShouldbeEquivalentTo

More info can be found here: [https://github.com/dennisdoomen/fluentassertions/wiki#object-graph-comparison](https://github.com/dennisdoomen/fluentassertions/wiki#object-graph-comparison)

I'm really enjoying using shouldly, keep up the great work.

**Comment by JosephWoodward** [comment]
Sounds like a great feature to me. Interested in others' thoughts.

**Comment by Treyphor** [comment]
I would also like to see this feature implemented :)
