### ISSUE TITLE
shouldly should show more details when asserting DateTime

### ISSUE THREAD

**Issue by SebastianWojciechowski** [shouldly/shouldly#371]
Hi,

shouldly should show more details when asserting DateTime.
Example:

> **Assert.Equal**(result.ShortenDate, newUrlItem_ACT.ShortenDate);

```
Result Message:	
Assert.Equal() Failure
Expected: 2016-04-12T22:00:14.2100000
Actual:   2016-04-12T22:00:14.2096734Z
```

above you can see the difference: 2100000 and 2096734Z.
Below it is not shown and it looks like everything is ok..

> result.ShortenDate.**ShouldBe**(newUrlItem_ACT.ShortenDate);

```
Result Message:	
result.ShortenDate
    should be
12/04/2016 22:02:21
    but was
12/04/2016 22:02:21
```

**Comment by JosephWoodward** [comment]
Further precision sounds like a good idea to me. A pull request for this would be more than welcome. Thoughts @JakeGinnivan ?

**Comment by JosephWoodward** [comment]
Thanks for the prompt PR for this @SebastianWojciechowski - sorry it's taken so long for me to get around to it. I think we should keep the original time format (as it's more readable), but add the additional precision using a [custom date](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx#fffSpecifier) formatter so it's formatted like `12/04/2016 22:02:21.018`.

**Comment by SebastianWojciechowski** [comment]
@JosephWoodward my PR uses "o" for DateTime format, so it would look like this:

`2009-06-15T13:45:30.0000000`

this is what xUnit uses and I think that this is a very good idea.

It preserves the date and time values along with kind and what is even more important developers will be able to create DateTime object by DateTime.Parse and emitted string to for example debug unit test.

We have to remember that and more applications are written to support many different time zones so additional information about it in error message would be additional plus.

```
The example displays the following output:
    6/15/2009 1:45:30 PM (Unspecified) --> 2009-06-15T13:45:30.0000000
    6/15/2009 1:45:30 PM (Utc) --> 2009-06-15T13:45:30.0000000Z
    6/15/2009 1:45:30 PM (Local) --> 2009-06-15T13:45:30.0000000-07:00
    
    6/15/2009 1:45:30 PM -07:00 --> 2009-06-15T13:45:30.0000000-07:00
```
More about the "o" can be found here:
https://msdn.microsoft.com/library/az4se3k1(v=vs.110).aspx#Roundtrip

**Comment by JosephWoodward** [comment]
You've raised a very good point. Thanks for the PR, I'll merge it now.
