### ISSUE TITLE
ShouldMatchApproved fails on Mono

### ISSUE THREAD

**Issue by asbjornu** [shouldly/shouldly#376]
Since `ShouldMatchApproved` is dependent on source information (which I assume it gets from `.pdb` files on Windows), the method fails on Mono since no `.pdb` files exist. Mono has `.mdb` files instead. Since [Cecil supports both formats](https://github.com/jbevain/cecil/wiki/Debug-symbols), perhaps it's not a huge job to get the Mono support up to speed?

These are all baseless assumptions, so please correct me if I'm wrong. :smiley:

**Comment by van800** [comment]
Mono 5.x generates Portable PDB (.pdb) debug files instead of Mono’s MDB (.mdb) format.

**Comment by JosephWoodward** [comment]
Oh really? That's good to know, would be nice to get this one working for Mono.

**Comment by JosephWoodward** [comment]
Now this feature targets .NET Standard this should work so closing this issue.
