### ISSUE TITLE
Type initialization for KnownDiffTools fails

### ISSUE THREAD

**Issue by alexandernyquist** [shouldly/shouldly#377]
I have an issue where Shouldly are throwing a `TypeInitializationException` at (seemingly) random times. The `TypeInitializationException` wraps a `ArgumentException`: `Illegal characters in path`.

See full stack trace: https://gist.github.com/alexandernyquist/1a533add1af0466a72f07fa8a7a2cd90

* The issue appears under R# test runner and NUnit Console
* I'm on a Swedish locale where `Path.InvalidPathChars` is `"<>| "`
* It happens on both 2.7.0 and 2.7.0-beta0003

I have not tested this in a stand alone application (the time is just not there right now), but I thought I'd share this since I cannot see why my code should have anything to do with this.

I will look into this more deeply next week if anyone does not have any idea as to why this happens.

**Comment by JakeGinnivan** [comment]
Id imagine this is to do with the different locale and maybe the compiler has slightly different output for anonymous classes. 

Have a look at `FirstNonShouldlyMethodFinder` which specifies how to find the method. In particular the regex looking for anon methods/classes.

**Comment by mariusGundersen** [comment]
I had the same issue, and found out that in my path I had quotes (`"`) around one of the paths. Quotes cannot be part of the path according to [Path.GetInvalidPathCharacters](https://msdn.microsoft.com/en-us/library/system.io.path.getinvalidpathchars%28v=vs.110%29.aspx). Maybe `GetFullPath` could strip quotes from the beginning and end of each string after splitting on `;`? Or if you stumble upon this issue, remove the quotes around your path entries.

**Comment by alexandernyquist** [comment]
Yep - that was it. I have an entry in my path that contains quotes. What do you think is a viable solution? I could provide a fix that trims `"` but that only covers this specific case. Maybe a more clear exception message?

**Comment by mariusGundersen** [comment]
Why_not_both.gif? 

A better error message is really needed here, I had to do quite a lot of spelunking through the stack trace to figure out the issue. It should probably catch the `ArgumentException` thrown by `Path.Combine` and either return a better error message (with the actual path variable that is the issue) or just swallow the error message and allow the other paths to be used.

**Comment by RahmanM** [comment]
I just got the same issue in one of my projects. Although some of the tests are working some are failing. The only thing has happened is I have copied the projects from one machine to another. I am still not sure what the path issue thing is? Anyone?
