### ISSUE TITLE
.NET Core version?

### ISSUE THREAD

**Issue by ivaylokenov** [shouldly/shouldly#379]
Hi, do you plan to write a .NET Core version of this library?

**Comment by JakeGinnivan** [comment]
Yep

2.7.0 supported rc1, will add support for rc2 very shortly

**Comment by JosephWoodward** [comment]
@JakeGinnivan Really interested to see what needs to be done to do do this. I was keen to make a start on this but the lack of project.json (and lack of experience upgrading a class library to .NET Core) had me stumped.

**Comment by JosephWoodward** [comment]
Managed to get a little further in this [pull request](https://github.com/shouldly/shouldly/pull/384). As this is new to me I'd appreciate a thorough check as I'm probably missing something!

**Comment by JosephWoodward** [comment]
Version 2.8.0 is now .NET Core RC2/NetStandard1.3 compatible.
