### ISSUE TITLE
Feature request: multilanguage implementation

### ISSUE THREAD

**Issue by totpero** [shouldly/shouldly#381]
Hi,

Can you implement feature to translate string returned from `ShouldlyMessageGenerator->GenerateErrorMessage` ?
This feature will be nice, support for multilanguage.

**Comment by JakeGinnivan** [comment]
Happy to receive a PR which kicks this off and suggests a structure and a testing approach.

**Comment by dennisroche** [comment]
I thought https://github.com/Humanizr/Humanizer/issues/59 solved multilingual nuget packaging nicely using satellite assemblies.

**Comment by davidrevoledo** [comment]
@JakeGinnivan I can take this task if you are agree, do you want to discuss how to implement it ?

**Comment by SimonCropp** [comment]
IMO this is not worth the effort (and resulting complexity). @JosephWoodward  thoughts?

**Comment by AaqibAhamed** [comment]
Can I take this?

**Comment by SimonCropp** [comment]
@JosephWoodward @jnm2 thoughts?

**Comment by jnm2** [comment]
It has to be something that is not a burden to extend over time.

**Comment by JosephWoodward** [comment]
> IMO this is not worth the effort (and resulting complexity).

I'm inclined to agree. This has been open since 2016 and hasn't received much attention as a feature.

**Comment by JosephWoodward** [comment]
I think we can close this issue off if we've agreed we're not going to do it.
