### ISSUE TITLE
Enhance no diff tool message

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#387]
When throwing `Cannot find a difftool to use, please open an issue or a PR to add support for your difftool.`

We should dump a list of environmental variables available and suggest that if running on the build server to prevent showing diff if a variable is present.

**Comment by dennisroche** [comment]
:+1:

**Comment by SimonCropp** [comment]
given the next version will support significantly more tools https://github.com/VerifyTests/DiffEngine#supported-tools i will close this
