### ISSUE TITLE
ShouldMatchApproved opens multiple instances of difftool

### ISSUE THREAD

**Issue by dennisroche** [shouldly/shouldly#388]
Recently had 75+ instances of Beyond Compare open as all the tests failed.

Beyond Compare and KDiff both support opening multiple files or directory comparison.

I'm not sure how I would implement this yet... but it would be nice if diffs are opened at the end of the test run.

**Comment by dennisroche** [comment]
Two possible options.

1. `AppDomain.Unload` to determine when the tests have finished.
2. Limit the number of diffs opened, e.g. 5.

**Comment by SimonCropp** [comment]
@JosephWoodward FWIW this is how it is handled in diffengine https://github.com/VerifyTests/DiffEngine/blob/master/docs/diff-tool.md#maxinstancestolaunch

**Comment by dennisroche** [comment]
`DiffRunner.MaxInstancesToLaunch(5);` helps solve the problem without having to mess about with `AppDomain.Unload`

Happy to close.

**Comment by dennisroche** [comment]
🤦‍♂️ that was in another project. 

yes, we should copy that approach 😀
