### ISSUE TITLE
ShouldAllBe does not show the element predicate correctly for `is` operator

### ISSUE THREAD

**Issue by alex-fomin** [shouldly/shouldly#389]
The following snippet produce incorrect assertion message:

			batchCommand.Commands.ShouldAllBe(command=>command is CreateResourceCommand);

```
Shouldly.ShouldAssertException : batchCommand.Commands
    should satisfy the condition
command
    but
[Tp.Rest.Commands.UpdateResourceCommand (22668405), Tp.Rest.Commands.UpdateResourceCommand (29839228)]
    do not
```

I expect a `command is CreateResourceCommand` as an assertion message

**Comment by JosephWoodward** [comment]
Just realised I'd not thanked you for raising this @alex-fomin! @ssiko has just submitted a PR to fix it.
