### ISSUE TITLE
More information for Should.Throw

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#391]
It would be good to show inner exceptions. For instance in https://github.com/TestStack/TestStack.BDDfy/pull/224/files Should.Throw was not enough to diagnose the issue so had to fall back to try/catch

**Comment by SimonCropp** [comment]
@JakeGinnivan still think this is necessary?

**Comment by JakeGinnivan** [comment]
Honestly no idea, happy to close
