### ISSUE TITLE
Shouldly for net451

### ISSUE THREAD

**Issue by Alterling** [shouldly/shouldly#394]
Please add dedicated net451 target without CallerMemberNamePolyfill because when I'm using net40 Shouldly with net451 project I'm getting warnings like

CSC : warning CS1685: The predefined type 'System.Runtime.CompilerServices.CallerMemberNameAttribute' is defined in multiple assemblies in the global alias; using definition from 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\mscorlib.dll'

**Comment by JakeGinnivan** [comment]
Hey, 

Did you want to submit a pull request for this?

**Comment by JakeGinnivan** [comment]
Thanks for the PR. Released in https://github.com/shouldly/shouldly/releases/tag/v2.8.2

**Comment by tgmayfield** [comment]
Shouldn't this have been for .NET 4.5? The same compiler warnings show up, and a 4.5.1 or later project would reference the 4.5 library.
