### ISSUE TITLE
ShouldBe produces a false positive on null collections using ? safe navigation

### ISSUE THREAD

**Issue by SwishWez** [shouldly/shouldly#400]
This occurs when using ShouldBe to check equality of a potentially null collection for an expected value via safe navigation.

E.g.
var expectedCollection = new List<string> { "Expected" };

(Act)

// Incorrectly passes when Result is null
lookup.Result?.SomeCollection.ShouldBe(expectedCollection);

// Adding brackets causes the test to correctly fail when Result is null
(lookup.Result?.SomeCollection).ShouldBe(expectedCollection);

**Comment by JosephWoodward** [comment]
Thanks for raising this @SwishWez, I'll take a look at it. In the mean time we always welcome and actively encourage community contributions so please feel free to submit a pull request.

**Comment by JosephWoodward** [comment]
You're right, I've included a failing test to demonstrate the issue:

```c#
public class Lookup { public Result Result { get; set; } }

public class Result { public List<string> SomeCollection { get; set; } }

public class TempTests
{
    [Fact]
    public void Test()
    {
        var expectedCollection = new List<string> { "Expected" };
        var lookup = new Lookup
        {
            Result = null
        };

        // Incorrectly passes when Result is null
        lookup.Result?.SomeCollection.ShouldBe(expectedCollection);
    }
}
```

Once again, thanks for raising this.

**Comment by JustinPealing** [comment]
Is there anything that can be done about this? My understanding of the null-conditional operator is that the `ShouldBe` extension method will never be called if `Result` is null. Another way of writing this test is would be:

```
if (lookup.Result != null)
{
    lookup.Result.SomeCollection.ShouldBe(expectedCollection);
}
```

Which makes it a lot more obvious why this won't work as expected.

**Comment by JakeGinnivan** [comment]
> My understanding of the null-conditional operator is that the ShouldBe extension method will never be called if Result is null

Yep, nothing we can do about this, we simply do not get called by the compiler when Result is null. I guess this is a downside of the extension method approach, afaik there is nothing we can do about this. We possibly could create a Roslyn analyser which will identity this issue and flag it as an issue?

**Comment by JosephWoodward** [comment]
> My understanding of the null-conditional operator is that the ShouldBe extension method will never be called if Result is null.

Of course, I didn't even stop to think about that (posted it in haste as lunch break was coming to an end).

> Roslyn analyser which will identity this issue and flag it as an issue?

As cool as that would be, do we want to go down that route? Where do we stop when it comes to showing warnings about language issues such as this? (I'm not saying it's a bad idea.)

**Comment by JakeGinnivan** [comment]
> As cool as that would be, do we want to go down that route? Where do we stop when it comes to showing warnings about language issues such as this? (I'm not saying it's a bad idea.)

Not sure, but that is the only way I can think of that we can sort this. But yeah, at some point it is up to the test author to ensure the test fails when it should

**Comment by JosephWoodward** [comment]
> Not sure, but that is the only way I can think of that we can sort this. But yeah, at some point it is up to the test author to ensure the test fails when it should

Yeah, my thoughts exactly. I say we leave it as blocked/won't fix personally.

**Comment by JakeGinnivan** [comment]
👍 

@SwishWez going to close this issue out. If you can think of any other way to resolve then please continue the discussion
