### ISSUE TITLE
Migrate the contribution guidelines to a CONTRIBUTING file

### ISSUE THREAD

**Issue by tdwright** [shouldly/shouldly#405]
GitHub supports special files for guidelines for contributors; a bit like the way it treats README files as special. See: https://help.github.com/articles/setting-guidelines-for-repository-contributors/ and https://github.com/blog/1184-contributing-guidelines

Should we move [the contributing section of the README](https://github.com/shouldly/shouldly#contributing) to it's own CONTRIBUTING file?

**Comment by JosephWoodward** [comment]
Sounds like a good idea to me. Happy to have a PR for it!

**Comment by JosephWoodward** [comment]
Just noticed there is already a PR for it x)
