### ISSUE TITLE
Display detailed diff for string comparisons when calling ShouldBe

### ISSUE THREAD

**Issue by xerxesb** [shouldly/shouldly#41]
This task is to enhance the message reporting of ShouldBe(string) method to show more information about the string and where it differed from the target.

The basic idea (from my recollection) was taken from Phil Haack's blogpost on comparing strings un unit tests. (http://haacked.com/archive/2012/01/14/comparing-strings-in-unit-tests.aspx)

He has a reference implementation which (with some love) should slip into Shouldly. (https://gist.github.com/1610603)

This task will possibly require doing the refactor to the ShouldlyMessage/ShouldlyMessageGenerator i've been putting off for some time (ie: All messages should be routed through an appropriate generator and the ShouldlyMessage shouldn't do any message output).

**Comment by JakeGinnivan** [comment]
Done, thanks to @chaitanyagurrapu
