### ISSUE TITLE
NullReferenceException when using ShouldNotHaveFlag

### ISSUE THREAD

**Issue by niklaskallander** [shouldly/shouldly#415]
Hi,

I'm getting a NullReferenceException when using the ShouldNotHaveFlag assertion. Nothing is null on the specific code-line where I use it. However, the enum value does in fact have the flag I'm expecting it **not** to have (if that helps).

**Shouldly stacktrace:**
```
at Shouldly.Internals.ActualCodeTextGetter.ParseStackTrace(StackTrace trace)
at Shouldly.Internals.ActualCodeTextGetter.GetCodeText(Object actual, StackTrace stackTrace)
at Shouldly.ShouldlyAssertionContext..ctor(String shouldlyMethod, Object expected, Object actual, StackTrace stackTrace)
at Shouldly.ExpectedActualShouldlyMessage..ctor(Object expected, Object actual, Func`1 customMessage, String shouldlyMethod)
at Shouldly.ShouldlyExtensionMethods.ShouldHaveEnumExtensions.ShouldNotHaveFlag(Enum actual, Enum expectedFlag, Func`1 customMessage)
at Shouldly.ShouldlyExtensionMethods.ShouldHaveEnumExtensions.ShouldNotHaveFlag(Enum actual, Enum expectedFlag)
```

**Code for reproducing the issue:**
```
[Flags]
public enum ReproEnum
{
    Value1 = 1,
    Value2 = 2,
    Value3 = 4,
    All = Value1 | Value2 | Value3
}

[Test]
public void Repro()
{
    var values = ReproEnum.All;

    values.ShouldNotHaveFlag(ReproEnum.Value2);
}
```

Thanks!

**Comment by JosephWoodward** [comment]
Thanks for reporting this, we always welcome pull requests so if you do fancy giving it ago it would be most appreciated.

**Comment by niklaskallander** [comment]
I'll have a look-see, no promises! (:

**Comment by niklaskallander** [comment]
I've created a pull request for this: https://github.com/shouldly/shouldly/pull/416, but this will only fix the issue for my particular case/scenario. If the ShouldyMethods attribute is missing anywhere else those assertions would also fail (if the assertions won't pass). 

However, I do believe fixing ActualCodeTextGetter.ParseStackTrace should be a separate issue/pr?

**Comment by niklaskallander** [comment]
So, obviously, my tiny (and in my eyes, innocent) code-change caused a cascade of test failures. Where did I go wrong? (:

**Comment by niklaskallander** [comment]
As far as I can tell, almost all assertions defined in Shouldly uses `ActualCodeTextGetter.ParseStackTrace` (indirectly or otherwise) to find the "test method" (I think) for a failing assertion. And, unless any of the methods or classes (found in the call stack) are marked with a `ShouldyMethods` attribute, you will get a `NullReferenceException` because eventually you'll run out of frames to iterate over.

Is there something I'm not seeing?

**Comment by niklaskallander** [comment]
I tried another fix for this (which doesn't seem to break any tests not already broken in a clean checkout):
https://github.com/niklaskallander/shouldly/commit/c0a2e065bdcb2b4cfd5cc2713b337ee849f23f4a

However, I'm not sure that is the "better" approach?

**Comment by niklaskallander** [comment]
@JosephWoodward Any input on this would be appreciated, thanks! (:

**Comment by davidrevoledo** [comment]
@JosephWoodward Is this bug closed ?

**Comment by sasanknvs** [comment]
@JosephWoodward is this issue closed ?

**Comment by JosephWoodward** [comment]
Yes, it should be closed, thanks for pointing that out.
