### ISSUE TITLE
Enumerable.ShouldBeOfTypes()

### ISSUE THREAD

**Issue by Pondidum** [shouldly/shouldly#424]
Would there be interest in a pull request to support this scenario:

```csharp
var events = new[] { new AddedEvent(), new RemovedEvent() };

events.ShouldBeOfTypes(new[] { typeof(AddedEvent), typeof(RemovedEvent) });
```

I would be interested in implementing this either way, as it is something I would find very useful for testing EventSourced aggregates.

If there is interest, a couple of design questions:

* What to call the method (I just pluralised `.ShouldBeOfType`)
* Support generic variation (`events.ShouldBeOfTypes<AddedEvent, RemovedEvent>()`
  * and if so, to how many generics should I support?
* For non-generic, should the `expected` parameter be a `params Type[] expectedTypes`, or `IEnumerable<Type> expectedTypes` (or something else)?

**Comment by dbarwikowski** [comment]
What should happen for this scenario:

var events = new[] { new RemovedEvent(), new AddedEvent() };

events.ShouldBeOfTypes(new[] { typeof(AddedEvent), typeof(RemovedEvent) });

Assertion should fail or pass?

**Comment by Pondidum** [comment]
Fail in my opinion, as the types are in the wrong order.
Perhaps supporting the `ignoreOrder` parameter which is used on other collection methods too?

**Comment by dbarwikowski** [comment]
It depends what exatly mean ShouldBeOfTypes:
- IEnumerable contains elements of specified Types
```C#
var events = new[] { new RemovedEvent(), new RemovedEvent() };
events.ShouldBeOfTypes(new[] { typeof(RemovedEvent) }); //true?
```

This is confusing. Actually what you are trying to do is checking if both collections have the same elements, and I think you should use `ShouldBe` for that

**Comment by Pondidum** [comment]
The basic reason was to remove the need to do `.Select(e => e.GetType())` on the assertion.

I use this for testing the events emitted from eventsourced aggregates - I am usually checking for a series of events, but not what the event's content is, e.g. 
```
events.ShouldBeTypes(new[] { 
    typeof(BasketCreated),
    typeof(ProductAdded),
    typeof(ProductRemoved),
    typeof(ProductAdded)
})```

**Comment by dbarwikowski** [comment]
So maybe this will be more general solution?
```C#
events.ShouldBe(new[] {
    typeof(BasketCreated),
    typeof(ProductAdded),
    typeof(ProductRemoved),
    typeof(ProductAdded)
}, (e) => typeof(e));
```
Where `(e) => typeof(e)` will be executed on each element of `events`

**Comment by Pondidum** [comment]
That would work well I think - it doesn't look like it will clash with other `ShouldBe` extensions either.

Would this be something I can implement and pull-request?

**Comment by dbarwikowski** [comment]
I think this is the purpose of having open-sourced project. There is:
```C#
        public static void ShouldBe<T>(this T actual, T expected, [InstantHandleAttribute] Func<string> customMessage);
```
So, I'm not sure if it will not break anything... Maybe we shoud ask @JakeGinnivan

**Comment by JakeGinnivan** [comment]
There is the risk of overloading ShouldBe too much. 

I always want to raise the question about using the expressiveness of Linq and shouldlys already good error reporting to do something like

```
var events = new[] { new AddedEvent(), new RemovedEvent() };
events.Select(e => e.GetType()).ShouldBe(typeof(AddedEvent), typeof(RemovedEvent) })
```

If we were to add an extension I think I like @Pondidum's solution, but I would make it a params so you can go

```
events.ShouldBeTypes(
    typeof(BasketCreated),
    typeof(ProductAdded),
    typeof(ProductRemoved),
    typeof(ProductAdded)
)
```

**Comment by JakeGinnivan** [comment]
But unsure it's more expressive than `events.Select(e => e.GetType()).ShouldBe(typeof(AddedEvent), typeof(RemovedEvent) })`

**Comment by EddieGarmon** [comment]
I just submitted a PR #481 with the overloads for IEqualityComparer<T>, and here you could create your own comparer that just looked at types. This would accomplish this and more.
