### ISSUE TITLE
null ShouldBeAssignableTo both, Nullable<> and reference types

### ISSUE THREAD

**Issue by 6bee** [shouldly/shouldly#427]
While I expect `null` to be assignable to both, a nullable value type and any reference type, shouldly claims it's not.

assertion
```
string value = null;
value.ShouldBeAssignableTo<string>();
```
results in
```
Message: Shouldly.ShouldAssertException : value
    should be assignable to
System.String
    but was
null
```

**Comment by JosephWoodward** [comment]
Thank you for reporting this @6bee

**Comment by JosephWoodward** [comment]
Had a bit of spare time so I've made a start on fixing this.

**Comment by JosephWoodward** [comment]
Here's the [fix,](https://github.com/shouldly/shouldly/pull/428) it could do with a review.
