### ISSUE TITLE
Migrate from project.json to .csproj

### ISSUE THREAD

**Issue by JosephWoodward** [shouldly/shouldly#429]
Shouldly's currently still using the old project.json format so we're going to need to migrate to .csproj soon before the migration tooling goes away making things more difficult.

I'm happy to pick this up and will make a start in the next few days.

**Comment by JosephWoodward** [comment]
[Here](https://github.com/shouldly/shouldly/pull/432) is the initial working PR/branch for the tooling migration.

**Comment by dennisroche** [comment]
@JosephWoodward are you still working on this? happy to jump in and pick up the last pieces (including getting build-ci working - there are a few prickly pieces around that)

**Comment by JosephWoodward** [comment]
Hi @dennisroche, yes I am still working on it. I've made good progress but definitely running into issues and would always welcome additional help. I have a branch [here](https://github.com/shouldly/shouldly/tree/ToolingMigration) I've been working from.

**Comment by dennisroche** [comment]
@JosephWoodward ha, i didn't get notification of reply. i'll take a look. once this done, i would be keen to start on the .NET Core 2 port as really want `ShouldMatchApproved` back

**Comment by dennisroche** [comment]
@JosephWoodward this looks like the Packaging issue with the CI build, https://github.com/Microsoft/msbuild/issues/1333

**Comment by JosephWoodward** [comment]
This migration has now been completed, so I will close this ticket.
