### ISSUE TITLE
v2.8.3 is not released on NuGet

### ISSUE THREAD

**Issue by Piedone** [shouldly/shouldly#434]
It seems the new version is missing from NuGet, please update.

**Comment by JosephWoodward** [comment]
Hi, @Piedone 

Yeah, there are complications with the build/publish script that we're looking into, hopefully should have 2.8.3 published shortly - sorry for the wait.

**Comment by Piedone** [comment]
I see, thanks for the update!

**Comment by Roemer** [comment]
Unfortunately it is still not on nuget. Is there an ETA when this will be the case?

**Comment by JosephWoodward** [comment]
Hi @Roemer 

[2.8.3 is now available on NuGet](https://www.nuget.org/packages/Shouldly/2.8.3), thanks for being patient.

**Comment by Piedone** [comment]
Great, thank you!

**Comment by JosephWoodward** [comment]
No problem, the next one shouldn't take so long to appear in NuGet! :)
