### ISSUE TITLE
Shouldly.dll not signed (netstandard1.3)

### ISSUE THREAD

**Issue by AndyGerlicher** [shouldly/shouldly#449]
Using the latest NuGet package (2.8.3):
```
>sn -vf lib\net451\Shouldly.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'lib\net451\Shouldly.dll' is valid

>sn -vf lib\netstandard1.3\Shouldly.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

lib\netstandard1.3\Shouldly.dll does not represent a strongly named assembly
```

Looks like signing was added a long time ago (#40), but the netstandard1.3 dll is not signed.

We're about to adopt Shouldly for MSBuild (Microsoft/msbuild#2250) and I'd rather not have to suppress that compile warning, especially if it's by mistake. Is this by design or something you're aware of?

**Comment by JosephWoodward** [comment]
Hi @AndyGerlicher, thanks for making us aware of this issue, @slang25 has just contributed a fix for it.

**Comment by jeffkl** [comment]
@JosephWoodward can we please get a release with the signed assembly?  I'd like to merge my PR https://github.com/Microsoft/msbuild/pull/2250

**Comment by JosephWoodward** [comment]
@jeffkl Will do, should get it out today 👍

**Comment by JosephWoodward** [comment]
@jeffkl A pre-release of Shouldly 3.0 is now available on NuGet and can be downloaded [here], the reason it's a 3.0 and a major version bump is because we removed support for .NET 3.5; other than that it's stable.

**Comment by JosephWoodward** [comment]
I'll close this issue, if there are any problems then do feel free to post them again and I'd be more than happy to reopen it :)

**Comment by AndyGerlicher** [comment]
Thanks!! We confirmed it's signed and merged our PR :)

**Comment by JosephWoodward** [comment]
@AndyGerlicher Great to hear! :)
