### ISSUE TITLE
Addition of IEqualityComparer to some methods to allow custom comparisons

### ISSUE THREAD

**Issue by whortleberrybearer** [shouldly/shouldly#453]
Would it be useful / suitable to allow an `IEqualityComparer<T>` instance to be passed into some methods to allow the equality checks to be customised?  E.g.

`public static void ShouldBe<T>(this T actual, T expected, IEqualityComparer<T> comparer) 
        {
            …
        }`

It’s similar to what has already been put forward in #364.

I have had a situation recently where I needed to compare 2 object, but overriding the `Equals` method was not suitable and I didn’t want to have to write many `x.Prop1.ShouldBe(y.Prop1); x.Prop2.ShouldBe(y.Prop2);` as it would have been a real maintenance pain.  I ended up with a comparison object that and just asserting that was true, e.g. `comparer.Equals(x, y).ShouldBeTrue()` which works, but lost the context in the failure message.  Allowing a comparer object to be passed into the ShouldBe method would allow the context to be retained, e.g. `x.ShouldBe(y, comparer)`.

I have noticed internally, `Is.Equal` already takes an `IEqualityComparer<T>` parameter, so much of the internal functionality is already in place, it would just need some new extension methods to allow the comparer to be passed it.

I’m thinking it would only be suitable in a few places, such as the generic `T` and `IEnumerable<T>` `ShouldBe` and `ShouldNotBe` methods.

Any thoughts?

**Comment by EddieGarmon** [comment]
PR #481 supports this.

**Comment by TAGC** [comment]
As of ten seconds ago, I'd really like this too.

**Comment by JakenVeina** [comment]
Also, an overload that just takes `Func<T, T, bool>` would be nice too.
