### ISSUE TITLE
Logo ideas

### ISSUE THREAD

**Issue by JosephWoodward** [shouldly/shouldly#455]
Shouldly's current brand is the star:

![68747470733a2f2f7261772e6769746875622e636f6d2f73686f756c646c792f73686f756c646c792f6d61737465722f7061636b6167655f69636f6e2e706e67](https://user-images.githubusercontent.com/1237341/28947803-b4dcfa90-78a9-11e7-945c-0e14ded1a59c.png)

However in a bid to give Shouldly more of a presence and image (which will also help draw attention in the NuGet search results) I'd like to open the floor to some logo ideas and/or feedback.

Having had a bit of a play around in Photoshop here are some ideas I've been playing with; I'm thinking the O with the tick would be the smaller version of the icon (NuGet package icon for instance).

Would love some feedback on thoughts, suggestions or other logo options if anyone would like to come up with some ideas.

**Version 1:** (speech bubble to represent the more readable assertion messages)
![shoulder_smaller](https://user-images.githubusercontent.com/1237341/28947894-3afb1684-78aa-11e7-9b41-cfc7c9f157d6.png)

[See more below](https://github.com/shouldly/shouldly/issues/455#issuecomment-320415621), feel free to 👍 the ones you like.

**Comment by slang25** [comment]
It's looks very professional, it's more meaningful than the current logo. I like it 👍

**Comment by JosephWoodward** [comment]
Added a couple of other suggestions

**Comment by JosephWoodward** [comment]
**Version 3:** (using the original star idea, not sure if it works well with the tick)
![shoulder_star](https://user-images.githubusercontent.com/1237341/28993366-86e1531c-79ac-11e7-86ef-056247c3bcb5.png)

**Comment by gep13** [comment]
@JosephWoodward don't think the star works with the tick, it is a bit too busy.

**Comment by JosephWoodward** [comment]
@gep13 I agree, busy is a good way to put it.

**Comment by whortleberrybearer** [comment]
I prefer the O over the speech bubble.  Not sure the speech bubble adds anything to the logo.

**Comment by dcomartin** [comment]
I prefer version 2.  I'm with everyone else, others are too busy with the check mark.

**Comment by lloydjatkinson** [comment]
Version 2 👍

**Comment by MahendraChoudhary** [comment]
Version 2 is looks more appropriate

**Comment by xerxesb** [comment]
I spent 10 minutes thinking about it when I picked that star logo, years ago.

I have no attachment to it - change at will. 👍

**Comment by JosephWoodward** [comment]
Went with version two in the end,, thanks for the input everyone!
