### ISSUE TITLE
ShouldAllBe potential blocking?

### ISSUE THREAD

**Issue by RPM1984** [shouldly/shouldly#458]
We've got an ASP.NET website which uses async/await, and Shouldly for assertions.

We're seeing some slow requests (via AppInsights), and the info shows the thread being 'blocked' on `ShouldAllBe`, specifically the [Compile](https://github.com/shouldly/shouldly/blob/master/src/Shouldly/ShouldlyExtensionMethods/ShouldBeEnumerableTestExtensions.cs#L112) call.

Here's an example from AppInsights Profiler ETL trace:
![image](https://user-images.githubusercontent.com/930343/29552830-3d2e4456-875c-11e7-9264-c43451d66e04.png)

In the screenshot above, 3.2 seconds was spend blocked waiting for `ShouldAllBe` to complete. (reference on what `BLOCKED_TIME` means: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-profiler)

The `GetItemsFromRedisAsync` method looks like this:
```
 keys.ShouldNotBeEmpty();
keys.ShouldAllBe(cacheKey => !string.IsNullOrWhiteSpace(cacheKey));

// go to redis
```

So, it's like the LINQ compilation is getting stuck/blocked? I couldn't replicate with a simple console app thrashing with 1000's of strings, but wondering if anyone here can provide some further guidance?

Thanks!

**Comment by JosephWoodward** [comment]
Thanks for raising this, it's the first we've heard about it; have you been able to reproduce it since posting this?

**Comment by slang25** [comment]
@RPM1984 What version of Shouldly were you using?
You could be hitting this: #439 
This could account for that sort of blocking duration.

**Comment by JosephWoodward** [comment]
That's a good point @stuart-lang 👍

**Comment by slang25** [comment]
That said, I can see little downsides to adding a compilation cache using a static `ConcurrentDictionary<Expression<Func<T, bool>, Func<T, bool>>`

**Comment by RPM1984** [comment]
Yeah, i'm on version 2.8.3 (latest I think?).

**Comment by PureKrome** [comment]
>@RPM1984 What version of Shouldly were you using?
>You could be hitting the issue that was fixed by this: #439

Was the fix pushed up into the Beta3 pre-release?

**Comment by JosephWoodward** [comment]
@PureKrome Yes, that's right.

**Comment by SimonCropp** [comment]
given there is no repro for this, and @RPM1984 has a workaround, and it has been 3 years, i will close for now. happy to revisit if more info becomes avaliable
