### ISSUE TITLE
New assertion: ShouldImply

### ISSUE THREAD

**Issue by TAGC** [shouldly/shouldly#460]
In one of my projects I've defined an `AssertImplies` function that I use in some of my unit tests. This function takes two boolean parameters and asserts that the first implies the second. In propositional logic, this holds for all cases except when the first parameter (the antecedent) is true, and the second (the consequent) is false:

| P     | Q     | P -> Q |
|-------|-------|--------|
| false | false | true   |
| false | true  | true   |
| true  | false | false  |
| true  | true  | true   |

I've defined it in my code like this:

```cs
public static void AssertImplies(bool antecedent, bool consequent) =>
    (consequent || !antecedent).ShouldBeTrue();
```

One of the ways I find this helpful is checking that if two equatable objects are equal, then their hashcodes must also be equal:

```cs
AssertImplies(m1.Equals(m2), m1.GetHashCode() == m2.GetHashCode());
```

It might be nice if Shouldly incorporated this rule for cases like this, I guess with something along the lines of:

```cs
public static void ShouldImply(this bool antecedent, bool consequent) =>
    (consequent || !antecedent).ShouldBeTrue();
```

With this, I could write:

```cs
m1.Equals(m2).ShouldImply(m1.GetHashCode() == m2.GetHashCode());
```

I was planning to do this myself and submit a pull request, but I get dozens of errors trying to run tests after checking out master and at this point I've spent longer trying to figure out how to build Shouldly without issue than I anticipate implementing this feature would take:

![image](https://user-images.githubusercontent.com/1588951/30532160-a467aae2-9c4a-11e7-9b1d-78ad102d11f6.png)

**Comment by TAGC** [comment]
Any update on this? It's been half a year. @JakeGinnivan.

**Comment by TAGC** [comment]
Sorry, think I mentioned an inactive contributor. @JosephWoodward, sorry to bother, you seem active and I'm just looking for closure on this issue (i.e. whether you agree it could be implemented, or closed if not suitable).

**Comment by mattfrear** [comment]
As a random person on the internet who just browsed the Issues list, I don't think this is necessary.

You could perhaps implement it yourself in your own Shouldly.Implies NuGet package, and if that gets popular or a lot of usage then add it into the main Shouldly package.

**Comment by JosephWoodward** [comment]
Yeah, I'd be inclined to agree with @mattfrear. Certainly not opposed to it but, I'd I'm keen to see level of interest in this assertion so we can leave the issue open and see what activity it gets?

**Comment by JosephWoodward** [comment]
This hasn't seen much activity in way of others interested in this feature so I'm going to close it off for now.
