### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by sneh1** [shouldly/shouldly#469]
I forked and clone the repo.
Set the 'TestDiffTools' as startup project.

When I run tests for any tests by choosing any diff tool and the further options, I get the following error:

```
System.ArgumentNullException occurred
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: path1
  Source=mscorlib
  StackTrace:
   at System.IO.Path.Combine(String path1, String path2)
   at TestDiffTools.Program.Main(String[] args) in ..\Projects\shouldly\src\TestDiffTools\Program.cs:line 69
```

Please help to resolve this issue.

I am using Visual Studio 2017.

**Comment by slang25** [comment]
Good spot. If you change the csproj to include this:
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
```
That will fix it. The code should probably gracefully exit if it detects this scenario too.

**Comment by sasanknvs** [comment]
@slang25 When tried to open the solution in VS2015 i am getting an error "One or more projects could be opened" with below message in the Output windows. Can someone help me out ?

C:\Users\Sasanknvs\Source\Repos\shouldly\src\Shouldly\Shouldly.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Sasanknvs\Source\Repos\shouldly\src\Shouldly\Shouldly.csproj

C:\Users\Sasanknvs\Source\Repos\shouldly\src\Shouldly.Tests\Shouldly.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Sasanknvs\Source\Repos\shouldly\src\Shouldly.Tests\Shouldly.Tests.csproj

C:\Users\Sasanknvs\Source\Repos\shouldly\src\TestDiffTools\TestDiffTools.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Sasanknvs\Source\Repos\shouldly\src\TestDiffTools\TestDiffTools.csproj

C:\Users\Sasanknvs\Source\Repos\shouldly\src\DocumentationExamples\DocumentationExamples.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Sasanknvs\Source\Repos\shouldly\src\DocumentationExamples\DocumentationExamples.csproj

**Comment by JosephWoodward** [comment]
This should no longer be an issue, let me know otherwise.
