### ISSUE TITLE
Add ShouldSoundLike for System.String

### ISSUE THREAD

**Issue by xerxesb** [shouldly/shouldly#47]
String similarity checking using a [Levenshtein distance](http://en.wikipedia.org/wiki/Levenshtein_distance)

```
    [Test]
    public void TestShouldBeSimilarTo()
    {
        "Hello".ShouldBeSimilarTo("Helo");
    }
```

**Comment by SimonCropp** [comment]
given how many different similar algorithms there are, IMO this should not be part of the shouldly.. perhaps it could exist as another nuget that extends shouldly?

@JosephWoodward thoughs?

**Comment by JosephWoodward** [comment]
@SimonCropp I agree, it's not something we've seen asked for in all the time this ticket has existed. I'll close 👍

**Comment by SimonCropp** [comment]
any other issues/prs u want to close for the same reason?
