### ISSUE TITLE
Why not have ShouldSatisfyAllConditions generic with Action<T>?

### ISSUE THREAD

**Issue by JackTheSpades** [shouldly/shouldly#472]
Simple question, but why exactly does the ShouldSatisfyAllConditions not have an overload to handle Action<T> parameters?

It just seems much more natural that, when you call a Method named "ShouldSatisfyAllConditions" on an object, that all of these conditions are in some reference to said object without having to retype the same object again every time for every assertion.
Example:

```cs
public static void ShouldSatisfyAllConditions<T>(this T obj, params Action<T>[] actions)
{
    Action[] converted = actions
        .Select(a => new Action(() => a(obj)))
        .ToArray();
    obj.ShouldSatisfyAllConditions(converted);
}
  
var mrBurns = new Person() { Name = null };
mrBurns.ShouldSatisfyAllConditions
                (
                    p => p.Name.ShouldNotBeNullOrEmpty(),
                    p => p.Name.ShouldBe("Mr.Burns")
);
```

**Comment by lxalln** [comment]
Surely this is the same as writing:

```csharp
var mrBurns = new Person() { Name = null };
mrBurns.Name.ShouldNotBeNullOrEmpty();
mrBurns.Name.ShouldBe("Mr.Burns");
```

That achieves the same, is easier to understand, and is fewer lines of code. No?

**Comment by JackTheSpades** [comment]
Of course. Down the line it doesn't really matter how Asserts are arranged, as you have to pass them all anyway.
The point of the post is more about the fact that `ShouldSatisfyAllConditions` already exists as an extension method, but it doesn't matter what object it is used on at the moment. The current implementation works like this.

```cs
var homer = new Person() { Name ="Homer" };
var mrBurns = new Person() { Name = null };
homer.ShouldSatisfyAllConditions
                (
                    () => mrBurns.Name.ShouldNotBeNullOrEmpty(),
                    () => mrBurns.Name.ShouldBe("Mr.Burns")
                );
```

The fact that I called it on homer really has no bearing, as it takes an array of Action, with no real connection to the calling object. So why not have it at least be something that references the caller by passing Action<T> instead?

As for why you'd want to use it at all, from what I understand it doesn't stop at the first failure but completes all Actions passed to it before aggregating them.
As I already said, the end result (whether you pass or fail) remains the same and it just boils down to personal preference.
If I have 5 asserts on the same object, I like having them under some common usage like this. On another hand when I copy paste asserts I only have to replace one instance (given my Action<T> version, not the actual current one).
As I said, the usage is only personal preference really, the point of the thread is that the current implementation is rather unintuitive and... honestly pointless as an extension method.

**Comment by lxalln** [comment]
Ah I see, I didn't originally understand the confusing nature of `ShouldSatisfyAllConditions`. In which case, I totally agree that it'd make more sense for a generic version to exist.

> …honestly pointless as an extension method

I think it's worse than pointless, it's misleading.

Time to submit a PR perhaps?

**Comment by egil** [comment]
I +1 this issue. One neat usage for me is when my SUT returns an array of objects, and I want to assert on them individually, then this would allow me to do the following:

```csharp
List<some object> result = ...

result.Count.ShouldBe(2);
result[0].ShouldSatisfyAllConditions(x => x.Prop.ShouldBe("Foo"), ...);
result[1].ShouldSatisfyAllConditions(x => x.Prop.ShouldBe("Bar"), ...);
```

That saves me from having to assign each object in the array to its own variable or/and to use `result[x]` in my `ShouldSatisfyAllConditions` actions.

When will this land in a release?

**Comment by nchetan** [comment]
Found this issue from https://up-for-grabs.net/#/filters?labels=52&tags=
Based on the fact that it's closed, can we remove that label please?

**Comment by lxalln** [comment]
@nchetan this issue isn't closed :)

**Comment by SimonCropp** [comment]
given https://github.com/shouldly/shouldly/pull/498 is merged i will close this
