### ISSUE TITLE
NotThrowAsync : Make an async version of Should NotThrow

### ISSUE THREAD

**Issue by MarcAndreJean** [shouldly/shouldly#473]
It would be nice to have an async version of Should.NotThrow

**Comment by JosephWoodward** [comment]
I agree, I was thinking exactly the same thing today.

**Comment by totorovan** [comment]
I'd like got pick this one for the start :)

**Comment by JosephWoodward** [comment]
We have a PR for this [here](https://github.com/shouldly/shouldly/pull/430).

**Comment by LiryChen** [comment]
Hey I am a first-timer looking for tasks to do too. I found this issue pretty interesting, and there is a PR(didnt pass the checks yet) for it. Could I jump in and help with this issue?

**Comment by morrisond91** [comment]
Any idea when this will be implemented and released, looking forward to using it.

**Comment by morrisond91** [comment]
Ideally in the next hour :P

**Comment by yuliajulaya** [comment]
Is this issue fixed? If not I can help with it, would be my first PR on github.

**Comment by JosephWoodward** [comment]
@morrisond91 We've got a PR for it [here](https://github.com/shouldly/shouldly/pull/430/files) which will be part of the next release.

@yuliajulaya As mentioned above, this PR has been picked up but if you're looking for a PR and have a non-Windows machine then I'd love to get [this one fixed](https://github.com/shouldly/shouldly/issues/531]!

**Comment by ArnaudB88** [comment]
What is the current state of this functionality? The PR is created for more than 2 years now...

**Comment by JosephWoodward** [comment]
I've finally gotten around to merging this and will get it released in the next few days.
