### ISSUE TITLE
Is there a change log somewhere?

### ISSUE THREAD

**Issue by natiki** [shouldly/shouldly#480]
Hi,

Just upgraded Shouldy from 2.8.x to 3.x and want to see/understand what is new in the major version bump. I had a look on the documentation site, but there is no change log that I can see nor here on GH. 

Is there a change log somewhere?

**Comment by JosephWoodward** [comment]
Hi @natiki,

[Here's a list of the changes](https://github.com/shouldly/shouldly/releases), the main reason for the major version bump was we dropped support for .NET 3.5.

**Comment by natiki** [comment]
Hi @JosephWoodward,

Cool, thanks for that. Perhaps adding that as a link on the main https://github.com/shouldly/shouldly would be a good idea? And even perhaps in the documentation itself.

**Comment by JosephWoodward** [comment]
@natiki Good idea. Moving forward I'll link to the most recent versions at the bottom of the main page 👍
