### ISSUE TITLE
ShouldMatchApproved doesn't work in .net core

### ISSUE THREAD

**Issue by John-Williams** [shouldly/shouldly#486]
It looks to me like ShouldMatchApproved doesn't work in .net core 

There is a small todo in the code here:
https://github.com/shouldly/shouldly/blob/8655c6362d12d2fed2f53fb15c28eafc2393df76/src/Shouldly/ShouldlyExtensionMethods/ShouldMatchApprovedTestExtensions.cs#L1

which says: "// TODO Try and get this working with Core"

Firstly, the documentation should reflect this. 

Secondly, can this get fixed? I've had a pretty good look around at other issues and couldn't find anything relevant.

**Comment by JosephWoodward** [comment]
Hi @John-Williams,

Yes, this is something we're aware of and keen to get working.

**Comment by loneosama** [comment]
i have gotten the should match working with netstandard2.0 and that is fully compatible with netcoreapp2.0 can you see to my pull request @JosephWoodward

**Comment by dennisroche** [comment]
@loneosama I can't see your pull request? Can you link to this issue? 

I also have `ShouldMatchApproved` working on `netstandard2.0` and would love to have it working for everybody.

**Comment by loneosama** [comment]
the thing was someone told me that test your code on resharper unit test runner it has 1306 unit tests sepertate units tests for both frameworks. I did that and my some unit tests for should match approved were failing  for one of the frameworks. [Pull request](https://github.com/shouldly/shouldly/pull/496l) Here is the pull request. I had started to check it out but couldn't get the time to do so.

**Comment by JosephWoodward** [comment]
This can now be closed as this functionality has been ported to Shouldly in the most recent preview. There are still a few more diff tools to migrate across.
