### ISSUE TITLE
NullReferenceException when creating error message from Expression

### ISSUE THREAD

**Issue by DanielRose** [shouldly/shouldly#487]
I got a NullReferenceException when I was using ShouldAllBe(). The minimal repro is:

```
[TestFixture]
public class NRETest
{
  private static readonly int One = 1;

  [Test]
  public void NRE()
  {
    var list = new List<int> { One };

    list.ShouldAllBe(val => val != One);
  }
}
```

Environment: Windows 10, .NET 4.7, Shouldly 3.0.0

This results in an NRE in ExpressionStringBuilder.VisitMember(), because node.Expression is null.

**Comment by JosephWoodward** [comment]
Thanks for reporting this.

**Comment by HajbokRobert** [comment]
@JosephWoodward , can I take this?

**Comment by JosephWoodward** [comment]
@HajbokRobert Awesome! Thanks for this!

**Comment by JosephWoodward** [comment]
@DanielRose This has now been fixed and will be included in the next release.
