### ISSUE TITLE
Error reporting not on par with expectations

### ISSUE THREAD

**Issue by nicojs** [shouldly/shouldly#497]
Hi, I've just started to use Shouldly but I can't seem to get the error messages working.

This:

```cs
var map = new SortedList();
map.IndexOfValue("boo").ShouldBe(2);
```

Outputs: 

```
Shouldly.ShouldAssertException: -1
    should be
2
    but was not
```

Instead of (from readme):

```
map.IndexOfValue("boo") should be 2 but was 1
```

I've set debug info to full:

```xml
 <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
```

I'm using netcoreapp2.0 as my target framework.

I've attached my example project: [ShouldyErrorMessages.zip](https://github.com/shouldly/shouldly/files/1859036/ShouldyErrorMessages.zip)

Thanks for creating and maintaining Shouldly :trophy:

**Comment by hahn-kev** [comment]
I'm also having the exact same issue, I'm also running a 2.0 app.

**Comment by jhromadik** [comment]
Same thing over here. On .NET Framework 4.6.1 and 4.7 it works as expected, but .NET Core 1.1 and 2.0 don't display the expression, only the value.

Stack traces for the `Shouldly.ShouldAssertException` are different:

    .NET FW:
    Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
    Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)
    Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected)

    .NET Core:
    Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
    Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)

**Comment by zolrath** [comment]
I am also seeing this problem and as much as I enjoy the method of defining tests in Shouldy I can't adopt it in our new code base with such uninformative error reporting. Would love to see .net core support enhanced to be on par with 4.7!

**Comment by JosephWoodward** [comment]
@nicojs @hahn-kev @jhromadik @diegobarbosa @zolrath We hope to have solved this issue in [version 3.0.2 which can now be downloaded from NuGet](https://www.nuget.org/packages/Shouldly/), thanks for reporting it.

**Comment by JosephWoodward** [comment]
I will close this issue in the mean time, if you run into this again then please either feel free to reopen this, or raise it as a new issue. Thanks once again!

**Comment by hahn-kev** [comment]
I can confirm this is working for me now! Thanks 👍

**Comment by JosephWoodward** [comment]
Woohoo! Thanks.
