### ISSUE TITLE
ShouldBe difference text confuses null with the string "null"

### ISSUE THREAD

**Issue by jnm2** [shouldly/shouldly#499]
To pick an amusing example:

```cs
string text = null;
text.ShouldBe("null");
```

Produces:
```cs
Shouldly.ShouldAssertException : text
    should be
"null"
    but was
null
    difference
Difference     |                     
               |                     
Index          | 0    1    2    3    
Expected Value | n    u    l    l    
Actual Value   | n    u    l    l    
Expected Code  | 110  117  108  108  
Actual Code    | 110  117  108  108  
```

The diff says it is comparing against actual char codes 110, 117, 108, and 108. I wouldn't expect a diff at all because the actual string is not present (in contrast, I do expect the diff that shows up for an empty string).

**Comment by jnm2** [comment]
Opened https://github.com/shouldly/shouldly/pull/538.

**Comment by JosephWoodward** [comment]
This has now been merged, thanks for the PR!
