### ISSUE TITLE
model.ShouldBeEquivalentTo(otherModel);

### ISSUE THREAD

**Issue by SlowLogicBoy** [shouldly/shouldly#508]
Is there anything similar to [FluentAssertions](https://fluentassertions.com/documentation/#object-graph-comparison) `orderDto.Should().BeEquivalentTo(order);` ?

I would like to compare if two objects are equivalent but not with the same reference.

Edit:
Looks like PR #411 already exist for this.

**Comment by JosephWoodward** [comment]
For anyone landing on this page from Google, this feature is now in the [latest beta release](https://www.nuget.org/packages/Shouldly/4.0.0-beta0002).
