### ISSUE TITLE
ShouldBe for DateTime does not compare DateTimeKind.

### ISSUE THREAD

**Issue by PiotrPerak** [shouldly/shouldly#512]
var x = new DateTime(1980, 6, 10, 1, 1, 1, DateTimeKind.Utc);
    var y = new DateTime(1980, 6, 10, 1, 1, 1, DateTimeKind.Local);

    // this should generate failure but passes
    x.ShouldBe(y);

**Comment by meJevin** [comment]
I think this is not a bug, because this boils down to calling `DateTime.Equals` on `x` and `y` objects.
Indeed, the code below yields the same result

```
var x = new DateTime(1980, 6, 10, 1, 1, 1, DateTimeKind.Utc);
var y = new DateTime(1980, 6, 10, 1, 1, 1, DateTimeKind.Local);

// This returns true
x.Equals(y);
```

Comparing `DateTime` objects with different kinds is a bad idea in the first place.

**Comment by SimonCropp** [comment]
Yeah i dont think the default date equality behaviour should be changed.

@JosephWoodward suggest this should be closed
