### ISSUE TITLE
ShouldNotBeNull doesn't output variable name

### ISSUE THREAD

**Issue by mattfrear** [shouldly/shouldly#523]
Test code:
```csharp
var thing = new Thing();
thing.Foos = null; // Foos is an IList<Foo>
thing.Foos.ShouldNotBeNull();
```

Expected output:
```
Message: Shouldly.ShouldAssertException : thing.Foos
    should not be null but was
```
Actual output:
```
Message: Shouldly.ShouldAssertException : null
    should not be null but was
```

Same problem occurs (no variable name shown) with `ShouldNotBeEmpty()` when the object is null.

**Comment by maintain53** [comment]
I will like to work on this

**Comment by JosephWoodward** [comment]
Hi @mattfrear, sorry for the delay in looking into this. I don't appear to be able to replicate this issue, I'm doing the following and get the following response:

```csharp
using System;
using System.Collections.Generic;
using Shouldly;
using Xunit;

namespace TestProject4
{
    public class Foo {}
    
    public class Thing
    {
        public IList<Foo> Foos { get; set; }
    }
    
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            var thing = new Thing();
            thing.Foos = null; // Foos is an IList<Foo>
            thing.Foos.ShouldNotBeEmpty();
        }
    }
}
```
Response:

```csharp
TestProject4.UnitTest1.Test1

Shouldly.ShouldAssertException : thing.Foos
    should not be empty but was null
   at Shouldly.ShouldBeEnumerableTestExtensions.ShouldNotBeEmpty[T](IEnumerable`1 actual, Func`1 customMessage)
   at TestProject4.UnitTest1.Test1() in /Users/josephwoodward/Dev/TestProject4/TestProject4/UnitTest1.cs:line 25
```

**Comment by mattfrear** [comment]
Hi @JosephWoodward, thanks for investigating. At the time of reporting the bug I using Shouldly 3.0.1.

I stopped using Shouldly after finding this bug, when I saw the high number of open issues I thought "it's dead" so I switched to FluentAssertions. I actually much prefer the Shouldly syntax though, I miss it!

I just tried to reproduce it again, and I realise that my problem was that my unit tests project is not using "Full debug info", it's using the default which is portable. I will close this issue.

**Comment by JosephWoodward** [comment]
Hi @mattdotmatt, glad you got to the bottom of it. FluentAssertions is an equally good library, some people prefer one over the other etc so use whatever works for you.

Shouldly's far from dead though, we just have other things on our plate at times and we're slowly working through the issues raised.

Thanks for closing off the issue 👍
