### ISSUE TITLE
ShouldBeBetween(low, high)?

### ISSUE THREAD

**Issue by becdetat** [shouldly/shouldly#53]
I've got some loose change that I'm not interested in testing. I could just do:

```
price.ShouldBeGreaterThan(0.99m);
price.ShouldBeLessThan(1.01m);
```

but I had to think about that. This would be better:

```
price.ShouldBeBetween(0.99m, 1.01m);
```

and a complementary method would fit what I actually need:

```
price.ShouldBeWithinTolerance(1.00m, 0.01m);
```

which expands to `price.ShouldBeBetween(1.00m - 0.01m, 1.00m + 0.01m);`

I'm happy to give this a shot.

**Comment by Enissay** [comment]
> Oh I see. There is a `ShouldBe` overload with tolerance for float and double. I'm using decimal. Is there any reason for not having a decimal overload?

I see this is still not the case. No tolerance allowed for decimal type :-/
