### ISSUE TITLE
Ship with SourceLink

### ISSUE THREAD

**Issue by jnm2** [shouldly/shouldly#535]
Would you consider providing PDBs with SourceLink information? This will make it easy for anyone to drop into Shouldly code any time they want to understand what's going on, and users may return the courtesy by taking some initiative in diagnosing bugs they observe. Creating a repro is much easier when you aren't dealing with a black box!

It's easier than it used to be because the csproj SDK now supports it. The recommended route is https://github.com/dotnet/sourcelink#sourcelink-preview.

(Just ran into an NRE inside Shouldly's ExpressionStringBuilder and wanted to investigate.)

**Comment by jnm2** [comment]
I believe this has been closed by #536. Thanks @slang25, that was fast! 🎉

**Comment by JosephWoodward** [comment]
Yup! I'll get a new release out soon!

**Comment by jnm2** [comment]
@JosephWoodward Cool! Hey, if I fixed https://github.com/shouldly/shouldly/issues/499 really fast, would it make it?

**Comment by jnm2** [comment]
Just in case, no pressure: https://github.com/shouldly/shouldly/pull/538
