### ISSUE TITLE
Add diffing support for VS Code

### ISSUE THREAD

**Issue by JosephWoodward** [shouldly/shouldly#550]
Now that ShouldMatchApproved works cross platform, it'd be great to add support for VS Code. Mac is currently there, [but commented out](https://github.com/shouldly/shouldly/blob/master/src/Shouldly/Configuration/KnownDiffTools.cs#L16), so need to add it for Windows and Linux.

I'm happy to get it working on Linux, but it'd be great if someone could add it for Windows.

This involves finding out the most reliable way of locating VS Code on Windows (I believe it's changed locations a few times now).

**Comment by Mohammad-Haris** [comment]
I am a complete newbie to open source. I would really appreciate if you can guide me a little along the way and answer some questions. 
I am more than willing to contribute towards the solution of this issue though.

**Comment by JosephWoodward** [comment]
This can now be closed.
