### ISSUE TITLE
Extra Debug mode information added in Release mode.

### ISSUE THREAD

**Issue by akshaybheda** [shouldly/shouldly#551]
I am facing issue with 3.0.2 Version of Shouldly. My Test Project is .net framework 461. I am running tests in Debug mode, Tests run fine but whenever I run the tests in Release mode, I am getting additional text added to test messages which fails my few tests as i use .Shouldbe Method. 

The information that is added is "Shouldly uses your source code to generate its great error messages, build your test project with full debug information to get better error messages"

Additional information: The issue comes wherever i am using

> Should.Throw<ShouldAssertException>(()=>Method that throws the exception)).Message.ShouldBe("My Error message")

**Comment by akshaybheda** [comment]
@JosephWoodward I have created a sample repository, which you can clone and run the test using dotnet test --configuration release

**Comment by JosephWoodward** [comment]
Yes, thanks for this. I took a look and the behaviour is expected. Unfortunately when running in release mode there are optimisations that take place which make it difficult to walk the call stack to get the information Shouldly needs.

I'm tempted to update the message output to say "please build your test project in debug mode to get better error messages".

**Comment by slang25** [comment]
Depending on your circumstances you can work around this by doing `dotnet msbuild /t:Rebuild;VSTest p:Configuration=Release /p:Optimize=false`. (or drop the `dotnet` if you are not using an SDK style project)

**Comment by JosephWoodward** [comment]
I had a quick go at disabling optimisations then building in release mode, but the test still failed. How is this different?

**Comment by slang25** [comment]
Oddly you have to do it in the source project it seems for this case (which is going to be a no-no for most, hence this ad-hoc approach). If you try that command it should work.

**Comment by akshaybheda** [comment]
Well for now I have used this for workaround in my source project  
```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>false</Optimize>
    <DebugType>full</DebugType>
  </PropertyGroup>
```
