### ISSUE TITLE
Should.ThrowAsync error messages should match Should.Throw messages

### ISSUE THREAD

**Issue by demoncodemonkey** [shouldly/shouldly#554]
The error messages for Should.ThrowAsync don't seem as detailed as the error messages for Should.Throw. To demonstrate what I mean, try adding these to a file in your project:

```
    public class Package
    {
        public static Task<int> DoSomething()
        {
            throw new DivideByZeroException();
        }
    }

    public class Tests
    {
        [Test]
        public void Test1()
        {
            Should.Throw<TimeoutException>(() => Package.DoSomething());
        }

        [Test]
        public void Test2()
        {
            Should.Throw<TimeoutException>(async () => await Package.DoSomething());
        }

        [Test]
        public async Task Test3()
        {
            await Should.ThrowAsync<TimeoutException>(() => Package.DoSomething());
        }

        [Test]
        public async Task Test4()
        {
            await Should.ThrowAsync<TimeoutException>(async () => await Package.DoSomething());
        }
    }

//requires these packages: NUnit 3.11, NUnit3TestAdapter 3.12, Shouldly 3.02
```

Test1 output: 😃 
> Message: Shouldly.ShouldAssertException : Task \`Package.DoSomething()\`
>     should throw
> System.TimeoutException
>     but threw
> System.DivideByZeroException

Test2 output: 😃 
> Message: Shouldly.ShouldAssertException : Task \`async () => await Package.DoSomething()\`
>     should throw
> System.TimeoutException
>     but threw
> System.DivideByZeroException

Test3 output: 😞 
> Message: System.DivideByZeroException : Attempted to divide by zero.

Test4 output: 😞 
> Message: Shouldly.ShouldAssertException : Shouldly uses your source code to generate its great error messages, build your test project with full debug information to get better error messages
> The provided expression
>     handle aggregate exception
> System.TimeoutException
>     but was
> System.DivideByZeroException

**Comment by JosephWoodward** [comment]
Thanks for raising this, I'll take a look.

**Comment by gmilani** [comment]
Hello @JosephWoodward 
I want to start contributing to Shouldly project. Can I start with this issue?

**Comment by JosephWoodward** [comment]
Hi @gmilani,

Yes! That would be great! Let me know if you have any issues or questions.

**Comment by hrai** [comment]
Should this be closed?

**Comment by JosephWoodward** [comment]
Yes it should, thanks!

**Comment by wuanunet** [comment]
Hi,

It seems there’s a minor mistake in the documentation or example. The correct usage should be:

`action.ShouldThrow().Message.ShouldBe("message");`

Instead of:

`action.ShouldThrow().WithMessage("message");`

WithMessage does not appear to be a valid method in the current version of Shouldly.

Thanks for the great library! 😊

**Comment by gabemilani** [comment]
Thanks for catching that!

Would you be able to open a PR fixing it?
