### ISSUE TITLE
Exceptions should be deserializable

### ISSUE THREAD

**Issue by jho1965us** [shouldly/shouldly#557]
Got the following message when trying to deserialize ShouldAssertException:

System.Runtime.Serialization.SerializationException: 'The constructor to deserialize an object of type 'Shouldly.ShouldAssertException' was not found.'

**Comment by JosephWoodward** [comment]
Thanks for reporting this, I'll take a look.

**Comment by bender2k14** [comment]
@jho1965us, why did you serialize the exception?

**Comment by jho1965us** [comment]
part of my test run in an other AppDomain for the exception to cross the AppDomain boundary it get serialized

**Comment by EranOfer** [comment]
MSDN:
"Exception(SerializationInfo, StreamingContext), which is a protected constructor that initializes a new exception object from serialized data. **You should implement this constructor if you've chosen to make your exception object serializable**"

Could you please make all custom exception serializable?

For example :
```
 ShouldAssertException(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {}
```

Thanks in advance

**Comment by brunomasantos** [comment]
From what i can understand in here, this would be something like:

```
...

 [SecurityPermissionAttribute(SecurityAction.Demand, SerializationFormatter = true)] 
 protected ShouldAssertException(SerializationInfo info, StreamingContext context) : base(info, context)
        {}
...

#if StackTrace

...

        [SecurityPermissionAttribute(SecurityAction.Demand, SerializationFormatter = true)]
        public override void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            if (info == null)
            {
                throw new ArgumentNullException("info");
            }

            info.AddValue("ShouldAssertException.StackTrace", this.StackTrace);
            
            base.GetObjectData(info, context);
        }

...

#endif
```

Wondering if you are ok with me picking this up. Also it would be great for @jho1965us to gives us the real use case to add a unit test matching it.

**Comment by SimonCropp** [comment]
i dont think "exceptions should be serializable" applies to when the exceptions are being throw directly to a test runner. 

@jho1965us @EranOfer @brunomasantos  If you think it is necessary, can u provide a minimal standalone repro solution that illustrates where an exceptions not being serializable causes problems in the context of shouldy

**Comment by SimonCropp** [comment]
@JosephWoodward close for now?
