### ISSUE TITLE
Extend `ShouldHaveSingleItem` to take a predicate

### ISSUE THREAD

**Issue by RedX2501** [shouldly/shouldly#561]
Linqs `Single` has an overload that takes a predicate which makes such code very intuitive:

    var item = collection.Single(x => x.Name == "foo")

It would be nice if we could extend that to our `ShouldHaveSingleItem`:

    var item = collection.ShouldHaveSingleItem(x => x.Name == "foo")

A simple implementation could be

```
public static T ShouldHaveSingleItem<T>(this IEnumerable<T> collection, Func<T, bool> pred, string customMessage)
{
  try
  {
     var item = collection.Single(pred);
     return item;
  }
  catch(InvalidOperationException ex)
  {
     //todo: get the body of pred and print it out into the message.
     throw new ShouldAssertException(ex.Message);
  }  
}
```

I'm currently trying this out (as an extension in other code) and the only problem I have with the nice message is that I cannot use `ExpectedShouldlyMessage` because it is `internal` what is the reason for that and what is my best alternative?

**Comment by jnm2** [comment]
Are you satisfied with the error message if you make the extension method delegate to `.Where(predicate).ShouldHaveSingleItem()`?

**Comment by nibba228** [comment]
You just need to make it `public`, not  `internal`

**Comment by RodgerLeblanc** [comment]
`ExpectedShouldlyMessage` is now `public` instead of `internal` following #648.

**Comment by jnm2** [comment]
Closing due to lack of response, but we will see future responses and reopen if anyone wants to pursue this and has answers to guide the design.

**Comment by jehrenzweig-captionhealth** [comment]
Posting from the distant future, where cats are driving space-cars...

I didn't know about the `ShouldHaveSingleItem()` method until I saw this issue.  It helped me identify a more elegant way to check not only the number of items in an enumerable, but also the contents of that single item:
```csharp
public record User(string[] Nicknames, string FullName);

// Happy path
var jj = new User(Nicknames: ["Johnny"], FullName: "John Jacob Jingleheimer Schmidt");
IEnumerable<User> firstSetOfUsers = [ jj ];

firstSetOfUsers.ShouldHaveSingleItem().ShouldSatisfyAllConditions(
    x => x.Nicknames.ShouldHaveSingleItem().ShouldBe("Johnny"),
    x => x.FullName.ShouldBe("John Jacob Jingleheimer Schmidt"));
```

Example of an assertion that fails in the root `ShouldHaveSingleItem()` check:
```csharp
// More users than expected
var ab = new User(Nicknames: ["Andy"], FullName: "Andrew Bee");
var cd = new User(Nicknames: ["Chuck"], FullName: "Charles Dee");
IEnumerable<User> secondSetOfUsers = [ ab, cd ];

secondSetOfUsers.ShouldHaveSingleItem().ShouldSatisfyAllConditions(
    x => x.Nicknames.ShouldHaveSingleItem().ShouldBe("Andy"),
    x => x.FullName.ShouldBe("Andrew Bee"));
```

Example of an assertion that fails in the nested `ShouldHaveSingleItem()` check:
```csharp
// More nicknames than expected
var zz = new User(Nicknames: ["Zed", "ZeeZee", "Zero"], FullName: "Greg Zee");
IEnumerable<User> thirdSetOfUsers= [ zz ];

thirdSetOfUsers.ShouldHaveSingleItem().ShouldSatisfyAllConditions(
    x => x.Nicknames.ShouldHaveSingleItem().ShouldBe("Zed"),
    x => x.FullName.ShouldBe("Greg Zee"));
```

HTH!
