### ISSUE TITLE
Any ability to register custom base types with Shouldly?

### ISSUE THREAD

**Issue by natiki** [shouldly/shouldly#569]
Hi,

I have my own base type which is fundamentally a string with some length checking. Screenshot below for brevity sake:

![image](https://user-images.githubusercontent.com/4738140/57966592-7dda6c80-7997-11e9-800c-5067e6f2decd.png)

I would like to perform ShouldBe() calls to the type directly. So of course the following is possible by accessing the Value property which is of type `string`:

```c#
 [Parallelizable(ParallelScope.All)]
 [TestFixture]
 public class TSpYtStringLengthTests : SpYtTestsBase
 {
     [Test]
     public void TSpYtStringLength_Assignment()
     {
         //Arrange
         const string SOME_STRING = "Some String";

         //Act
         TSpYtStringLength myString = SOME_STRING;

         //Assert
         myString.Value.ShouldBe(SOME_STRING);
         string backToString = myString;
         backToString.ShouldBe(SOME_STRING);
     }
 }
```
So to do ShouldBe() directly on the `TSpYtStringLength` aside from replicating what is in `ShouldBeStringTestExtensions` is there a better way to do it? Any way to register types with Shouldly or similair?

**Comment by SimonCropp** [comment]
@natiki currently no there is no way to do this in shouldly
