### ISSUE TITLE
Shouldly uses your source code to generate its great error messages, build your test project with full debug information to get better error messages

### ISSUE THREAD

**Issue by gitgan1** [shouldly/shouldly#572]
I am using Shouldly 3.0.2 with NUnit 3.11.0. My test project is built using Debug configuration. 
When Shouldly assertion fails, it is not showing up meaning full message.
retryPolicyOutcome.ShouldBe(OutcomeType.Successful)

   Error Message:
    Shouldly.ShouldAssertException : Shouldly uses your source code to generate its great error messages, build your test project with full debug information to get better error messages
 The provided expression
     should be
 OutcomeType.Successful
    but was
 OutcomeType.Failure

**Comment by jeffkl** [comment]
You need to set DebugType to `Full` which is not the default anymore.  Example: 

https://github.com/jeffkl/SlnGen/blob/master/Directory.Build.targets#L4-L5

**Comment by slang25** [comment]
It will still work if it's on a modern .net framework runtime or .net core with portable pdbs, the message should be updated. I'd be interested to know the runtime here

**Comment by SimonCropp** [comment]
closing due to no response
