### ISSUE TITLE
System.Exception from ShouldMatchApproved

### ISSUE THREAD

**Issue by sungam3r** [shouldly/shouldly#574]
On this [PR](https://github.com/graphql-dotnet/graphql-dotnet/pull/1247) I have that error: https://ci.appveyor.com/project/graphql-dotnet-ci/graphql-dotnet/builds/26733618/tests

System.Exception : Source information not available, make sure you are compiling with full debug information. Frame: **RuntimeMethodHandle.InvokeMethod**

It seems to me that `TestMethodFinder` found not my method, but the framework method.

On my Windows machine, the test is successful.

Original posted issue JakeGinnivan/ApiApprover#77

**Comment by slang25** [comment]
This won't fix it, but the guidance on the readme is out of date and you should not need full debugtype for .NET Core projects (or probably any projects below 4.7.1).

**Comment by slang25** [comment]
This problem is because the tests are run in release mode. If they are run in debug they should work. On my mac I was able to replicate the issue by running the tests with the `-c Release` flag.

**Comment by sungam3r** [comment]
I confirm, the error is gone.

**Comment by JosephWoodward** [comment]
Great, thanks @slang25
