### ISSUE TITLE
Provide annotations for C# 8 Nullable Reference Types

### ISSUE THREAD

**Issue by jnm2** [shouldly/shouldly#579]
I'm starting to run into scenarios where I'd appreciate annotations on Shouldly. Would you accept a PR to move the LangVersion to 8.0 (necessary to annotate reference types with `?` in public APIs) and enable https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references? This does not require targeting .NET Core 3.0.

```cs
var foo = ...;
foo.ShouldNotBeNull();

// I'd like to be able to remove the `!`
foo!.Bar.ShouldBe(42);
```

In order to let the compiler know that `ShouldNotBeNull` means that `foo` can't be null lower down, you'd add `[NotNull]` to this line:

https://github.com/shouldly/shouldly/blob/4f990555884d60e07bc1278040a131a80e9f5031/src/Shouldly/ShouldlyExtensionMethods/ShouldBeNullExtensions.cs#L31

```diff
-   public static void ShouldNotBeNull<T>(this T actual) 
+   public static void ShouldNotBeNull<T>([NotNull] this T actual) 
```

https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullattribute:

> Specifies that an output is not `null` even if the corresponding type allows it.

Even though the the documentation refers to it as an output, and `actual` above is a by-value parameter, I have verified that `[NotNull]` has the intended effect.

It's also been really fun using https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator for two benefits, so I'd recommend it:

- It defines the System.Diagnostics.CodeAnalysis nullability attributes as internal attributes, which you would otherwise have to do manually.
- It annotates the .NET Framework and Standard reference assemblies by copying annotations from matching APIs in .NET Core 3.0 so that your codebase can benefit internally.

**Comment by jnm2** [comment]
I started some exploratory work on this and it annotated really nicely. It's pretty much done. I found several places where real NREs can be thrown in current releases.

**Comment by JosephWoodward** [comment]
Sounds like a great idea to me!
