### ISSUE TITLE
Disable accidental use of ShouldBeNullExtensions on structs, add "where T : class" on methods

### ISSUE THREAD

**Issue by r-pankevicius** [shouldly/shouldly#584]
Assume code today, when people are crazy about use of var-s:

```csharp
var result = ClassUnderTest.MyMethod();
result.ShouldNotBeNull();
```

If type of result is int, then this check will succeed, for example 5 != null evaluates to true.
But this check is useless first of all. Maybe people used different type yesterday, today refactored it to use int, but compiler did not tell, hey, it's false sense of success.

I suggest adding generic method specification requiring value under test to be nullable, e.g. class, not struct.

Below is sample code to show the idea: ShouldNotBeNull_V2 is better than ShouldNotBeNull_V1 because compiler will tell you're doing something wrong.

```csharp
static class MyExtensions
{
	public static void ShouldNotBeNull_V1<T>(this T actual)
	{
		if (actual == null)
			throw new InvalidOperationException();
	}

	public static void ShouldNotBeNull_V2<T>(this T actual) where T : class
	{
		if (actual == null)
			throw new InvalidOperationException();
	}
}

class UserCode
{
	public void Test()
	{
		int x = 5;

		5.ShouldNotBeNull_V1(); // possible to write it
		5.ShouldNotBeNull_V2(); // you get compiler error
	}
}
```

**Comment by sungam3r** [comment]
Hmm, I think that there already was where constraint ).

**Comment by r-pankevicius** [comment]
I was looking at
https://github.com/shouldly/shouldly/blob/master/src/Shouldly/ShouldlyExtensionMethods/ShouldBeNullExtensions.cs
today

**Comment by r-pankevicius** [comment]
...and I've set up latest stable version of Shouldly: Assembly Shouldly, Version=3.0.2.0, Culture=neutral, PublicKeyToken=6042cbcb05cbc941, and was able to write:

```csharp
[Fact]
public void ICanHaz()
{
	5.ShouldNotBeNull();
	5.ShouldBeNull();
}
```
Well, compiler did not cry for Argentina.

$>ping @sungam3r

**Comment by sungam3r** [comment]
Well, in small steps we will sooner or later come to the ideal.

**Comment by r-pankevicius** [comment]
@sungam3r  Send a letter to Anders Hejlsberg, because C# compiler should catch this issue before us.

**Comment by jnm2** [comment]
Adding `where T : class` broke existing code that used these extension methods on `System.Nullable<T>` values. The fix was to add overloads with `where T : struct` as well. (#676)

**Comment by r-pankevicius** [comment]
@jnm2 **Shame on me**: I forgot that `System.Nullable<T>` is a struct. I'll come back with my view on this before inspecting your changes "to avoid mind pressure".  😊

**Comment by r-pankevicius** [comment]
This is version 3.

```csharp
static class MyExtensions
{
	public static void ShouldNotBeNull_V1<T>(this T actual)
	{
		if (actual == null)
			throw new InvalidOperationException();
	}

	public static void ShouldNotBeNull_V2<T>(this T actual) where T : class
	{
		if (actual == null)
			throw new InvalidOperationException();
	}

	// The Brave New World - V3.
	public static void ShouldNotBeNull_V3<T>(this T actual) where T : class
	{
		if (actual == null)
			throw new InvalidOperationException();
	}

	public static void ShouldNotBeNull_V3<T>(this Nullable<T> actual) where T : struct
	{
		if (actual.HasValue)
			throw new InvalidOperationException();
	}
}

static class UserCode
{
	public static void Test()
	{
		// Version 1
		//
		5.ShouldNotBeNull_V1(); // possible to write this nonsense:(

		// Version 2: let's improve it
		//

		// you'll get compiler error: that's good
		// Error CS0452: The type 'int' must be a reference type in order to use it as parameter 'T'
		// in the generic type or method 'MyExtensions.ShouldNotBeNull_V2<T>(T)'
		//5.ShouldNotBeNull_V2();

		// My mistake here...
		//int? y = 5;
		//y.ShouldNotBeNull_V2();

		// Version 3: let's improve it again
		//

		// compiler error: that's good
		//5.ShouldNotBeNull_V3();

		int? z = 5;
		z.ShouldNotBeNull_V3(); // works!
	}
}
```

**Comment by jnm2** [comment]
Looks good. I think style guides recommend the syntax `T?` rather than `Nullable<T>` in C# source code. Another difference you'll see is that Shouldly is using C# 8's Nullable Reference Types feature, so the syntax is `T?` for `where T : class` as well.

**Comment by r-pankevicius** [comment]
Your syntax` this T? actual` also looks good. The only difference semantically is ==/!== null and HasValue/! HasValue.

**Comment by r-pankevicius** [comment]
I've heard about C# 8's Nullable Reference Types feature, but did not dig into it yet. Thanks for info.

**Comment by jnm2** [comment]
> The only difference semantically is ==/!== null and HasValue/! HasValue.

You can use both the operators and the HasValue property whether or not you use the syntax `T?` or `Nullable<T>`. `T?` is a synonym for `global::System.Nullable<T>` the same way that `(int, string) is a synonym for `global::System.ValueTuple<int, string>`.

**Comment by r-pankevicius** [comment]
Oh, unit tests are not a target for optimization, so investigation deep to MSIL level if ==/!== operators are as optimal as property getter HasValue invocation do not make a difference.

**Comment by jnm2** [comment]
Just updated to beta0004 and found a latent bug in our tests because of this :D
