### ISSUE TITLE
ShouldBeApproved: "current Visual Studio" DiffTool wrong arguments order

### ISSUE THREAD

**Issue by pavel-usachev** [shouldly/shouldly#592]
Hello. 

I mentioned that on red ShouldMatchApproved test, I see hardly readable diff in Visual Studio. 
Look, I have appoved file like this and the test:

![test_approved](https://user-images.githubusercontent.com/540241/68424582-5aa9b080-01b5-11ea-8b50-d56a7da93a4a.PNG)

When test fails, I am getting this diff:

![actual](https://user-images.githubusercontent.com/540241/68424630-71e89e00-01b5-11ea-8186-23a6497d2fa8.PNG)

But I expect to see:

![expected](https://user-images.githubusercontent.com/540241/68424640-76ad5200-01b5-11ea-8ee9-b86e2843b9d4.PNG)

As [docs.microsoft.com](https://docs.microsoft.com/en-us/visualstudio/ide/reference/diff?view=vs-2019) said:

> devenv /Diff SourceFile TargetFile [SourceDisplayName [TargetDisplayName]]

Is it a mistake in arguments order for diff tools or desired behavior? Do you consider changing an approved file path to source argument?

**Comment by sungam3r** [comment]
I myself asked this question. Moreover, when working on another project where approved tests are used, there were cases when people were also confused because of this.

**Comment by JosephWoodward** [comment]
Would love to have a PR to fix this if possible? My development machine these days is a Mac with Rider so it's a challenge to verify this.

**Comment by pavel-usachev** [comment]
Yep, but to solve issue in general I went through every diff tool in the list of known and checked the arguments for windows platform. I see that older diff tools are not intended to check "source" and "target" files, it just meant to check "left" and "right" ones. Newer tools show better diff in "approved received" order while older tools doesn't care of argument order. Fix me, please, if I get it wrong.

I have few more questions:

Why some tools take arguments to just diff two files while other are receive arguments for merge? Did you plan to just show difference between approved and received files or to create a new approved file right out in the tool?

Is there such significant difference in arguments order for other platforms: Linux and MacOS? Can I just change received and approved arguments for all of the tools?

**Comment by pavel-usachev** [comment]
When I installed all this this tools I came up with reason why there's difference in tools arguments. It is merged into \*approved* file where it's possible and just show diffs where is not.

@JosephWoodward, could you have a glance at the PR. I also moved difftools to separate files, changed files discovery a little and added one more difftool (vimdiff). Check whether it's acceptable.

**Comment by SimonCropp** [comment]
fixed by https://github.com/shouldly/shouldly/pull/644
