### ISSUE TITLE
ShouldBe() marked as heuristically unreachable by ReSharper 2019.3.20191207.71320

### ISSUE THREAD

**Issue by mqtwinter** [shouldly/shouldly#599]
I'm using Shouldly 3.0.2. Love it. Just upgraded to VS 2019 16.4.1 and ReSharper 2019.3.20191207.71320.

Now ReSharper is thinking some ShouldBe() calls always throw exceptions, so it marks all code after it as heuristically unreachable.

This seems to be only for ShouldBe() methods that have ContractAnnotationAttribute.
For example:
[ContractAnnotationAttribute("actual:null,expected:notnull => halt;actual:notnull,expected:null => halt")]
public static void ShouldBe<T>(this T actual, T expected);

Perhaps ReShaper is now processing these annotation incorrectly? Which of course would not be your fault. I'm trying to understand the annotation syntax so I can tell if it's correct or not.

![image](https://user-images.githubusercontent.com/27961202/70720263-80007180-1cc1-11ea-9f1c-918458ab383d.png)

**Comment by mqtwinter** [comment]
The issues I just submitted to JetBrains: [https://resharper-support.jetbrains.com/hc/en-us/requests/2400984](url)

ReSharper docs on the annotation syntax don't seem to mention the syntax being used.
[https://www.jetbrains.com/help/resharper/Contract_Annotations.html](url)

None of the examples in the docs have anything like where you are using TWO parameters with a halt. For whatever that's worth.

[ContractAnnotationAttribute("actual:null,expected:notnull => halt;actual:notnull,expected:null => halt")]
public static void ShouldBe(this T actual, T expected);

**Comment by JosephWoodward** [comment]
Oh interesting, so it was a ReSharper bug?

**Comment by mqtwinter** [comment]
ReSharper support just commented as follows:

We've already aware of this problem, please refer to the reported issue - [https://youtrack.jetbrains.com/issue/RSRP-477404](url)

Not sure if that means they believe it is a bug in ReSharper. So we'll see!

**Comment by mqtwinter** [comment]
The R# people say this will be resolved in R#  2019.3.1

**Comment by JosephWoodward** [comment]
Going to close this off as it's no longer an issue, thanks for making us aware of @mqtwinter
