### ISSUE TITLE
ShouldMatchApproved opens difftool in the 1st Visual studio instance

### ISSUE THREAD

**Issue by Ekkeir** [shouldly/shouldly#600]
We are using ShouldMatchApproved in our unit tests. After migrating to VS2019 (used as difftool) the following unexpected behaviour is observed (could have gone unnoticed in VS2017).

1. Open an instance of VS with a solution, make sure that ShouldMatchApproved unit test fails. Run the test. A difftool window opens in this VS instance (as expected).

2. Open another instance of VS with another solution, make sure that ShouldMatchApproved unit test fails. Run the test - difftool window for the test opens in the previous VS instance. (not expected).

3. (Additional, more severe unexpectedness) Close the VS instance opened on step 1, run the ShouldMatchApproved unit test from the second solution, observe the following error:

Shouldly.ShouldAssertException : Cannot find a difftool to use, please open an issue or a PR to add support for your difftool.
    In the meantime use 'ShouldlyConfiguration.DiffTools.RegisterDiffTool()' to add your own
  Stack Trace: 
    PublicApiApprovalTest.Public_Api_Changes() line 30

Current workarounds:
1. Do not close the 1st opened VS instance.
2. Close all VS instances. Reopen the solution(s) you're working on.

Observed: Difftool opens in the first opened VS instance only. Does not open at all when the first opened VS instance is closed.
Expected: Difftool opens in separate VS instances per opened solutions

Is this something that can be solved via configuration on my side?
Thanks in advance.

**Comment by sungam3r** [comment]
I have the same issue.

**Comment by SimonCropp** [comment]
I dont think this is possible to fix. From my experience with approvaltests and verify (that have similar functionality) you cant determine what instance of VS ran the test and even if you could you cant pick an instance of VS to launch the diff in.

**Comment by SimonCropp** [comment]
That is why VS is very far down list of tool preference here https://github.com/VerifyTests/DiffEngine/blob/master/docs/diff-tool.order.md

**Comment by JosephWoodward** [comment]
@SimonCropp That's an interesting question, I'm not sure (it was before my time). That's interesting to know that it's not possible to know which instance to launch the diff view in.

**Comment by SimonCropp** [comment]
so do we close this?

**Comment by JosephWoodward** [comment]
@SimonCropp Yeah, if we can't control which window this opens in then we should close this off.
