### ISSUE TITLE
Discussion - Upgrading co-contributors to have merge permissions?

### ISSUE THREAD

**Issue by hrai** [shouldly/shouldly#608]
This is an open source project and I know people contribute on their free time which is hard to get these days.

I was wondering if the maintainer has considered pulling in long term contributors to help out with the PR merges.

This would enable faster resolution of issues. Also, the PRs wouldn't be sitting waiting for merges and gets stale with potential merge conflicts when someone tries to merge them.

/cc @jnm2

**Comment by JosephWoodward** [comment]
Yeah, I'd certainly be up for some help on keeping this up to date. Given all of @jnm2's work he seems like a good candidate.

**Comment by jnm2** [comment]
Thanks for the vote of confidence! I'm hesitant because I'm always behind on what I think I should be doing, so I may disappoint. On the other hand, I use Shouldly everywhere and would like to give back.

At one point I thought @slang25 already had merge permissions. He's been pretty active here. My perception is that he'd be a capable co-maintainer if available.

**Comment by SimonCropp** [comment]
@JosephWoodward @jnm2 @slang25 

so the current status is I am a tourist with commit permissions. My goal is to get should back to a "maintained" state. i dont really have any skin in the game to be a long term maintainer, although i am happy to stick around if needs be. But i think adding @jnm2 and/or @slang25 as maintainer would be a good idea.

**Comment by slang25** [comment]
Thanks @SimonCropp, I appreciate the work you've put in here getting everything in good shape. Getting that Nullable Reference stuff merged is a big deal too 🥳 

I'd love to join as a maintainer, I think like @JosephWoodward (and @jnm2) my availability is a bit "spikey", but with more of us there's a better chance we'll have things covered and can give each other some encouragement.

**Comment by SimonCropp** [comment]
i added @jnm2 and @slang25
