### ISSUE TITLE
Add and require C# XML documentation on public methods

### ISSUE THREAD

**Issue by egil** [shouldly/shouldly#609]
It would really push this library to the next level if all public assert methods had good [XML documentation](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/). 

Most of the time, the vocabulary used to name assert methods is so good that docs are not needed, but some of the lesser used methods does require me now and then to look it up in the docs to make sure I am getting what I want.

It also seems to me that XMLDocs are easier to maintain and make sure are there, e.g. during pull requests, and can, if the right tool is used, be the basis of a documentation site (e.g. docfx).

If I get a little spare time, I will try to add docs to the source code based on those in the /docs folder. That said, I hope you start enforcing XMLDocs on pull requests going forward.

Thanks for a great library!

**Comment by JosephWoodward** [comment]
I agree, this would be great to do.

**Comment by SimonCropp** [comment]
closing this one for now. docs can always be better, and no amount of change will ever make this one done. Always happy to accept PR for docs (xml or otherwise)
