### ISSUE TITLE
Should methods should return T to support fluid method chaining

### ISSUE THREAD

**Issue by cable729** [shouldly/shouldly#61]
For example,

```
computedAddress.ShouldContain("Boston").ShouldNotContain("Alaska");
```

This would be possible if `ShouldContain` returned the passed-in argument.

Let me know if you would like this functionality and I can start working on it.

**Comment by ivanakcheurov** [comment]
Actually I'd even use this right in code:
using(var context = GetContext())
{
foreach (var orderItem in context.OrderItems.Where(oi => oi.OrderRef == OrderRef).ShouldNotBeEmpty())
{
// do something with each order item
}
}
