### ISSUE TITLE
can i become a core contributor?

### ISSUE THREAD

**Issue by SimonCropp** [shouldly/shouldly#617]

**Comment by JosephWoodward** [comment]
Hi Simon, thanks for your interest! I'm a bit hesitant to make anyone without a history of contributions to Shouldly a core contributor. Out of interest, why are you interested in becoming a core contributor over a contributor?

**Comment by SimonCropp** [comment]
> why are you interested in becoming a core contributor

even though i dont use shouldly, i like the concept and i think it is something that should continue to exist and be maintained.

> why are you interested in becoming a core contributor over a contributor

It seems you are not short on contributors https://github.com/shouldly/shouldly/pulls. but you need more people to help triage , merge, and release

Happy to run as a trial. perhaps 2-3 weeks. if u think it is not working out, remove me and no hard feelings.

**Comment by JosephWoodward** [comment]
> It seems you are not short on contributors https://github.com/shouldly/shouldly/pulls. but you need more people to help triage , merge, and release.

This is true. And there's some things I'd really like to get done but lack the time sometimes. Is this a long term commitment you're interested in?

**Comment by SimonCropp** [comment]
> . Is this a long term commitment you're interested in?

depends if i can have an impact.

how about we close this for now. i will see what impact i can have as a non maintainer. and we can re-evaluate in the future?

**Comment by JosephWoodward** [comment]
Do you fancy continuing this conversation over DM on Twitter?

**Comment by SimonCropp** [comment]
sure. DMd u
