### ISSUE TITLE
remove Func<string> customMessage overloads

### ISSUE THREAD

**Issue by SimonCropp** [shouldly/shouldly#637]
@JosephWoodward @JakeGinnivan whats the point of passing the `customMessage` builder all the way through? why not just let all the apis take a string?

**Comment by jnm2** [comment]
ℹ NUnit has the same thing. I think it's in case it slows down the test to build the message. I think I used it maybe once, ever.

**Comment by JakeGinnivan** [comment]
That would be my guess, avoid creating a potentially large string/evaluating the things which create the custom message if it's not needed.

That said, that seems like a premature/unnecessary optimisation

**Comment by SimonCropp** [comment]
any objections to me removing and only having a string. it deletes a massive amount of code

**Comment by SimonCropp** [comment]
specifically. it removes 1600 lines of code

**Comment by jnm2** [comment]
Having time to publish versions with [Obsolete], but people do expect a few such breaks in a major release too.

**Comment by JosephWoodward** [comment]
I'd be happy to remove the delegate versions. Perhaps to save confusion we leave the extension methods there for a bit with `[Obsolete(true)]` and a description with how to fix as opposed to just removing them?

**Comment by lprichar** [comment]
> it removes 1600 lines of code

That is very cool, and I now understand why the feature was removed.  

However, it's extremely useful for the .ShouldBeEmpty() method when you want to write out details about the item that actually came back when it was unexpectedly non-empty.  For instance if you're doing an import and have import errors like this:

`importErrors.ShouldBeEmpty(() => $"{importErrors[0].LineNumber}: {importErrors[0].Message}")`

I've now rewritten over 100 tests that were doing something like that to something like this:

`importErrors.ShouldBeEmpty(() => $"{importErrors.FirstOrDefault()?.LineNumber}: {importErrors.FirstOrDefault()?.Message}")`

Shouldly is a wonderful library for convenience and readability, it's a shame to have lost some of that sweet syntactic sugar.

**Comment by jnm2** [comment]
That's a nice example, thanks @lprichar! Here's what I often do:

```cs
importErrors.Select(e => (e.LineNumber, e.Message)).ShouldBe(new[]
{
    (1, "Message 1"),
    (2, "Message 2"),
});
```

Extending to your example:

```cs
importErrors.Select(e => (e.LineNumber, e.Message)).ShouldBeEmpty();
```

Or possibly string interpolation rather than a tuple.

**Comment by lprichar** [comment]
Projecting a collection that's supposed to be empty in order to get useful error messages when it isn't.  Interesting solution.  Feels a bit hacky at first glance, but is definitely a very creative solution.  Thanks @jnm2.

**Comment by jnm2** [comment]
@lprichar It's felt like the most consistent approach in the most situations so far, and it usually feels like it has the best signal-to-noise ratio of all the options. I'm always on the lookout for better ideas!

**Comment by SimonCropp** [comment]
perhaps ShouldBeEmpty should serialize the list to a string and write the result on fail?

My personal approach would be to use snapshot testing via https://github.com/VerifyTests/Verify. then if the collection is not empty i get a diff tool opening showing the unexpected values in the list
