### ISSUE TITLE
At loss with shouldly result

### ISSUE THREAD

**Issue by Hefaistos68** [shouldly/shouldly#654]
Just got this out of a unit test:
```
Message: 
    Test method Q7.Core.Test.BaseCollectionTest.TestCopyAssign threw exception: 
    Shouldly.ShouldAssertException: b
        should be
    [] (Q7.Core.BaseCollection`1[System.Int32])
        but was
    [] (Q7.Core.BaseCollection`1[System.Int32])
        difference
    []
  Stack Trace: 
    Extensions.TestDefaultCopy[T]() line 129
    BaseCollectionTest.TestCopyAssign() line 55
```

from my point of view there is no difference according to the message. In fact both objects are empty containers. Yet something triggered the failure and shouldly could not express the difference. 
I will dig into this and let you know whats up with that. Maybe we can improve it somehow.

**Comment by slang25** [comment]
Interesting, can you share with us some of the test code? A small example recreating the issue would really help (or even just which assertion method is being used and the types).

**Comment by SimonCropp** [comment]
@Hefaistos68 assuming the lack of response means you found a solution. if not can you share a small repro and we can re-open this issue

**Comment by Hefaistos68** [comment]
Sorry, am on medical leave and not working, will get back to it in a few weeks.
