### ISSUE TITLE
ShouldNotThrowAsync not available

### ISSUE THREAD

**Issue by lommez** [shouldly/shouldly#659]
I've downloaded the package 3.0.2 but the extension method ShouldNotThrowAsync is not available.
Or am i missing something?

Here is my code:
```csharp
Task t = proxy.DoSomethingAsync();
t.ShouldNotThrowAsync("some message").Wait();
```

**Comment by JosephWoodward** [comment]
Hi @lommez, check out the [latest beta package](https://www.nuget.org/packages/Shouldly/4.0.0-beta0002), you'll find it in there.

**Comment by JosephWoodward** [comment]
I'll close this off in the meantime, any other questions then please feel free to ask.
