### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by Piedone** [shouldly/shouldly#663]
Would it be possible to set up GitHub sponsorship for the project, or some other way to financially contribute?

**Comment by SimonCropp** [comment]
@JosephWoodward do you want to go with 

* GH sponsors? which requires a non-personal bank account for sponsoring a project
* Open Collective?

**Comment by JosephWoodward** [comment]
@SimonCropp I'm leaning towards the latter, though this really isn't something I've considered or have experience with. What would you suggest?

**Comment by SimonCropp** [comment]
my preference would also be Open Collective. want me to get that started?

**Comment by SimonCropp** [comment]
@JosephWoodward i need to be an admin of the org to set this up in open collective

**Comment by SimonCropp** [comment]
opencollective created https://opencollective.com/shouldly

@JosephWoodward can u create an OC account so i can make u an admin?

**Comment by SimonCropp** [comment]
GH funding created 
![image](https://user-images.githubusercontent.com/122666/95654281-ba89a380-0b4a-11eb-9ff3-df752a9a0972.png)

**Comment by SimonCropp** [comment]
note that i have left the default tiers in place. happy to take suggestions on modifications

**Comment by Piedone** [comment]
Great! One can customize the amount when making the donation (with the minimum being the amount displayed for the tier) so it's basically just a question what's the minimum you'd like somebody to be able to call them "Sponsor".

Can you confirm you're ready to receive financial contributions?

**Comment by jnm2** [comment]
@JosephWoodward What do you think?

**Comment by jnm2** [comment]
@Piedone Here's the current situation: maintainers are chronically overcommitted, and I think this is new to us. On the other hand, your generosity means an awful lot to us, and it's good to see in the ecosystem. Can I ask for a suggestion from you for what you think is a fair amount for us to set the "Sponsor" level at? Then I can set that up in Open Collective and we would be immediately ready to receive the contribution.

/cc @shouldly/core I know you're busy, but if you already have an amount in mind, now would be an ideal time to comment.

**Comment by Piedone** [comment]
I'm glad to hear!

I think what Git Extensions does (another .NET project that we also sponsor) is quite a good approach: https://opencollective.com/gitextensions There are multiple tiers for one-time and recurring contributions too. I'd probably draw the line at $50 as well (keep in mind that all amounts are minimums and people can choose to actually contribute more). However, I've never been on the receiving end of OSS financial contributions (despite being active in a lot of OSS projects) but GE's tiers look suitable for me (and apparently they work, too).

**Comment by jnm2** [comment]
@Piedone Thanks for the suggestion! I think it's copying Git Extensions now. Let us know if you notice something that could be improved.

**Comment by Piedone** [comment]
Great then! Can you confirm you're ready to receive financial contributions, you'll indeed receive the funds when setting up contributions in OC?

**Comment by jnm2** [comment]
I understand the funds will sit there until we submit expenses to transfer them to personal accounts based on whatever criteria we agree on. I don't think any configuration is needed on the OC side, just at some point @JosephWoodward will need to help decide how to split/spend it. I've never been part of a discussion like this before and possibly he hasn't either. Do you have advice?

**Comment by Piedone** [comment]
I have no experience with this so can't really comment, sorry. My personal recommendation would be to find a simple, clear rule so you don't have any differences in the future. One thing to consider, also as done by GE, is not to take payments for contributors directly but only to expenses they themselves have to pay. There e.g. hiring a graphic designer is something like this. However, I don't see how something like this would work with Shouldly.

Anyway, let me know if we can submit the sponsorship :). I just want to make sure beforehand that everything is clear on your side.

**Comment by jnm2** [comment]
Oh, I see what you're asking, and thanks!
Yes, we're ready for you to submit the sponsorship.

**Comment by Piedone** [comment]
Great, thanks!

**Comment by jnm2** [comment]
@Piedone We appreciate that! OC prompted me to tweet, hope that's fine with you.

@JosephWoodward There's money now, want to file expenses for hosting etc?

**Comment by Piedone** [comment]
Of course, thank you.
