### ISSUE TITLE
Take down other docs sites

### ISSUE THREAD

**Issue by SimonCropp** [shouldly/shouldly#669]
since we now have gitbook https://docs.shouldly.io/

@JosephWoodward can u take down 

 * https://shouldly.readthedocs.io/
 * http://docs.shouldly-lib.net/

**Comment by JosephWoodward** [comment]
I'm not sure I have access to them (I think @JakeGinnivan has access). There's still some bits that need to be migrated over from the readthedocs site too, so probably worth leaving it there until that's completed.

**Comment by jnm2** [comment]
https://github.com/shouldly/shouldly/issues/308 tracks the progress of migrating to readthedocs.

**Comment by SimonCropp** [comment]
@jnm2 @JosephWoodward i think i have migrated all the existing doco from the old sites. can u review?

**Comment by jnm2** [comment]
It looks great from the dozen or so pages I looked at! I don't have time to comb through deeply right now. If that's a need, I'd feel better if we came up with a CI check to make sure all `Should*` extension method names are documented.

**Comment by SimonCropp** [comment]
@jnm2 i did consider that as well. Although for now i think it is safe to take down the other docs sites?

**Comment by JakeGinnivan** [comment]
Am I good to stop paying for shouldly-lib.net domain now too?

So just to confirm @SimonCropp, delete the readthedocs and readme.io sites. I can do that if so

**Comment by SimonCropp** [comment]
> So just to confirm @SimonCropp, delete the readthedocs and readme.io sites. I can do that if so

@JakeGinnivan yep that correct

> Am I good to stop paying for shouldly-lib.net domain now too?

given we have `shouldly.io` i assume we dont need `shouldly-lib.net`. @JosephWoodward @jnm2 want to chime in?

**Comment by JosephWoodward** [comment]
@JakeGinnivan Yeah, you're good to stop paying for the shouldly-lib domain as I've moved it to a trendy .io domain 😊

**Comment by JakeGinnivan** [comment]
Done :)

**Comment by jnm2** [comment]
> Yeah, you're good to stop paying for the shouldly-lib domain as I've moved it to a trendy .io domain 😊

@josephwoodward Shouldly.io has now gone down: https://github.com/shouldly/shouldly/issues/860
