### ISSUE TITLE
Make ChuckedAWobbly public

### ISSUE THREAD

**Issue by robdmoore** [shouldly/shouldly#67]
I want to be able to catch it in an Automated UI test so that I can grab a screenshot.

I don't want to catch `Exception` because I want to skip the exceptions that automatically trigger screenshots.

**Comment by jmrnilsson** [comment]
Since `Shouldly.ChuckedAWobbly` is used to propagate errors to client code, it could be worth while to consider an interface or inherit from something like ArgumentException. Catching `Exception` is often regarded as bad practice.
