### ISSUE TITLE
Version 4 stable

### ISSUE THREAD

**Issue by SimonCropp** [shouldly/shouldly#670]
Whats left to do for the v4 stable release?

**Comment by SimonCropp** [comment]
ping @JosephWoodward @jnm2 @slang25 thoughts?

**Comment by jnm2** [comment]
A beta release possibly? (https://github.com/shouldly/shouldly/issues/638#issuecomment-655173490)

**Comment by SimonCropp** [comment]
yep. will release a beta as soon as @JosephWoodward grants me nuget access :)

**Comment by JosephWoodward** [comment]
Doing it tonight (sorry for being slack). It'd be great to get one final beta out before a stable v4 IMO.

**Comment by JosephWoodward** [comment]
I've released a [0003 beta](https://github.com/shouldly/shouldly/releases/tag/v.4.0.0-beta0003).

I'm not sure I can add you to the NuGet organisation as I think it's still owned by @JakeGinnivan

**Comment by jnm2** [comment]
The beta has an issue keeping me from moving to it which was just fixed (https://github.com/shouldly/shouldly/issues/674). Also @JosephWoodward I think there's a typo in the tag https://github.com/shouldly/shouldly/releases/tag/v.4.0.0-beta0003 (`v.` instead of `v`).

**Comment by JosephWoodward** [comment]
Now that's been fixed, I'll publish a new beta tonight

**Comment by SimonCropp** [comment]
@jnm2 @JosephWoodward i think we should push a stable now

**Comment by jnm2** [comment]
Can I have your thoughts on https://github.com/shouldly/shouldly/issues/698 quick?

**Comment by SimonCropp** [comment]
i started an upgrade guide https://docs.shouldly.io/documentation/3to4

any additions?

**Comment by slang25** [comment]
There are spelling fixes in the API, for example, `FilenameDescriminator` `->` `FilenameDiscriminator`

That's just from a quick scan of this:
https://www.fuget.org/packages/Shouldly/4.0.0-beta0004/lib/netstandard2.0/diff/3.0.2/

I'll have a proper look later.

**Comment by SimonCropp** [comment]
i am deploying v4 now.

**Comment by jnm2** [comment]
Thanks for keeping this moving!
