### ISSUE TITLE
Minimize access

### ISSUE THREAD

**Issue by SimonCropp** [shouldly/shouldly#671]
@whatupdave @PandaWood @xerxesb @AnthonyEgerton @JakeGinnivan

just wondering if you still want to to have access to Github and/or the nuget for shouldly?

I am thinking from a security perspective it makes sense to minimize that access if it is no  longer required

**Comment by JakeGinnivan** [comment]
You can remove me, I can request access again if I get back involved. Maybe just have at leave 2 so access is not lost if you happen to move on from the project etc

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AnthonyEgerton** [comment]
I’m happy for you to remove me. 

Cheers,
Anthony

**Comment by JosephWoodward** [comment]
@SimonCropp I've removed Jake and Anthony 👍

**Comment by PandaWood** [comment]
Hey sorry for the delay, yeah might as well remove me.

**Comment by SimonCropp** [comment]
@PandaWood thanks
