### ISSUE TITLE
int?.ShouldBeNull issue

### ISSUE THREAD

**Issue by JosephWoodward** [shouldly/shouldly#674]
It looks like in the latest 0003 release we've broken the following scenarios when using `Nullable<T>` due to the [class constraint](https://github.com/shouldly/shouldly/issues/584):

```csharp
int? age = null;
age.ShouldBeNull();

int? age = 5;
age.ShouldNotBeNull();
```

```
[CS0452] The type 'int?' must be a reference type in order to use it as parameter 'T' in the generic type or method 'ShouldBeNullExtensions.ShouldNotBeNull<T>(T?, string?)'
```

**Comment by jnm2** [comment]
Yep, just hit this too on nullable struct types. I think the only real way to address #584 would be to start shipping an analyzer along with the library.

**Comment by jnm2** [comment]
I forgot, there's a resolution to this! C# now resolves overloads in this scenario:

```cs
public static void ShouldBeNull<T>(this T? x) where T : class { }
public static void ShouldBeNull<T>(this T? x) where T : struct { }
```

```cs
((string?)null).ShouldBeNull(); // No error!
((int?)null).ShouldBeNull(); // No error!
4.ShouldBeNull(); // Error!
```

**Comment by JosephWoodward** [comment]
This has been fixed in the latest release https://www.nuget.org/packages/Shouldly/4.0.0-beta.4
