### ISSUE TITLE
ShouldCompleteInException  ?

### ISSUE THREAD

**Issue by SimonCropp** [shouldly/shouldly#694]
```
public class ShouldCompleteInException : ShouldlyTimeoutException // Need to do this to not break existing API
```

Should this be clean up since we are making breaking changes? @jnm2 @JosephWoodward

**Comment by SimonCropp** [comment]
modified here https://github.com/shouldly/shouldly/commit/50a46607fa196bbece867ce22efd812c2b3abb85

@bmpj13 any ideas?

**Comment by SimonCropp** [comment]
actually modified here https://github.com/shouldly/shouldly/commit/896b6efcf5fbb022e2a3b41eb45b6033aacf8210

@JakeGinnivan any ideas?

**Comment by JakeGinnivan** [comment]
Sorry, it's been too long

**Comment by jnm2** [comment]
The problem with removing the base class is that it silently breaks code that was catching ShouldlyTimeoutException and expecting to catch both kinds of exceptions. I don't really see the benefit to having code that catches assertion exceptions in general except perhaps utility methods.

**Comment by SimonCropp** [comment]
If there is no scenario for people to catch these exception types, i think we should remove them

**Comment by jnm2** [comment]
I'm aware I'm appealing on the basis of lack of imagination here. 😄 But removing them in a major version would be a forcing function to learn what the use cases might be that we would change our minds and support, and we can always restore them.

The framework guidelines say never to throw one of the base exception types though, so we can't remove all of them. We can make them internal though.

**Comment by SimonCropp** [comment]
In this case the FW design guidelines are wrong. They were written only to consider APIs consumed in a real running app scenario. They never took into account using exceptions to communicate information to someone running a test

**Comment by jnm2** [comment]
Hmm, maybe. I'm not sure. On the other hand, I like seeing the exception type in the test results window because it tells me the exception originated from Shouldly and not from production or third party code.

**Comment by SimonCropp** [comment]
given i dont feel strongly about it, i will close
