### ISSUE TITLE
Consider moving the solution file to the repo root

### ISSUE THREAD

**Issue by jnm2** [shouldly/shouldly#697]
Pros:
- `dotnet build`, `dotnet test`, etc would all work in the repo root
- It's easier to start VS when you leave your terminal open in the repo root (`sh`, Tab, Enter)
- It makes more sense if there are ever projects in the solution outside the `src` folder, like `build` or `deploy` or `tests` etc

Cons:
- Adding new projects will require inserting `src/` into the default path Visual Studio suggests

Can anyone else think of pros and cons?

**Comment by JosephWoodward** [comment]
I'm with you on this one, it's something I've been meaning to do at some point.
