### ISSUE TITLE
remove minver

### ISSUE THREAD

**Issue by SimonCropp** [shouldly/shouldly#705]
with how often  we deploy i dont think minver adds enough value. for me it adds friction, i had trouble getting the version correct on the last release. 

imo we should remove it and just have the version in the dir props

thoughts

**Comment by SimonCropp** [comment]
for context. i am the creator of GitVersion and i no longer use it on any of my projects. at the time, in old csproj world, it was a pain to keep the nuget version in sync with the assembly version. especially in thr context of a project producing multiple nugets. now the directory props it is simple to maintain

**Comment by JosephWoodward** [comment]
I've no strong feelings about this, so happy to do it by hand 👍

**Comment by mbhoek** [comment]
@SimonCropp I found this comment because shouldly is still listed as one of the projects using GitVersion. As you seem to be pretty explicit about no longer using GitVersion on any of your projects, you might want to get [the reference](https://gitversion.net/docs/who) removed?

**Comment by SimonCropp** [comment]
@mbhoek i am no longer part of the GitVersion project and dont have commit permissions. you should feel free to submit a pull request to fix that reference

**Comment by adamralph** [comment]
> i had trouble getting the version correct on the last release

Out of interest, do you remember what trouble you had?
