### ISSUE TITLE
docs.shouldly-lib.net is returning a 404

### ISSUE THREAD

**Issue by da1rren** [shouldly/shouldly#711]
![image](https://user-images.githubusercontent.com/2702382/98606843-de720d80-22df-11eb-8a56-62333909a2e9.png)

**Comment by da1rren** [comment]
My mistake the docs are over here: https://docs.shouldly.io/

**Comment by SimonCropp** [comment]
@da1rren the new docs is at https://docs.shouldly.io/

where did u get the old docs link? so i can fix that reference

**Comment by da1rren** [comment]
@SimonCropp Second result on google for me!

**Comment by SimonCropp** [comment]
thanks. i have request google to remove that page

**Comment by JosephWoodward** [comment]
> thanks. i have request google to remove that page

As the domain has expired, hopefully it won't take long for Google to unlist those results. 🤞
