### ISSUE TITLE
Approval methods fail with TypeInitializationException under .NET 5

### ISSUE THREAD

**Issue by slang25** [shouldly/shouldly#717]
As found by @gkinsman, when using things like `.ShouldMatchApproved()` results in an exception being thrown when targetting `net5`:

> System.TypeInitializationException : The type initializer for 'EmptyFiles.AllFiles' threw an exception.

Repo: https://github.com/gkinsman/ShouldlyRepro

This is because the `EmptyFiles` package is expected to copy an `EmptyFile` directory to the bin folder on build, and does this via targets files in the nuget package.

Something has changed in .NET 5 around the behavior of transitive dependencies here, if we explicitly reference `EmptyFile` as a top-level dependency then it works. That would be a quick workaround for Shouldly users.

I'm just creating a PR in `EmptyFiles` which I think will handle .NET5 appropriately.

**Comment by slang25** [comment]
Potential fix: https://github.com/VerifyTests/EmptyFiles/pull/71

**Comment by SimonCropp** [comment]
@gkinsman this should be fixed now. thanks @slang25 for the fix

**Comment by slang25** [comment]
Brilliant, confirmed using that repo updating with just a top-level dependency on Shouldly now does the right thing 🙂

**Comment by gkinsman** [comment]
Awesome news, thanks!
