### ISSUE TITLE
There is no PR validation build check

### ISSUE THREAD

**Issue by jnm2** [shouldly/shouldly#727]
This makes it hard to see if I'm making a mistake, and it risks placing the master branch in an undeliverable state.

I'm not sure I have access to the AppVeyor account, but GitHub Actions is also quite good. I'd be willing to set that up if that sounds desirable.

**Comment by jnm2** [comment]
Looks like multiple PRs I just submitted fail when I run `dotnet test`. I'm used to PRs saving me the time to run the entire test suite and preventing me from forgetting.

**Comment by JosephWoodward** [comment]
Yeah, we should get this fixed. I'm not sure what broke it 🤔

**Comment by jnm2** [comment]
I wonder if adding people to the org reset some token or other.

**Comment by SimonCropp** [comment]
so do we delete and recreate the appveyor project?

**Comment by jnm2** [comment]
If we're deleting AppVeyor, can we move to GitHub Actions?

**Comment by SimonCropp** [comment]
> can we move to GitHub Actions

no objections here

**Comment by jnm2** [comment]
@shouldly/core I would like to remove the AppVeyor webhooks from this repository and set up a GitHub action to do the exact same thing we were using AppVeyor for. Does that sound good?

**Comment by mcon** [comment]
I've created a couple of PRs which should fix the build: https://github.com/shouldly/shouldly/pull/780 https://github.com/shouldly/shouldly/pull/778

Seems the AppVeyor CI is running, just no statuses being posted... Would be great if the maintainers could step in here.

**Comment by jnm2** [comment]
I haven't heard from other maintainers, but I am one, so I'll start doing what I'm capable of. Right now that means creating a GitHub Actions PR validation build.

**Comment by jnm2** [comment]
This is now in place and required on PRs. This doesn't stop maintainers from merging PRs at their discretion at any time, which is important to me, but it puts the pressure in the right place.

A temporary issue with this is that GitHub has no way to trigger a PR build without someone pushing to the PR branch. So for old PRs, we will have to merge without having a build status to verify.
