### ISSUE TITLE
`ShouldBe` on Enumerables assumes that an enumerable is traversable multiple times

### ISSUE THREAD

**Issue by jswolf19** [shouldly/shouldly#735]
When `ShouldBe` on an enumerable fails, it reenters the enumerable in order to make its error message. It is my understanding, however, that enumerables are not guaranteed to be retraversable, and a test on such an enumerable results in incorrect error reporting.

My use case is with testing a CSV parser that, when calling `ReadLine()` returns an enumerable dependent on an underlying `TextReader`, so that multiple traversals of the Enumerable result in different lines. I want to avoid extra buffering and requiring that the `TextReader` be seekable.

This can be worked around by using `ToList()`.

**Comment by SimonCropp** [comment]
@jswolf19 can you share a failing unit tests as a Pull Request

**Comment by jswolf19** [comment]
@SimonCropp Yeah, I should be able to whip something up.

**Comment by SimonCropp** [comment]
@jswolf19 awesome :)
