### ISSUE TITLE
ShouldMatchApproved performance issues with large approvals

### ISSUE THREAD

**Issue by distantcam** [shouldly/shouldly#736]
We're having performance issues when using ShouldMatchApproved in various places when the exception message is shown.

- Visual studio intellisense for the exception message.
- Build server when the output of test runs shows the exception message.

This is due to the `expectedValue` being shown in the exception, when the approval is very large.

Is there a way to remove the `expectedValue` from the exception message? And possibly the diff as we don't need it either?

Repo - https://github.com/distantcam/ShouldlyIssue736

**Comment by SimonCropp** [comment]
can u share some code that replicates the perf issues?

**Comment by SimonCropp** [comment]
or if it is open source a url

**Comment by distantcam** [comment]
@SimonCropp Updated with link to reproduction

**Comment by SimonCropp** [comment]
what diff tool r u using?

**Comment by distantcam** [comment]
Beyond Compare. Why does that matter?

**Comment by SimonCropp** [comment]
would this work for u https://github.com/shouldly/shouldly/issues/749

**Comment by distantcam** [comment]
Yep, it's the same problem. Truncating or excluding the whole approval file from the exception message would fix the issue.

**Comment by distantcam** [comment]
I upgraded to the latest version and this still isn't fixed.

**Comment by jnm2** [comment]
@distantcam The pull request was merged 12 days ago and is in the 4.1.0 milestone. That's the version to keep an eye out for when we do another release.

**Comment by distantcam** [comment]
Still not fixed.

**Comment by distantcam** [comment]
Still not fixed.

**Comment by jnm2** [comment]
@distantcam It's fixed, but the fix is not published as a NuGet package yet.
