### ISSUE TITLE
Shouldly 4.0.2 adds lots of "empty.*" files to project

### ISSUE THREAD

**Issue by martincostello** [shouldly/shouldly#737]
With Should 4.0.2 installed in a test project, the project is filled with lots of files named `empty.*`, such as `empty.bmp`, `empty.docx` etc. They are further duplicated in an `EmptyFiles` folder.

![image](https://user-images.githubusercontent.com/1439341/102464488-4c7ac480-4044-11eb-9394-1bd8d8eb824e.png)

These files appear to be contained in the NuGet package, shown below in Solution Explorer.

![image](https://user-images.githubusercontent.com/1439341/102464234-045ba200-4044-11eb-92d3-5ee82004493b.png)

Looks like extra content is being hoovered up as part of the `dotnet pack` phase of your builds and being published, and then further somehow being added to the referencing project.

**Comment by martincostello** [comment]
For comparison, the 4.0.1 NuGet package is 129.77 KB compared to 4.0.2's 207.35 KB.

**Comment by SimonCropp** [comment]
can u try 4.0.3

**Comment by martincostello** [comment]
Looks like that fixed it:

![image](https://user-images.githubusercontent.com/1439341/102475733-2a883e80-4052-11eb-8b46-b333b2fd7b6c.png)
