### ISSUE TITLE
Empty files are shown as included in project in v4.0.2

### ISSUE THREAD

**Issue by loop-evgeny** [shouldly/shouldly#738]
When I upgraded my tiny test project from Shouldly v4.0.1 to 4.0.2 all the empty files Shouldly uses started appearing under the project, like this:

![image](https://user-images.githubusercontent.com/34301024/102471855-fadb3580-4055-11eb-9f35-767513236592.png)

This did not happen in v4.0.1. I don't want to see that - it's noise in the solution explorer.

(Ideally I don't really want those files copied to my build output directory, either, as they were even in v4.0.1 - can they not be embedded resources or something instead? Why are they even needed?)

**Comment by dashenxian** [comment]
The same is true of mine

**Comment by SimonCropp** [comment]
so this also happens with 4.0.3

**Comment by bert2** [comment]
4.0.3 fixed this for me.

**Comment by bert2** [comment]
thanks for fixing it so quickly, @SimonCropp 👍

**Comment by loop-evgeny** [comment]
Great, v4.0.3 fixes it, thanks!

**Comment by SimonCropp** [comment]
glad to hear

**Comment by dashenxian** [comment]
thanks for fixing it so quickly, @SimonCropp 👍
