### ISSUE TITLE
ShouldMatchApproved showing "approved" version on the right in diff tool seems counter-intuitive to me

### ISSUE THREAD

**Issue by loop-evgeny** [shouldly/shouldly#747]
When ShouldMatchApproved() fails it calls the diff tool (Beyond Compare in my case) with the "received" file first, then the "approved" file, which makes the diff too show the "approved" file on the right. I find this quite counter-intuitive. I expect the "approved/expected" on the left and the "received/actual" value on the left.

I realise that this is subjective, but if you do an image search for ["expectation vs reality"](https://www.google.com/search?q=expectations+vs+reality&tbm=isch), for example, you will find that "expectations" is almost always on the left. I'd be interested to know how many intuitively expect "approved" on the left and how many on the right.

**Comment by SimonCropp** [comment]
isnt the convention for most diff tools to be received on left and current on right. then u accept  to the right?

**Comment by loop-evgeny** [comment]
I don't think the diff tools themselves have any convention - they just display files in the order you specify on the command line.

**Comment by SimonCropp** [comment]
happy to accept a pr that optional switches it the other way

**Comment by SimonCropp** [comment]
also the "expectation vs reality" image search is mostly about joke memes. where the punch line is "the reality" and hence has to come last

**Comment by loop-evgeny** [comment]
That's true. I don't really know what other people expect on the left and right, so I'm hoping for some comments here from others!

**Comment by SimonCropp** [comment]
@loop-evgeny did u want to submit a PR for this?

**Comment by loop-evgeny** [comment]
I cloned the code, but turns out Shouldly.Tests uses .NET Framework 4.8. I don't have that installed and don't want to install it just for this, so no, not at this stage.

**Comment by jnm2** [comment]
I've always found this counterintuitive too. The test failed, and I expect to see what it was off by. If it was numeric, then I'd expect the relevant difference to be `actual` minus `expected`. Additions in `actual` would appear as additions in the diff, and subtractions as subtractions.

**Comment by SimonCropp** [comment]
shouldnt this be an issue in diffengine?

**Comment by jnm2** [comment]
@SimonCropp Hard for me to say because I haven't looked closely, but I guess I should have before marking up for grabs. This upstream issue should stay open though to track the Shouldly API work.

**Comment by SimonCropp** [comment]
this is now supported in diffengine. no changes are required in shouldly, so this should be closed https://github.com/VerifyTests/DiffEngine/blob/main/docs/diff-tool.md#leftright-diff-behavior

**Comment by jnm2** [comment]
Unless Shouldly wants to provide this option in ShouldMatchConfiguration, which is more discoverable for Shouldly users than setting an environment variable.

**Comment by SimonCropp** [comment]
yeah but this is a user preferences, that should operate on the machine level. it should not be hard coded into source and forced on every developer using the codebase

**Comment by jnm2** [comment]
Seems like a blurry line to me, but certainly let's wait and see if someone asks for it. Good point!
