### ISSUE TITLE
ShouldMatchApproved does not bring up difftool for some file extensions in Shouldly 4.x+

### ISSUE THREAD

**Issue by Ekkeir** [shouldly/shouldly#748]
After updating Shouldly from 3.x to 4.x, ShouldMatchApproved-based tests ceased bringing up a diff-tool window in Visual Studio.

It seems that "exotic" extensions are no longer accepted for some reason.

The following seems to reproduce the problem
```c#
public void ShouldMatchApprovedShouldWork()
{
    var input = Guid.NewGuid().ToString();
    // var extension = "txt"; // This brings up a difftool window still
    var extension = "graphql"; // This does NOT bring up a difftool window, while it did so in versions 3.x

    input.ShouldMatchApproved(cfg => cfg
        .WithFilenameGenerator((_, __, fileType, fileExtension) => $"ApprovedGuid.{fileType}.{fileExtension}")
        .WithFileExtension(extension));
    }
```

Visual Studio is used as a diff-tool.

**Comment by SimonCropp** [comment]
yep sounds like a bug. what progress have you made in fixing it?

**Comment by Ekkeir** [comment]
Well, I downgraded back to Shouldly 3.x for now.

I can only assume it's somehow related to migration to diffengine in 4.0.

**Comment by SimonCropp** [comment]
glad you found a fix that works for you

**Comment by Ekkeir** [comment]
Any plans to fix it though? Especially if it does seems to be a bug?
