### ISSUE TITLE
Truncate output of ShouldMatchApproved

### ISSUE THREAD

**Issue by loop-evgeny** [shouldly/shouldly#749]
When ShouldMatchApproved fails it outputs

> should match approved with options: Ignoring line endings
> ... (whole approved file here)
>     difference
> Showing some of the 829476 differences

My "approved" file is ~900 KB and such an amount of text is not handled well by tools like Visual Studio and TeamCity. Those tools *should* of course handle it better, but Shouldly can easily work around it by truncating the output to some reasonable length - nobody is going to read 900 KB anyway.

**Comment by SimonCropp** [comment]
what size would u truncate to ?

**Comment by loop-evgeny** [comment]
It would take some experimentation to see what VS and TeamCity handle but off the top of my head, I'd say ~ 50-100 KB. Seems unlikely that a person would manually inspect more text that to see the differences. They'd likely need to use the diff tool to compare received and approved for any more.

**Comment by loop-evgeny** [comment]
Raised a TeamCity issue for this, by the way: https://youtrack.jetbrains.com/issue/TW-69539
