### ISSUE TITLE
Enabling the Discussions tab

### ISSUE THREAD

**Issue by jnm2** [shouldly/shouldly#771]
@shouldly/core What do you think about turning on the GitHub Discussions tab for this repository? Here's an example of what it might look like: https://github.com/dotnet/roslyn/discussions

I would probably have moved https://github.com/shouldly/shouldly/issues/756 to a discussion under the Ideas category. Is that the kind of place you'd want that to be, or should we stick with issues for now?

**Comment by jnm2** [comment]
@JosephWoodward How do you feel about me taking action on things like this by default, as we all deal with the reality that we don't get a chance to see and respond to things as often as we like?

**Comment by JosephWoodward** [comment]
@jnm2 Sounds like a good idea to me! As I've not had much time to dedicate to Shoudly recently, you've been contributing to Shouldly long enough to understand the project's general direction to feel free to make any changes you see fit.

**Comment by jnm2** [comment]
Cool, nice to know that ccing isn't coming across as spamming! I turned on the Discussions feature and I'll look at moving things on a case-by-case basis.
