### ISSUE TITLE
TaskShould.Throw or overload to Should.Throw?

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#79]

**Comment by PureKrome** [comment]
@JakeGinnivan again, sorry to cast 'ressurect' on such an old thread, but I was [re-reading my SO thread](http://stackoverflow.com/a/22406846/30674) about this today .. and noticed [Stephen Cleary's](http://blog.stephencleary.com/) reply in there. That guy know's his `async/await` stuff - and he's got some code for an async throw's method.

Thoughts on adding that in, sir?

(note: SC's comment might now be out of date, considering the time between his answer and today's current state).

**Comment by JakeGinnivan** [comment]
Hey

The support is in another file - https://github.com/shouldly/shouldly/blob/master/src/Shouldly/ShouldThrowTaskExtensions.cs#L10

We made the decision to block rather than requiring to await the Should.Throw method. I think this should all work

**Comment by PureKrome** [comment]
Why block out of interest (as opposed to .. say . giving people a choice) ?

**Comment by JakeGinnivan** [comment]
We support .net 4.0. Without async/await support blocking was the easier option.

Is there a particular issue you are having?

**Comment by JakeGinnivan** [comment]
Though adding an overload called `ThrowAsync` which returns the task and is required to be awaited sounds like a good idea

**Comment by PureKrome** [comment]
I don't think so - was more worried about Stephen's summary. My code is simple - so it's working right now. But if he was right .. i'm worried other errors might pop up later with more complex `async/await` code.

So having another method (it's not really an overload considering the method doesn't exist, yet) - could be done? he even did the code :) :clap: :balloon: :cake:

**Comment by JakeGinnivan** [comment]
It should be fine. Shouldly will work with more advanced async/await scenarios fine. 

I run the task explicitly and remove any synchronisation context so await's inside the code under test cannot jump back onto the unit test sync context causing a deadlock.

**Comment by PureKrome** [comment]
Ah kewl :)

Could the new method be added as an option?

![weeeeee](http://deathstarpr.com/wp-content/uploads/2013/05/HanSoloCocky.png)

**Comment by JakeGinnivan** [comment]
https://github.com/shouldly/shouldly/issues/172
