### ISSUE TITLE
Should.ThrowAsync<Exception> does not fail for a succeeding task

### ISSUE THREAD

**Issue by hwanders** [shouldly/shouldly#818]
The assertion `Should.ThrowAsync<TException>` with the generic type `Exception` will **not** fail for a successful task.
Instead it returns  a `ShouldAssertException` which I think should never be returned but only thrown.

This means that some tests including assertions about certain processes to fail (with an unknown exception) will appear green although the processes succeed.

Changing the asserted exception type to any other one works: the succeeding tasks gets detected and the assertion fails.

For reference: xunit's `Assert.ThrowsAnyAsync<Exception>(...)` properly fails in this case.

Demo code for Shouldly 4.0.3 (with xunit 2.4.1 on Microsoft.NET.Test.Sdk 16.10.0 on net5.0 with C# 9.0):

```csharp
[Fact]
public async Task ShouldThrowAsyncException_SucceedingTask_ShouldFailAssertion()
{
    // for reference, this assertion passes
    await Should.NotThrowAsync(() => Task.CompletedTask);

    // assert the opposite
    var ex = await Should.ThrowAsync<Exception>(() => Task.CompletedTask);

    // assertion should have failed!
    throw new Exception(
        $"{nameof(Should.ThrowAsync)} has not complained about the task's success; " +
        $"instead it returned a {ex.GetType().Name}"
    );
}
```

**Comment by adam-knights** [comment]
New to this project, but fancied having a dig in the code. It is down to [this line](https://github.com/shouldly/shouldly/blob/037a2b9c118aa266a84988d9adf0301c4ca1ad5a/src/Shouldly/ShouldStaticClasses/ShouldThrowTaskAsync.cs#L55). When your expectedException type is `Exception` the `ShouldAssertException` is a child of `Exception` and matches, when its any other type of Exception it hits the second part of the switch and throws it and behaves as expected.

I've posted a PR with a fix that also adds a test that fails before my fix and passes afterward.

**Comment by hwanders** [comment]
I think you've analyzed this correctly and the test is correct.
The `e.ShouldBeOfType<ShouldAssertException>()` in the `catch (ShouldAssertException e)` block seems redundant though.

**Comment by ggrondecki** [comment]
I just ran into this issue today and I see the PR for it is still open. Any ETA on when this will be released?
