### ISSUE TITLE
Shouldly should not add tons of dependencies

### ISSUE THREAD

**Issue by taori** [shouldly/shouldly#826]
There's a ton of odd dependencies introduced by the upgrade from 3x to 4x
I get that DiffEngine and EmptyFiles probably makes sense, but things like

Registry, MEF, ConfigurationManager, SqlClient and all the other seem pretty weird. Was there any thought put into crosscompiling so there are less dependencies?

![grafik](https://user-images.githubusercontent.com/5545184/132599335-47f1cabf-fe0b-4997-a4c7-b96527a484c4.png)
![grafik](https://user-images.githubusercontent.com/5545184/132599393-43210b86-f42d-4fdc-8168-0b05aa5a5b0c.png)

**Comment by SimonCropp** [comment]
i dont know why nuget is resolving that list. the actual count of dependencies for shouldly is only 4 https://www.nuget.org/packages/Shouldly

 * DiffEngine (>= 6.4.9)
 * EmptyFiles (>= 2.3.3)
 * Microsoft.CSharp (>= 4.7.0)
 * System.Memory (>= 4.5.4)

so perhaps raise it with the nuget team?

**Comment by taori** [comment]
After a brief investigation i would assume the original offender here is https://www.nuget.org/packages/DiffEngine/6.4.9

**Comment by SimonCropp** [comment]
happy accept a PR to diffengine that reduces the number of dependencies

**Comment by taori** [comment]
Yeah. Will look into that shortly. Just writing an issue @diffengine atm so it is tracked.

**Comment by SimonCropp** [comment]
hopefully this should fix it

**Comment by taori** [comment]
@SimonCropp @slang25 Thanks for the quick fix.

When is this going to be published though? - Last nuget package update was 10months ago. Is CI broken or is the project in a "collection features and fixes" state?

**Comment by SimonCropp** [comment]
@taori  i am not a core maintainer or this project. so i have no idea
