### ISSUE TITLE
Support Net Framework

### ISSUE THREAD

**Issue by Edgaras91** [shouldly/shouldly#829]
I have a class library, that builds 2 releases, one for net core 3.1, and one for net460 (.NET Framework 4.6.0).
When I run my tests project which is on net core 3.1, it only covers the core 3.1 build library, resulting in "half-covered code".

Changing the TargetFramework to:
<TargetFrameworks>net460;netcoreapp3.1</TargetFrameworks> 
Fails to load the Shouldly library.

Can we have support for net framework 4.6.0 (or alternative framework version) please?

**Comment by SimonCropp** [comment]
given 4.6 was released 6 years ago, i dont think it is reasonable to request an OSS library to put in the effort to support it. 

you should be able to use 4.6.1
