### ISSUE TITLE
Add support for IReadOnlyDictionary

### ISSUE THREAD

**Issue by rick-palmsens** [shouldly/shouldly#834]
`ShouldContainKey` works with `IDictionary`, but not with `IReadOnlyDictionary`.

**Comment by vladimir-kovalyuk** [comment]
Voting for this

**Comment by SimonCropp** [comment]
@vladimir-kovalyuk the best way to vote is with a Pull Request

**Comment by jnm2** [comment]
@martincostello kindly [offered](https://github.com/shouldly/shouldly/pull/859#issuecomment-2306570145) to implement. Thanks, let us know if you need anything!

**Comment by jnm2** [comment]
@martincostello Possibly, if you comment here, GitHub might allow me to set you as the assignee of this issue. Or perhaps it only allows that for the issue author, I'm not sure.

**Comment by martincostello** [comment]
"Comment" 😄
