### ISSUE TITLE
No new releases since 2020

### ISSUE THREAD

**Issue by Compufreak345** [shouldly/shouldly#841]
Hi all,

the last release is from December 2020 - the last commit in the main branch is from October 2021.

Are there any new releases planned so the users of the Nuget package can benefit from the latest changes, like enabling field comparisons?

Thanks!

**Comment by slang25** [comment]
Hi @Compufreak345, thanks for raising this, I'll take a look at what's involved in getting a new release out 🙂

**Comment by jacobjmarks** [comment]
Seconded. I am particularly interested in getting the functionality added with #790

**Comment by SimonCropp** [comment]
4.1 is released

**Comment by jacobjmarks** [comment]
Great news, thanks @SimonCropp. Looks like a GitHub release also needs to be added?

**Comment by SimonCropp** [comment]
@jacobjmarks https://github.com/shouldly/shouldly/releases/tag/4.1.0
