### ISSUE TITLE
Improve test coverage.

### ISSUE THREAD

**Issue by ilia-murzinov** [shouldly/shouldly#86]
Test coverage is pretty poor right now, about 1 test per method.
We should improve the number of tests.

**Comment by gauravdesale** [comment]
I was just curious about the platform and was wondering if there is a file that has these in them

**Comment by JosephWoodward** [comment]
@gauravdesale Yes, all the tests can be found [here](https://github.com/shouldly/shouldly/tree/master/src/Shouldly.Tests).
