### ISSUE TITLE
Feature Request: task.ShouldComplete()

### ISSUE THREAD

**Issue by rettigcd** [shouldly/shouldly#880]
Many times my tests fail because an asynchronous task hangs because it is blocked by something it shouldn't be.  It would be super-helpful to catch these issues (and not have all the tests hang) if we had an extension method as follows:

```
const int defaultWaitMs = 3000;
public static async Task ShouldComplete( this Task task, string taskDescription = "[Task]", int ms = defaultWaitMs ) {
	TimeSpan waitTime = TimeSpan.FromMilliseconds( ms );
	await task.WaitAsync( waitTime );
	if(!task.IsCompletedSuccessfully)
		throw new Exception( $"{taskDescription} did not complete in {waitTime}" );
}
```
An alternate method signatures might be:
ShouldCompleteIn( this Task task, int ms, string taskDescription="[Task]"

**Comment by rettigcd** [comment]
I started to create the PR but .WaitAsync(...) is not available.  Maybe I should upgrade the project to .NET 7?

**Comment by sungam3r** [comment]
You can use polyfill like that https://github.com/graphql-dotnet/server/pull/985/files#diff-e10407568aa1bc9f1cb19a0d9dce5d5433341e47fb368ee1f83d47c8689df8d1

**Comment by rettigcd** [comment]
It looks to me like this feature already exists via `.TimeoutAfter(...)`
