### ISSUE TITLE
Nuget package has wrong URL for release note "https://github.com/shouldly/releases/tag/4.2.1"

### ISSUE THREAD

**Issue by Bertk** [shouldly/shouldly#901]
![image](https://github.com/shouldly/shouldly/assets/2315215/e6c600c0-6e60-423a-9b4c-7452de0d2caa)

This URL will work : https://github.com/shouldly/shouldly/releases/tag/4.2.1

Line in project file: https://github.com/shouldly/shouldly/blob/master/src/Shouldly/Shouldly.csproj#L20

**Comment by slang25** [comment]
Thanks for reporting this, this should be fixed for our next release 🙂 (fixed in 49684cb953c630bb2cda294896b55fb9bdc34bcd)
